#!groovy

@Library('devopslib') _

pipeline {
    options {
        timeout(time: 1, unit: 'HOURS')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/local/Handbook-pdf-CD/jenkins-agent.yaml'
        }
    }

    parameters {
        credentials(name: 'certificate', credentialType: 'com.cloudbees.plugins.credentials.common.StandardCredentials', defaultValue: 'kyligence-git', required: true)
        string(name: 'branch/commitid', defaultValue: 'master', description: 'Branch name or commit Id, which will be fetch the code.')
    }

    stages {
        stage("Checkout Source Code") {
            steps {
                container("build") {
                    dir("sourcecode") {
                        script {

                            // 需要配置本地 git mirror 后才可用
                            // retry(3) {
                            //     sshCmdWithCredentials(
                            //         'bash -c /var/lib/git/pull.sh',
                            //         'private_git',
                            //         ['name':'localhost','host':'10.1.2.192', 'allowAnyHosts': true]
                            //     )
                            //     githubCheckout 'Kyligence-Enterprise-Manual'
                            // }

                            retry(3) {
                                githubCheckout 'Kyligence-Enterprise-Manual', 'master', 'https', 'github.com', '+refs/heads/*:refs/remotes/origin/*'
                            }
                        }
                    }
                }
            }
        }
        stage('Building Package') {
            steps {
                container("build") {
                    dir("sourcecode") {
                        sh "mkdir -p /var/cicd/handbook/ && \
                        ls "
                    }
                }
            }
        }
    }
}
