#!groovy

@Library('devopslib') _

pipeline {
    options {
        timeout(time: 1, unit: 'HOURS')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/local/Handbook-pdf-CD/jenkins-agent.yaml'
        }
    }

    parameters {
        string(name: 'repo', defaultValue: 'Kyligence', description: 'Kap repo?')
        string(name: 'branch', defaultValue: 'master', description: 'Kap branch?')
        string(name: 'version', defaultValue: '', description: 'Kap version?')
        credentials(name: 'certificate', credentialType: 'com.cloudbees.plugins.credentials.common.StandardCredentials', defaultValue: 'kyligence-git', required: true)
    }

    stages {
        stage("Clone") {
            steps {
                container("git") {
                    dir("sourcecode") {
                        script {
                            retry(3) {
                                githubCheckout 'Kyligence-Enterprise-Manual', null, 'https', 'github.com', '+refs/heads/*:refs/remotes/origin/*'
                            }
                        }
                        sh("ls -al ${env.WORKSPACE}")
                    }
                }
            }
        }
        stage('Deadline') {
            steps {
                container("build") {
                    dir("sourcecode") {
                        echo 'Deadline'
                        sh "gitbook build & gitbook pdf"
                        sh "ls -al ${env.WORKSPACE}"
                    }
                }
            }
        }
        stage('Package') {
            steps {
                container("build") {
                    dir("sourcecode") {
                       echo 'Package'
                    }
                }
            }
        }
        stage('Upload') {
            steps {
                container("build") {
                    dir("sourcecode") {
                        echo 'Upload'
                    }
                }
            }
        }
    }
}
