#!groovy

@Library('devopslib') _

pipeline {
    options {
        timeout(time: 1, unit: 'HOURS')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/Newten-Test_CH/jenkins-agent.yaml'
        }
    }

    parameters {
        string(name: 'repo', defaultValue: '', description: 'Kap repo?')
        string(name: 'branch', defaultValue: '', description: 'Kap branch?')
        credentials(name: 'certificate', credentialType: 'com.cloudbees.plugins.credentials.common.StandardCredentials', defaultValue: 'kyligence-git', required: true)
    }

    stages {
        stage("Checkout Source Code") {
            steps {
                container("git") {
                    dir("sourcecode") {
                        script {
                            retry(3) {
                                sshCmdWithCredentials(
                                    'bash -c /var/lib/git/pull.sh',
                                    'private_git',
                                    ['name':'localhost','host':'10.1.2.192', 'allowAnyHosts': true]
                                )
                                githubCheckout 'KAP', null, 'git', '10.1.2.192', '+refs/pull/*:refs/remotes/origin/pr/*'
                            }
                        }
                    }
                }
            }
        }
        stage('Maven Install') {
            steps {
                container("maven") {
                    dir("sourcecode") {
                        sh script: """
                            mvn -U clean install -T 2C -pl src/external -Dmaven.compile.fork=true -DskipTests
                            mvn -U clean install -T 2C -Dmaven.compile.fork=true -DskipTests
                        """
                    }
                }
            }
        }
        stage('Testing ClickHouse IT') {
            steps {
                script {
                    container('maven') {
                        dir("sourcecode") {
                            sh script: """
                                mvn test -pl src/second-storage/clickhouse-it -Duser.timezone=GMT+8
                            """
                        }
        }
                }
            }
            post {
                always {
                    timestamps {
                        junit skipPublishingChecks: true, testResults: 'sourcecode/**/target/surefire-reports/*.xml'
                    }
                }
            }
        }
    }
}