# docker pull mysql:5.7

# echo -n 'kyligence' | base64

apiVersion: v1
kind: Secret
metadata:
  namespace: <<<namespace>>>
  name: mysql
type: Opaque
data:
  password: a3lsaWdlbmNl
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: <<<namespace>>>
  name: mysql
  labels:
    app: mysql
data:
  mysql.cnf: |
    [mysqld]
    # set the buffer pool size to 80% of the machine's physical memory size
    # The total buffer pool size is divided among all the buffer pools
    # For best efficiency, specify a combination of innodb_buffer_pool_instances and innodb_buffer_pool_size so that each buffer pool instance is at least 1GB.
    innodb_buffer_pool_size = 1GB
    innodb_buffer_pool_instances = 1

    innodb_flush_log_at_trx_commit = 1
    sync_binlog = 1
    max_connections = 200
    innodb_log_file_size = 500MB
    innodb_log_files_in_group = 2
    server_id = 1000
    log_bin = BIN-LOG
    binlog_format = ROW
    innodb_io_capacity = 200

    character_set_server=utf8
    init_connect='SET NAMES utf8'
    init_connect='SET collation_connection = utf8_unicode_ci'
    collation_server=utf8_unicode_ci

    [client]
    default_character_set=utf8
  mysql-init.sql: |
    CREATE DATABASE hive DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
    create user 'hive'@'%' identified by 'hive';
    grant all on hive.* to 'hive'@'%';

    CREATE DATABASE ke_metadata DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
    create user 'kylin'@'%' identified by 'kylin';
    grant all on ke_metadata.* to 'kylin'@'%';

    flush privileges;

    USE ke_metadata;

    CREATE TABLE `ke_metadata` (
      `META_TABLE_KEY` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
      `META_TABLE_CONTENT` longblob,
      `META_TABLE_TS` bigint(20) DEFAULT NULL,
      `META_TABLE_MVCC` bigint(20) DEFAULT NULL,
      PRIMARY KEY (`META_TABLE_KEY`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

    CREATE TABLE `ke_metadata_audit_log` (
      `id` bigint(20) NOT NULL AUTO_INCREMENT,
      `meta_key` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
      `meta_content` longblob,
      `meta_ts` bigint(20) DEFAULT NULL,
      `meta_mvcc` bigint(20) DEFAULT NULL,
      `unit_id` varchar(50) DEFAULT NULL,
      `operator` varchar(100) DEFAULT NULL,
      `instance` varchar(100) DEFAULT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=213 DEFAULT CHARSET=utf8;

    CREATE TABLE `ke_metadata_epoch` (
      `epoch_id` int(11) DEFAULT NULL,
      `epoch_target` varchar(255) DEFAULT NULL,
      `current_epoch_owner` varchar(2000) DEFAULT NULL,
      `last_epoch_renew_time` bigint(20) DEFAULT NULL,
      `server_mode` varchar(10) DEFAULT NULL,
      `maintenance_mode_reason` varchar(5000) DEFAULT NULL,
      `mvcc` bigint(20) DEFAULT NULL,
      `reserved_field_1` varchar(50) DEFAULT NULL,
      `reserved_field_2` longblob,
      `reserved_field_3` longblob,
      UNIQUE KEY `ke_metadata_epoch_epoch_target_uindex` (`epoch_target`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

    CREATE TABLE `ke_metadata_query_history` (
      `id` bigint(20) NOT NULL AUTO_INCREMENT,
      `query_id` varchar(50) DEFAULT NULL,
      `sql_text` text,
      `sql_pattern` text,
      `duration` bigint(20) DEFAULT NULL,
      `total_scan_bytes` bigint(20) DEFAULT NULL,
      `total_scan_count` bigint(20) DEFAULT NULL,
      `result_row_count` bigint(20) DEFAULT NULL,
      `submitter` varchar(255) DEFAULT NULL,
      `realizations` text,
      `server` varchar(50) DEFAULT NULL,
      `error_type` varchar(50) DEFAULT NULL,
      `engine_type` varchar(30) DEFAULT NULL,
      `cache_hit` tinyint(1) DEFAULT NULL,
      `query_status` varchar(20) DEFAULT NULL,
      `index_hit` tinyint(1) DEFAULT NULL,
      `query_time` bigint(20) DEFAULT NULL,
      `month` varchar(10) DEFAULT NULL,
      `query_first_day_of_month` bigint(20) DEFAULT NULL,
      `query_first_day_of_week` bigint(20) DEFAULT NULL,
      `query_day` bigint(20) DEFAULT NULL,
      `is_table_index_used` tinyint(1) DEFAULT NULL,
      `is_agg_index_used` tinyint(1) DEFAULT NULL,
      `is_table_snapshot_used` tinyint(1) DEFAULT NULL,
      `project_name` varchar(100) NOT NULL,
      `reserved_field_1` varchar(50) DEFAULT NULL,
      `reserved_field_2` varchar(50) DEFAULT NULL,
      `reserved_field_3` longblob,
      `reserved_field_4` longblob,
      PRIMARY KEY (`id`,`project_name`),
      KEY `ke_metadata_query_history_ix1` (`query_time`),
      KEY `ke_metadata_query_history_ix2` (`query_first_day_of_month`),
      KEY `ke_metadata_query_history_ix3` (`query_first_day_of_week`),
      KEY `ke_metadata_query_history_ix4` (`query_day`),
      KEY `ke_metadata_query_history_ix5` (`duration`)
    ) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8;

    CREATE TABLE `ke_metadata_query_history_realization` (
      `id` bigint(20) NOT NULL AUTO_INCREMENT,
      `query_id` varchar(255) DEFAULT NULL,
      `model` varchar(255) DEFAULT NULL,
      `layout_id` varchar(255) DEFAULT NULL,
      `index_type` varchar(255) DEFAULT NULL,
      `duration` bigint(20) DEFAULT NULL,
      `query_time` bigint(20) DEFAULT NULL,
      `project_name` varchar(255) NOT NULL,
      PRIMARY KEY (`id`,`project_name`),
      KEY `ke_metadata_query_history_realization_ix1` (`query_time`),
      KEY `ke_metadata_query_history_realization_ix2` (`model`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

    CREATE TABLE `ke_metadata_rec_candidate` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `project` varchar(100) DEFAULT NULL,
      `model_id` varchar(40) DEFAULT NULL,
      `unique_flag` varchar(200) DEFAULT NULL,
      `semantic_version` int(11) DEFAULT NULL,
      `type` tinyint(4) DEFAULT NULL,
      `rec_entity` text,
      `depend_ids` text,
      `layout_metric` text,
      `cost` double DEFAULT NULL,
      `total_latency_of_last_day` double DEFAULT NULL,
      `hit_count` int(11) DEFAULT NULL,
      `total_time` double DEFAULT NULL,
      `max_time` double DEFAULT NULL,
      `min_time` double DEFAULT NULL,
      `query_history_info` text,
      `state` tinyint(4) DEFAULT NULL,
      `create_time` mediumtext,
      `update_time` mediumtext,
      `reserved_field_1` varchar(50) DEFAULT NULL,
      `reserved_field_2` longblob,
      `reserved_field_3` longblob,
      PRIMARY KEY (`id`),
      UNIQUE KEY `ke_metadata_rec_candidate_idx` (`project`,`model_id`,`unique_flag`,`semantic_version`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

    CREATE TABLE `ke_metadata_session` (
      `SESSION_ID` varchar(180) NOT NULL,
      `CREATION_TIME` bigint(20) NOT NULL,
      `LAST_ACCESS_TIME` bigint(20) NOT NULL,
      `MAX_INACTIVE_INTERVAL` int(11) NOT NULL,
      `PRINCIPAL_NAME` varchar(100) DEFAULT NULL,
      PRIMARY KEY (`SESSION_ID`),
      KEY `ke_metadata_session_IX1` (`LAST_ACCESS_TIME`),
      KEY `ke_metadata_session_IX2` (`PRINCIPAL_NAME`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

    CREATE TABLE `ke_metadata_session_ATTRIBUTES` (
      `SESSION_ID` varchar(180) NOT NULL,
      `ATTRIBUTE_NAME` varchar(200) NOT NULL,
      `ATTRIBUTE_BYTES` blob NOT NULL,
      PRIMARY KEY (`SESSION_ID`,`ATTRIBUTE_NAME`),
      KEY `ke_metadata_session_ATTRIBUTES_IX1` (`SESSION_ID`),
      CONSTRAINT `ke_metadata_session_ATTRIBUTES_FK` FOREIGN KEY (`SESSION_ID`) REFERENCES `ke_metadata_session` (`SESSION_ID`) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
---
apiVersion: v1
kind: Service
metadata:
  namespace: <<<namespace>>>
  name: mysql
  labels:
    app: mysql
spec:
  ports:
  - name: mysql
    port: 3306
  selector:
    app: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: <<<namespace>>>
  name: mysql-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: rbd-dynamic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: <<<namespace>>>
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: password
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
          subPath: mysql
        - name: config
          mountPath: /etc/mysql/conf.d/mysql.cnf
          subPath: mysql.cnf
        - name: config
          mountPath: /docker-entrypoint-initdb.d/mysql-init.sql
          subPath: mysql-init.sql
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 1
            memory: 2Gi
        livenessProbe:
          exec:
            command:
              - /bin/bash
              - '-ec'
              - |
                mysqladmin status -uroot -p${MYSQL_ROOT_PASSWORD}
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 20
        readinessProbe:
          exec:
            command:
              - /bin/bash
              - '-ec'
              - |
                mysql -ukylin -pkylin -e "SELECT 1 FROM ke_metadata.ke_metadata_session_ATTRIBUTES"
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 20
      volumes:
      - name: config
        configMap:
          name: mysql
      - name: data
        persistentVolumeClaim:
          claimName: mysql-pvc