apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway.fullname" . }}
data:
  config.yaml: |
    spring:
      redis:
        host: {{ .Values.global.redis.host | default .Values.config.redis.host }}
        database: {{ .Values.global.redis.database | default .Values.config.redis.database }}
        password: {{ .Values.global.redis.password | default .Values.config.redis.password }}
    saas:
      gateway:
        integrate:
          iam: {{.Values.saas.gateway.integrate.iam}}
    kyligence:
      saas-gateway:
        deploy-model: {{ .Values.global.kyligence.deployMode | default .Values.kyligence.deployMode }}