apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-common
  namespace: cicd
spec:
  capacity:
    storage: 300Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-06dbd98a1c4896b01::fsap-0c348454eb8f5480c
