#!groovy

@Library('devopslib') _

pipeline {
    options {
        timeout(time: 2, unit: 'HOURS')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/yaml/jenkins-package-agent.yaml'
        }
    }

    parameters {
        string(name: 'repo', defaultValue: 'Kyligence', description: 'kyligence server starter parent repo')
        string(name: 'branch', defaultValue: 'main', description: 'kyligence server starter parent repo branch')
        string(name: 'version', description: 'release version')
        booleanParam(name: 'deploy', defaultValue:true, description:'推送到仓库')
    }

    stages {
        stage('1.Pull Code') {
            steps {
                container('build') {
                    dir('sourcecode') {
                        script {
                            if (!params.branch) {
                                error 'branch 参数不能为空'
                            }

                            echo 'checkout kyligence server starter parent'
                            retry(3) {
                                githubCheckout 'kyligence-server-starter-parent', params.branch, 'https', 'github.com', '+refs/pull/*:refs/remotes/origin/pr/* +refs/heads/*:refs/remotes/origin/*', 'kyligence-git', params.repo
                            }
                        }
                    }
                }
            }
        }
        stage('2.Building Package') {
            steps {
                container('build') {
                    dir('sourcecode') {
                        script {
                            if(params.version) {
                                sh "mvn versions:set -DnewVersion=${params.version}"
                            }

                            if (params.deploy) {
                                sh """
                                echo "deploy kyligence server starter parent"
                                mvn clean deploy -Dmaven.test.skip=true -Pdev
                                """
                            } else {
                                sh """
                                echo "build kyligence server starter parent"
                                mvn clean package -Dmaven.test.skip=true
                                """
                            }
                        }
                    }
                }
            }
        }
    }
}
