#!groovy

@Library('devopslib') _

pipeline {
    options {
        timeout(time: 1, unit: 'HOURS')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/local/Ke-45X-SP-QA-CD/jenkins-agent.yaml'
        }
    }

    parameters {
        string(name: 'version', defaultValue: 'ke-4.5.x-sp-qa', description: 'Kap version?')
        string(name: 'repo', defaultValue: 'Kyligence', description: 'Kap repo?')
        string(name: 'branch', defaultValue: 'ke-4.5.x-sp-qa', description: 'Kap branch?')
        credentials(name: 'certificate', credentialType: 'com.cloudbees.plugins.credentials.common.StandardCredentials', defaultValue: 'kyligence-git', required: true)
    }

    stages {
        
        stage('Building Package') {
            steps {
                container("build") {
                    dir("sourcecode") {
                        buildNewten(params.version)
                        archiveArtifacts artifacts: 'dist/*.tar.gz', fingerprint: true, followSymlinks: false, onlyIfSuccessful: true
                        sh "mkdir -p /var/cicd/artifacts/dev/${JOB_NAME} && \
                        cp dist/*.tar.gz /var/cicd/artifacts/dev/${JOB_NAME}/KE-${JOB_NAME}-${version}.${BUILD_NUMBER}.tar.gz"
                    }
                }
            }
        }
    }
}
