---
kind: "Pod"
name: "jenkins-agent"
spec:
  containers:
    - name: "maven"
      tty: true
      command:
        - "cat"
      image: "maven:3.6.3-openjdk-8"
      imagePullPolicy: "IfNotPresent"
      resources:
        limits:
          memory: "8Gi"
          cpu: "4"
        requests:
          memory: "8Gi"
          cpu: "4"
      volumeMounts:
        - mountPath: "/root/.m2/repository"
          name: "jenkins-common"
          subPath: "maven3/repository"
        - name: "kyligence-repo"
          mountPath: /root/.m2/repository/io/kyligence
  nodeSelector:
    cicd: ''
  tolerations:
    - key: cicd
      operator: Equal
      effect: NoSchedule
  volumes:
    - name: "jenkins-common"
      persistentVolumeClaim:
        claimName: "jenkins-common"
    - name: "kyligence-repo"
      emptyDir: { }
