#!groovy

@Library('devopslib@wip') _

pipeline {
    options {
        timeout(time: 1, unit: 'HOURS')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/ofs/DevOps/JenkinsJobExtract/jenkins-agent.yaml'
        }
    }

    triggers {
        cron('0 * * * *')
    }

    stages {
        stage('Compile') {
            steps {
                container('maven') {
                    dir('jenkins-etl') {
                        sh script: """
                            mvn clean install -DskipTests
                        """
                    }
                }
            }
        }
        stage('Extract') {
            steps {
                script {
                    container('maven') {
                        dir('jenkins-etl') {
                            withCredentials([[
                                $class: 'AmazonWebServicesCredentialsBinding',
                                credentialsId: "aws_global_s3_cp",
                                accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                                secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {

                               sh script: """
                                    cd target && java -jar -DAWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} -DAWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} jenkins-etl-1.0-SNAPSHOT-jar-with-dependencies.jar
                               """
                            }
                        }
                    }
                }
            }
        }
    }
}
