apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: hdfs-namenode-claim0
  name: hdfs-namenode-claim0
  namespace: <<<namespace>>>
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
