FROM nikolaik/python-nodejs:python3.8-nodejs16

LABEL version="handbook2:2.0"

RUN npm install -g @node-rs/jieba
RUN npm install -g @cmfcmf/docusaurus-search-local --registry=https://registry.npmmirror.com