apiVersion: v1
kind: Service
metadata:
  name: yarn-resourcemanager
  namespace: <<<namespace>>>
  labels:
    metrics-exporter: prometheus
spec:
  ports:
    - name: "8088"
      port: 8088
      targetPort: 8088
    - name: "8030"
      port: 8030
      targetPort: 8030
    - name: "8031"
      port: 8031
      targetPort: 8031
    - name: "8032"
      port: 8032
      targetPort: 8032
    - name: "8033"
      port: 8033
      targetPort: 8033
    - port: 8080
      name: metrics
  selector:
    io.kompose.service: yarn-resourcemanager
