apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: yarn-resourcemanager
  name: yarn-resourcemanager
  namespace: <<<namespace>>>
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: yarn-resourcemanager
  template:
    metadata:
      labels:
        io.kompose.service: yarn-resourcemanager
    spec:
      volumes:
      - name: config
        configMap:
          name: yarn-xml
      - name: exporter-dir
        emptyDir: {}
      - name: jmx-config
        configMap:
          name: jmx-exporter-config
      initContainers:
      - name: jmx-exporter
        image: 10.1.9.11:31500/jmx-prometheus-javaagent:0.16.1
        volumeMounts:
        - name: exporter-dir
          mountPath: /opt/jmx-exporter/
        command: ["cp", "/opt/jmx_prometheus_javaagent-0.16.1.jar", "/opt/jmx-exporter/"]
      containers:
        - name: yarn-resourcemanager
          image: kyligence/hadoop:2.10.1
          volumeMounts:
          - name: config
            mountPath: /etc/hadoop/fair-scheduler.xml
            subPath: fair-scheduler.xml
          - name: exporter-dir
            mountPath: /opt/jmx-exporter/
          - name: jmx-config
            mountPath: /opt/jmx-exporter/config.yaml
            subPath: config.yaml
          ports:
            - containerPort: 8088
            - containerPort: 8030
            - containerPort: 8031
            - containerPort: 8032
            - containerPort: 8033
            - containerPort: 8080
              name: metrics
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
            httpGet:
              path: /
              port: 8088
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
            httpGet:
              path: /
              port: 8088
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 1
              memory: 2Gi
          envFrom:
          - configMapRef:
              name: yarn-env
          env:
          - name: HADOOP_MODE
            value: resourcemanager
          - name: HADOOP_WEBHDFS_PORT
            value: "50070"
          - name: FORMAT_MESSAGES_PATTERN_DISABLE_LOOKUPS
            value: "true"
          - name: SERVICE_PRECONDITION
            value: hdfs-namenode:50070 hdfs-datanode-0.hdfs-datanode:50075 hdfs-datanode-1.hdfs-datanode:50075 hdfs-datanode-2.hdfs-datanode:50075
          - name: YARN_OPTS
            value: -javaagent:/opt/jmx-exporter/jmx_prometheus_javaagent-0.16.1.jar=8080:/opt/jmx-exporter/config.yaml
