plugins {
    id 'groovy'
}

group 'io.kyligence'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    maven { url 'https://repo.jenkins-ci.org/releases/' }
}

dependencies {
    implementation 'org.codehaus.groovy:groovy-all:3.0.5'

    testImplementation "com.lesfurets:jenkins-pipeline-unit:1.9"
    testImplementation 'org.spockframework.spock:spock-core:spock-2.0'
    testImplementation 'org.spockframework.spock:spock-spring:spock-2.0'
}

test {
    useJUnitPlatform()
}