version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    hostname: master
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins_cluster
    ports:
      - 8080:8080
      - 50000:50000

  agent1:
    image: jenkins/ssh-agent
    container_name: agent1
    hostname: agent1
    networks:
      - jenkins_cluster
    ports:
      - 2021:22

  agent2:
    image: jenkins/ssh-agent
    container_name: agent2
    hostname: agent2
    networks:
      - jenkins_cluster
    ports:
      - 2022:22

networks:
  jenkins_cluster:

volumes:
  jenkins_home:
