apiVersion: v1
kind: Service
metadata:
  namespace: <<<namespace>>>
  name: zk-hs
  labels:
    app: zk
spec:
  ports:
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app: zk
---
apiVersion: v1
kind: Service
metadata:
  namespace: <<<namespace>>>
  name: zk-cs
  labels:
    app: zk
    metrics-exporter: prometheus
spec:
  ports:
  - port: 2181
    name: client
  - port: 8080
    name: metrics
  selector:
    app: zk
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  namespace: <<<namespace>>>
  name: zk-pdb
spec:
  selector:
    matchLabels:
      app: zk
  maxUnavailable: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: <<<namespace>>>
  name: zk
spec:
  selector:
    matchLabels:
      app: zk
  serviceName: zk-hs
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: zk
    spec:
#      affinity:
#        podAntiAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            - labelSelector:
#                matchExpressions:
#                  - key: "app"
#                    operator: In
#                    values:
#                    - zk
#              topologyKey: "kubernetes.io/hostname"
      volumes:
      - name: exporter-dir
        emptyDir: {}
      - name: jmx-config
        configMap:
          name: jmx-exporter-config
      initContainers:
      - name: jmx-exporter
        image: 10.1.9.11:31500/jmx-prometheus-javaagent:0.16.1
        volumeMounts:
        - name: exporter-dir
          mountPath: /opt/jmx-exporter/
        command: ["cp", "/opt/jmx_prometheus_javaagent-0.16.1.jar", "/opt/jmx-exporter/"]
      imagePullSecrets:
      - name: docker-registry-secret
      containers:
      - name: kubernetes-zookeeper
        imagePullPolicy: IfNotPresent
        image: "10.1.9.11:31500/kubernetes-zookeeper:1.0-3.4.10"
        env:
        - name: FORMAT_MESSAGES_PATTERN_DISABLE_LOOKUPS
          value: "true"
        - name: JVMFLAGS
          value: -javaagent:/opt/jmx-exporter/jmx_prometheus_javaagent-0.16.1.jar=8080:/opt/jmx-exporter/config.yaml
        resources:
          requests:
            memory: "1Gi"
            cpu: "300m"
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        command:
        - sh
        - -c
        - "start-zookeeper \
          --servers=1 \
          --data_dir=/var/lib/zookeeper/data \
          --data_log_dir=/var/lib/zookeeper/data/log \
          --conf_dir=/opt/zookeeper/conf \
          --client_port=2181 \
          --election_port=3888 \
          --server_port=2888 \
          --tick_time=2000 \
          --init_limit=10 \
          --sync_limit=5 \
          --heap=512M \
          --max_client_cnxns=60 \
          --snap_retain_count=3 \
          --purge_interval=12 \
          --max_session_timeout=40000 \
          --min_session_timeout=4000 \
          --log_level=INFO"
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "zookeeper-ready 2181"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "zookeeper-ready 2181"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/zookeeper
        - name: exporter-dir
          mountPath: /opt/jmx-exporter/
        - name: jmx-config
          mountPath: /opt/jmx-exporter/config.yaml
          subPath: config.yaml
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 1Gi