#!groovy

@Library('devopslib@DEVOPS-1178') _

pipeline {
    options {
        timeout(time: 2, unit: 'HOURS')
        ansiColor('xterm')
    }

    agent {
        label '10.1.1.118-hdp2.4 || 10.1.1.45-hdp2.4'
    }

    parameters {
        string(name: 'repo', defaultValue: 'Kyligence', description: '')
        string(name: 'branch', defaultValue: 'master', description: '')
        string(name: 'WHORU', defaultValue: 'anonymous', description: 'who are you?')
        choice(name: 'FAST_MODE', choices: ['false', 'true'], description: '')
        string(name: 'SPARK_VERSION', defaultValue: 'spark-bin-2.2.1-r26', description: '')
    }

    environment {
        SPARK_ROOT='/usr/local/kyspark'
        SPARK_HOME="${SPARK_ROOT}/${SPARK_VERSION}"
        ZIPKIN_HOSTNAME='localhost'
        ZIPKIN_PORT=9410
        KAP_HDFS_WORKING_DIR='/kylin'
        KAP_METADATA_URL='kylin_default_instance@hbase'
    }

    stages {
        stage('Pull Code') {
            steps {
                script {
                    currentBuild.displayName = "#${BUILD_NUMBER} for ${params.WHORU}"
                }
                dir('kap') {
                    timestamps {
                        script {
                            retry(3) {
                                pullCodeFromGitMirror "KAP", "${params.branch}", false, "${params.repo}"
                            }
                        }
                    }
                }

            }
        }

        stage('Build') {
            steps {
                sh script: """
                    metadata_url=`echo ${WHORU} | sed 's/\\./_/g'`"_kapmaster_ci_instance"
                    echo "metadata url used for this run is \${metadata_url}"
                    cd kap
                    sed -ie "s/kylin_default_instance@hbase/\${metadata_url}@hbase/g" extensions/examples/test_case_data/sandbox/kylin.properties

                    sed '/<configuration>/r /opt/ci_queue_props/hive_queue.prop' -i extensions/examples/test_case_data/sandbox/kylin_hive_conf.xml
                    sed '/<configuration>/r /opt/ci_queue_props/mr_queue.prop' -i extensions/examples/test_case_data/sandbox/kylin_job_conf.xml
                    sed '/<configuration>/r /opt/ci_queue_props/mr_queue.prop' -i extensions/examples/test_case_data/sandbox/kylin_job_conf_inmem.xml
                    sed '\$r /opt/ci_queue_props/spark_queue.prop' -i extensions/examples/test_case_data/sandbox/kylin.properties

                    mkdir -p ${SPARK_ROOT}
                    cp /mnt/jenkins/kyspark/${SPARK_VERSION}.tgz ${SPARK_ROOT}/
                    cd ${SPARK_ROOT}
                    tar zxf ${SPARK_VERSION}.tgz
                    cd -
                    if [ ! -d "\$SPARK_HOME" ]; then
                      echo "SPARK_HOME is set to an invalid folder: ${SPARK_HOME}, please check it on the current node."
                    fi
                """

                sh script: """
                    lsof -i :7070,7071 | grep "(LISTEN)" | awk '{print \$2}' | xargs kill -9 || exit 0
                """

                sh script: """
                    cd ${WORKSPACE}/kap
                    sleep 10
                    ulimit -a
                    ulimit -u 10000
                    ulimit -a

                    MAVEN_OPTS="-Dmaven.repo.local=${WORKSPACE}/.repository" mvn clean install -DskipTests=true
                    MAVEN_OPTS="-Dmaven.repo.local=${WORKSPACE}/.repository" mvn -pl :kap-it failsafe:integration-test -Dhdp.version=2.4.0.0-169 -DfastBuildMode=${FAST_MODE} -P sandbox -Dsparder.enabled=true -DfailsafeArgLine=
                    MAVEN_OPTS="-Dmaven.repo.local=${WORKSPACE}/.repository" mvn -pl :kap-it failsafe:verify -Dhdp.version=2.4.0.0-169 -DfastBuildMode=${FAST_MODE} -P sandbox -Dsparder.enabled=true
                    MAVEN_OPTS="-Dmaven.repo.local=${WORKSPACE}/.repository" mvn -pl :kap-it failsafe:integration-test -Dhdp.version=2.4.0.0-169 -DfastBuildMode=${FAST_MODE} -Dsparder.enabled=false -DfailsafeArgLine=
                    MAVEN_OPTS="-Dmaven.repo.local=${WORKSPACE}/.repository" mvn -pl :kap-it failsafe:verify -Dhdp.version=2.4.0.0-169 -DfastBuildMode=${FAST_MODE} -P sandbox -Dsparder.enabled=false
                """

            }
        }
    }
}
