#!groovy

@Library('devopslib') _

pipeline {
    options {
        timeout(time: 2, unit: 'HOURS')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/aws/sfz-ci/jenkins-agent.yaml'
        }
    }
    triggers {
        pollSCM ('*/1 * * * *')
    }

    parameters {
        string(name: 'repo', defaultValue: 'Kyligence', description: 'Kap repo?')
        string(name: 'branch', defaultValue: 'devopslib', description: 'Kap branch?')
        string(name: 'commitid', defaultValue: 'devopslib', description: 'Kap branch?')
        string(name: 'version', defaultValue: '4.5.9', description: 'Kap version?')
        credentials(name: 'certificate', credentialType: 'com.cloudbees.plugins.credentials.common.StandardCredentials', defaultValue: 'kyligencegit', required: true)
    }

    stages {
        
        stage("Checkout Source Code") {
            steps {
                container("build") {
                    dir("sourcecode") {
                        script {
                             awsGithubCheckOut 'KAP'
                             sh """ 
                                 echo "\n------------------------------------------------"
                                     pwd
                                     ls -al
                                 echo "\n-------------------------------------------------"
                                """
                        }
                    }
                }
            }
        }

        stage('Building Package') {
            steps {
                container("build") {
                    dir("sourcecode") {
                         //buildNewten(params.version)
                         //archiveArtifacts artifacts: 'dist/*.tar.gz', fingerprint: true, followSymlinks: false, onlyIfSuccessful: true
                        //sh " mkdir -p /var/cicd/artifacts/dev/newten &&  \
                        //cp dist/*.tar.gz /var/cicd/artifacts/dev/newten/${version}-`git rev-parse --short HEAD`-${BUILD_NUMBER}-.tar.gz"
                        
                        //--s3 上传方式
                        withAWS(region: 'us-west-2', credentials: 'aws_global_s3_cp') {
                         // Upload reports for analyze
                        
                          sh script: """
                                #!/bin/bash
                                echo -e '\n-------------------'
                                pwd
                                echo -e '\n-------------------'
                                ls -al 
                                echo -e '\n-------------------'
                                mkdir  dist
                                echo -e '\n-------------------'
                                touch dist/KE-${version}-DEV-${BUILD_NUMBER}-`git rev-parse --short HEAD`.tar.gz
                                cp -p dist/*.tar.gz  .
                                echo -e '\n-------------------'
                                ls -al
                                echo -e '\n-------------------'
                                ls -al dist
                                echo -e '\n-------------------'
                             """                       
                           s3Upload(bucket: 'k8s-bucket-devops', path: "ke-cd/dev/newten/", includePathPattern: "*.tar.gz")
                       }
                    }
                }
            }
        }
    }
}
