#kubectl create secret docker-registry docker-registry-secret \
#  --docker-server=repo-ofs.kyligence.tech:5000 \
#  --docker-username=kydocker \
#  --docker-password=Ky123qwe.. \
#  -n kyligence

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hdfs.fullname" . }}-docker-registry-secret
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyIxMC4xLjkuMTE6MzE1MDAiOnsidXNlcm5hbWUiOiJreWRvY2tlciIsInBhc3N3b3JkIjoiS3kxMjNxd2UuLiIsImF1dGgiOiJhM2xrYjJOclpYSTZTM2t4TWpOeGQyVXVMZz09In19fQ==
type: kubernetes.io/dockerconfigjson
