apiVersion: v1
kind: Service
metadata:
  name: {{ include "hdfs.fullname" . }}-hive-metastore
  labels:
    metrics-exporter: prometheus
spec:
  selector:
    app: {{ include "hdfs.fullname" . }}-hive-metastore
  ports:
    - port: {{ .Values.hive_metastore.port }}
      name: thrift
    - port: 8080
      name: metrics

