apiVersion: v1
kind: Service
metadata:
  name: {{ include "hdfs.fullname" . }}-mysql
  labels:
    app: {{ include "hdfs.fullname" . }}-mysql
spec:
  ports:
  - name: mysql
    port: {{ .Values.mysql.port }}
  - name: metrics
    port: {{ .Values.mysql.prometheus.port }}
  selector:
    app: {{ include "hdfs.fullname" . }}-mysql