apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hdfs.fullname" . }}-mysql
  labels:
    app: {{ include "hdfs.fullname" . }}-mysql
data:
  mysql.cnf: |
    [mysqld]
    innodb_buffer_pool_size = 2GB
    innodb_buffer_pool_instances = 1

    innodb_flush_log_at_trx_commit = 1
    sync_binlog = 1
    max_connections = 200
    innodb_log_file_size = 500MB
    innodb_log_files_in_group = 2
    server_id = 1000
    log_bin = BIN-LOG
    binlog_format = ROW
    innodb_io_capacity = 200

    character_set_client_handshake=FALSE
    character_set_server=utf8mb4
    init_connect='SET NAMES utf8mb4'
    init_connect='SET collation_connection = utf8mb4_unicode_ci'
    collation_server=utf8mb4_unicode_ci

    [client]
    default_character_set=utf8mb4

    [mysql]
    default_character_set=utf8mb4
  mysql-init.sql: |
    CREATE DATABASE hive DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
    create user 'hive'@'%' identified by 'hive';
    grant all on hive.* to 'hive'@'%';

    flush privileges;