apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hdfs.fullname" . }}-yarn-xml
data:
  yarn-site.xml: |
    <configuration>
      <property><name>yarn.resourcemanager.fs.state-store.uri</name><value>/rmstate</value></property>
      <property><name>yarn.timeline-service.leveldb-timeline-store.path</name><value>/hadoop/yarn/timeline</value></property>
      <property><name>yarn.timeline-service.generic-application-history.enabled</name><value>true</value></property>
      <property><name>mapreduce.map.output.compress</name><value>true</value></property>
      <property><name>yarn.resourcemanager.recovery.enabled</name><value>true</value></property>
      <property><name>mapred.map.output.compress.codec</name><value>org.apache.hadoop.io.compress.SnappyCodec</value></property>
      <property><name>yarn.log-aggregation-enable</name><value>true</value></property>
      <property><name>yarn.timeline-service.enabled</name><value>true</value></property>
      <property><name>yarn.resourcemanager.store.class</name><value>org.apache.hadoop.yarn.server.resourcemanager.recovery.FileSystemRMStateStore</value></property>
      <property><name>yarn.resourcemanager.system-metrics-publisher.enabled</name><value>true</value></property>
      <property><name>yarn.nodemanager.remote-app-log-dir</name><value>/app-logs</value></property>
      <property><name>yarn.nodemanager.aux-services</name><value>mapreduce_shuffle</value></property>
      <property><name>yarn.resourcemanager.resource_tracker.address</name><value>{{ include "hdfs.fullname" . }}-yarn-resourcemanager:8031</value></property>
      <property><name>yarn.resourcemanager.hostname</name><value>{{ include "hdfs.fullname" . }}-yarn-resourcemanager</value></property>
      <property><name>yarn.timeline-service.hostname</name><value>yarn-historyserver</value></property>
      <property><name>yarn.log.server.url</name><value>http://yarn-historyserver:8188/applicationhistory/logs/</value></property>
      <property><name>yarn.resourcemanager.scheduler.address</name><value>{{ include "hdfs.fullname" . }}-yarn-resourcemanager:8030</value></property>
      <property><name>yarn.resourcemanager.address</name><value>{{ include "hdfs.fullname" . }}-yarn-resourcemanager:8032</value></property>
      <property><name>yarn.nodemanager.disk-health-checker.max-disk-utilization-per-disk-percentage</name><value>98.5</value></property>
      <property><name>yarn.resourcemanager.bind-host</name><value>0.0.0.0</value></property>
      <property><name>yarn.nodemanager.bind-host</name><value>0.0.0.0</value></property>
      <property><name>yarn.nodemanager.bind-host</name><value>0.0.0.0</value></property>
      <property><name>yarn.timeline-service.bind-host</name><value>0.0.0.0</value></property>

      <property>
        <name>yarn.scheduler.maximum-allocation-mb</name>
        <value>8192</value>
      </property>
      <property>
        <name>yarn.scheduler.minimum-allocation-mb</name>
        <value>2048</value>
      </property>
      <property>
        <name>yarn.nodemanager.vmem-pmem-ratio</name>
        <value>2.1</value>
      </property>
      <property>
        <name>yarn.scheduler.minimum-allocation-vcores</name>
        <value>1</value>
      </property>
      <property>
        <name>yarn.scheduler.maximum-allocation-vcores</name>
        <value>4</value>
      </property>
      <property>
        <name>yarn.nodemanager.resource.cpu-vcores</name>
        <value>4</value>
      </property>
      <property>
        <name>yarn.nodemanager.resource.memory-mb</name>
        <value>8192</value>
      </property>
      <property>
        <name>yarn.resourcemanager.scheduler.class</name>
        <value>org.apache.hadoop.yarn.server.resourcemanager.scheduler.fair.FairScheduler</value>
      </property>
      <property>
        <name>yarn.scheduler.fair.allocation.file</name>
        <value>fair-scheduler.xml</value>
      </property>
    </configuration>
  fair-scheduler.xml: |
    <allocations>
      <queue name="root">
        <weight>1.0</weight>
        <maxResources>16384mb,8vcores</maxResources>
        <schedulingPolicy>fair</schedulingPolicy>
        <aclSubmitApps>*</aclSubmitApps>
        <aclAdministerApps>*</aclAdministerApps>
        <queue name="default">
          <weight>1.0</weight>
          <schedulingPolicy>fair</schedulingPolicy>
          <aclSubmitApps>*</aclSubmitApps>
          <aclAdministerApps>*</aclAdministerApps>
        </queue>
      </queue>
      <defaultQueueSchedulingPolicy>fair</defaultQueueSchedulingPolicy>
      <queuePlacementPolicy>
        <rule name="specified" create="false"/>
        <rule name="default" queue="default"/>
      </queuePlacementPolicy>
    </allocations>
  hdfs-site.xml: |
    <configuration>
      <property><name>dfs.namenode.name.dir</name><value>file:///hadoop/dfs/name</value></property>
      <property><name>dfs.namenode.datanode.registration.ip-hostname-check</name><value>false</value></property>
      <property><name>dfs.permissions.enabled</name><value>false</value></property>
      <property><name>dfs.webhdfs.enabled</name><value>true</value></property>
      <property><name>dfs.namenode.rpc-bind-host</name><value>0.0.0.0</value></property>
      <property><name>dfs.namenode.servicerpc-bind-host</name><value>0.0.0.0</value></property>
      <property><name>dfs.namenode.http-bind-host</name><value>0.0.0.0</value></property>
      <property><name>dfs.namenode.https-bind-host</name><value>0.0.0.0</value></property>
      <property><name>dfs.client.use.datanode.hostname</name><value>true</value></property>
      <property><name>dfs.datanode.use.datanode.hostname</name><value>true</value></property>
    </configuration>
  core-site.xml: |
    <configuration>
        <!-- 以下是 HDFS 客户端配置 -->
        <property>
           <name>fs.defaultFS</name>
           <value>hdfs://{{ include "hdfs.fullname" . }}-namenode:8020</value>
        </property>
        <!-- 以下是 通用 客户端配置 -->
        <property>
          <name>io.compression.codecs</name>
          <value>org.apache.hadoop.io.compress.SnappyCodec</value>
        </property>
        <property>
            <name>hadoop.proxyuser.root.hosts</name>
            <value>*</value>
        </property>
        <property>
            <name>hadoop.proxyuser.root.groups</name>
            <value>*</value>
        </property>
    </configuration>
  hive-site.xml: |
    <configuration>

    
       <!-- 以下是hive metastore配置 -->       
       <property>
          <name>javax.jdo.option.ConnectionDriverName</name>
          <value>com.mysql.jdbc.Driver</value>
       </property>
       <property>
          <name>javax.jdo.option.ConnectionURL</name>
          <value>jdbc:mysql://{{ include "hdfs.fullname" . }}-mysql:3306/hive?UseUnicode=true&amp;characterEncoding=utf8&amp;characterSetResults=UTF-8&amp;serverTimezone=UTC&amp;useSSL=false&amp;verifyServerCertificate=false</value>
       </property>
       <property>
          <name>javax.jdo.option.ConnectionUserName</name>
          <value>hive</value>
       </property>
       <property>
          <name>javax.jdo.option.ConnectionPassword</name>
          <value>hive</value>
       </property>
       <property>
          <name>hive.metastore.port</name>
          <value>9083</value>
       </property>


       <!-- 以下是hive server2配置 -->
       <property>
          <name>hive.server2.thrift.min.worker.threads</name>
          <value>5</value>
       </property>
       <property>
          <name>hive.server2.thrift.max.worker.threads</name>
          <value>500</value>
       </property>
       <property>
          <name>hive.server2.thrift.port</name>
          <value>10000</value>
       </property>
       <property>
          <name>hive.server2.webui.port</name>
          <value>10002</value>
       </property>
       <property>
          <name>hive.metastore.uris</name>
          <value>thrift://{{ include "hdfs.fullname" . }}-hive-metastore:{{ .Values.hive_metastore.port }}</value>
       </property>
       <property>
          <name>hive.scratch.dir.permission</name>
          <value>777</value>
       </property>
       <property>
          <name>hive.exec.scratchdir</name>
          <value>/user/hive/scratch</value>
       </property>
       <property>
          <name>hive.metastore.warehouse.dir</name>
          <value>/user/hive/warehouse</value>
       </property>
    </configuration>