apiVersion: v1
kind: Service
metadata:
  name: {{ include "hdfs.fullname" . }}-yarn-nodemanager
  labels:
    metrics-exporter: prometheus
spec:
  clusterIP: None
  ports:
    - name: "8402"
      port: 8402
      targetPort: 8402
    - port: 8080
      name: metrics
  selector:
    io.kompose.service: {{ include "hdfs.fullname" . }}-yarn-nodemanager
