apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hdfs.fullname" . }}-yarn-historyserver-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.historyserver.storageSize }}
  storageClassName: {{ .Values.historyserver.storageClassName }}