apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "hdfs.fullname" . }}-zk
  labels:
    {{- include "hdfs.labels" . | nindent 4 }}
    app: {{ include "hdfs.fullname" . }}-zk
spec:
  selector:
    matchLabels:
      app: {{ include "hdfs.fullname" . }}-zk
  serviceName: {{ include "hdfs.fullname" . }}-zk-hs
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.zookeeper.replicaCount }}
  {{- end }}
  updateStrategy:
    type: {{ .Values.zookeeper.updateStrategy }}
  podManagementPolicy: OrderedReady
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "hdfs.fullname" . }}-zk
    spec:
      {{- if .Values.jmx.enabled }}
      volumes:
      - name: exporter-dir
        emptyDir: {}
      - name: jmx-config
        configMap:
          name: {{ include "hdfs.fullname" . }}-jmx-exporter-config
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.jmx.enabled }}
      initContainers:
        - name: jmx-exporter
          image: "{{ .Values.jmx.image.repository }}:{{ .Values.jmx.image.tag }}"
          volumeMounts:
            - name: exporter-dir
              mountPath: /opt/jmx-exporter/
          command: ["cp", "/opt/jmx_prometheus_javaagent-0.16.1.jar", "/opt/jmx-exporter/"]
      {{- end }}
      imagePullSecrets:
        - name: "{{ include "hdfs.fullname" . }}-{{ .Values.zookeeper.imagePullSecrets }}"
      containers:
      - name: {{ include "hdfs.fullname" . }}-kubernetes-zookeeper
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.zookeeper.image.repository }}:{{ .Values.zookeeper.image.tag }}"
        env:
        - name: FORMAT_MESSAGES_PATTERN_DISABLE_LOOKUPS
          value: "true"
        - name: JVMFLAGS
          value: -javaagent:/opt/jmx-exporter/jmx_prometheus_javaagent-0.16.1.jar=8080:/opt/jmx-exporter/config.yaml
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        command:
        - sh
        - -c
        - "start-zookeeper \
          --servers=1 \
          --data_dir=/var/lib/zookeeper/data \
          --data_log_dir=/var/lib/zookeeper/data/log \
          --conf_dir=/opt/zookeeper/conf \
          --client_port=2181 \
          --election_port=3888 \
          --server_port=2888 \
          --tick_time=2000 \
          --init_limit=10 \
          --sync_limit=5 \
          --heap=512M \
          --max_client_cnxns=60 \
          --snap_retain_count=3 \
          --purge_interval=12 \
          --max_session_timeout=40000 \
          --min_session_timeout=4000 \
          --log_level=INFO"
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "zookeeper-ready 2181"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "zookeeper-ready 2181"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: {{ include "hdfs.fullname" . }}-datadir
          mountPath: /var/lib/zookeeper
        - name: exporter-dir
          mountPath: /opt/jmx-exporter/
        - name: jmx-config
          mountPath: /opt/jmx-exporter/config.yaml
          subPath: config.yaml
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
  volumeClaimTemplates:
  - metadata:
      name: {{ include "hdfs.fullname" . }}-datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.zookeeper.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.zookeeper.storageSize }}