{{- if semverCompare ">=v1.21-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: policy/v1
{{- else -}}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "hdfs.fullname" . }}-zk-pdb
spec:
  selector:
    matchLabels:
      app: {{ include "hdfs.fullname" . }}-zk
  maxUnavailable: 1