#!groovy

@Library('devopslib') _

package_file = ''
namespace = 'test'

pipeline {
    options {
        timeout(time: 1, unit: 'HOURS')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/local/Newten-CD/jenkins-agent.yaml'
        }
    }

    parameters {
        string(name: 'branch', defaultValue: 'newten-qa', description: 'Kap branch?')
        string(name: 'repo', defaultValue: 'Kyligence', description: 'Kap repo?')
        string(name: 'version', defaultValue: '4.5.8.1', description: 'Kap version?')
        credentials(name: 'certificate', credentialType: 'com.cloudbees.plugins.credentials.common.StandardCredentials', defaultValue: 'kyligence-git', required: true)
    }

    stages {
        stage("Checkout Source Code") {
            steps {
                container("build") {
                    dir("sourcecode") {
                        script {
                            retry(3) {
                                sshCmdWithCredentials(
                                    'bash -c /var/lib/git/pull.sh',
                                    'private_git',
                                    ['name':'localhost','host':'10.1.2.192', 'allowAnyHosts': true]
                                )
                                githubCheckout 'KAP'
                            }

                            echo 'checkout KAP_Frontend to kystudio'
                            sh 'rm -rf ./kystudio'
                            dir('kystudio') {
                                retry(3) {
                                    githubCheckout 'KAP_Frontend', "${branch ?: params.branch ?: 'newten-qa'}", 'https', 'github.com', '+refs/heads/*:refs/remotes/origin/*'
                                }
                            }
                        }
                    }
                }
            }
        }
        stage('Building Package') {
            steps {
                container("build") {
                    dir("sourcecode") {
                        buildNewten(params.version, false, false)
                        archiveArtifacts artifacts: 'dist/*.tar.gz', fingerprint: true, followSymlinks: false, onlyIfSuccessful: true
                        script {
                            def commitid = sh(returnStdout:true, script: "git rev-parse --short HEAD").trim()
                            print commitid
                            sh "mkdir -p /var/cicd/artifacts/rc/Newten-CD && \
                            cp dist/*.tar.gz /var/cicd/artifacts/rc/Newten-CD/KE-${version}-RC-${BUILD_NUMBER}-${commitid}.tar.gz"
                        }
                    }
                }
            }
        }
        stage("Generate ENV") {
            steps {
                container("kubectl") {

                    withCredentials([file(credentialsId: 'kubeconfig', variable: 'KUBECONFIG')]) {
                        echo "查看 K8S 集群 Pod 列表"
                        sh "mkdir -p ~/.kube && cp ${KUBECONFIG} ~/.kube/config"
                    
                    // retry(3) {
                        script {
                            result = sh (
                                returnStatus: true,
                                script: """#!/bin/sh
                                    set +x
                                    cd ${WORKSPACE}/k8s/auto-generate/
                                    sh install.sh --package_file=${package_file ?: params.package_file ?: ''} --namespace=${namespace ?: params.namespace ?: namespace}
                                """
                            ).trim()
                            if(result == 0){
                                print 'SUCCESS'
                                currentBuild.result = 'SUCCESS'
                            }else{
                                print 'FAILED'
                                currentBuild.result = 'FAILED'
                            }
                        }
                    // }
                    }
                }
            }
        }
    }
}
