#!groovy

@Library('devopslib') _

// 上传制品包到Aws S3存储
def uploadAwsS3(region, credentials, bucket, path, ga_name) {
    timestamps {
        println("uploadAwsS3 -> path: ${path}, ga_name: ${ga_name}")
        withAWS(region: region, credentials: credentials) {
            s3Upload(bucket: bucket, path: path, file: ga_name)
        }
    }
}

pipeline {
    options {
        timeout(time: 2, unit: 'HOURS')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/yaml/jenkins-package-agent.yaml'
        }
    }

    parameters {
        string(name: 'repo', defaultValue: 'git://10.1.2.192/Kyligence/spark.git', description: 'spark repo')
        string(name: 'branch', defaultValue: 'kyspark-3.2.x-4.x', description: 'spark branch')
        string(name: 'release_version', defaultValue: '', description: 'spark release version for example: 3.2.0-kylin-4.x-r52')
    }

    stages {
        stage("Checkout Source Code") {
            steps {
                container("build") {
                    dir("sourcecode") {
                        retry(3) {
                            timestamps {
                                checkout([$class         : 'GitSCM',
                                        branches         : [[name: "${params.branch}"]],
                                        userRemoteConfigs: [[credentialsId: "kyligence-git",
                                                            name         : "origin",
                                                            refspec      : "+refs/pull/*:refs/remotes/origin/pr/* +refs/heads/*:refs/remotes/origin/*",
                                                            url          : "${repo}"]],
                                        browser          : [$class: 'GithubWeb', repoUrl: "https://github.com/Kyligence/spark"],
                                        extensions       : [
                                                [$class: 'CleanBeforeCheckout'],
                                                [$class: 'CloneOption', depth: 0, noTags: false, shallow: false, timeout: 60]
                                        ]
                                ])
                            }
                        }
                    }
                    sh script: """
                        wget http://repo-ofs.kyligence.tech:8081/repository/raw-public/io.kyligence.spark/depedencies.tar.gz
                        tar zxf depedencies.tar.gz
                        wget  https://s3.cn-north-1.amazonaws.com.cn/download-resource/kyspark/hive_1_2_2.tar.gz
                        tar zxf hive_1_2_2.tar.gz
                    """
                }
            }
        }
        stage('Deploy') {
            steps {
                container('build') {
                    dir('sourcecode') {
                        script {
                            sh script: """
                                #1、package kyspark
                                ./build/mvn versions:set -DnewVersion=${params.release_version}

                                export MAVEN_OPTS="-Xmx4g -XX:ReservedCodeCacheSize=1g -Xss512m"
                                ./build/mvn deploy -settings /root/.m2/settings.xml -Ppro -Phadoop-provided -Phive-provided -Phive-thriftserver -Pyarn -Pkubernetes -DskipTests=true
                                # ./build/mvn install -Phadoop-provided -Phive-provided -Phive-thriftserver -Pyarn -Pkubernetes -DskipTests=true
                            """
                        }
                    }
                    sh script: """
                        cp -r sourcecode ./on-perm-hadoop2
                        cp -r sourcecode ./on-perm-nohadoop
                        cp -r sourcecode ./cloud-hadoop3
                        cp -r sourcecode ./cloud-gcp
                        cp -r sourcecode ./cloud-huawei
                    """
                }
            }
        }
        stage('Package') {
            parallel {
                stage('on-perm-hadoop2') {
                    steps {
                        container("build") {
                            dir('on-perm-hadoop2') {
                                script {
                                    def releaseName = params.release_version.replace("-kylin", "")
                                    sh script: """
                                        export MAVEN_OPTS="-Xmx4g -XX:ReservedCodeCacheSize=1g -Xss512m"
                                        dev/make-distribution.sh --name ${params.release_version} -Phadoop-2.7 -Phive -Phive-thriftserver -Pyarn -Pkubernetes
                                        cp ../depedencies/log4j/*.jar dist/jars/
                                        mv dist spark-newten-${releaseName}-hadoop2
                                        tar czf spark-newten-${releaseName}-hadoop2.tgz spark-newten-${releaseName}-hadoop2
                                        md5sum spark-newten-${releaseName}-hadoop2.tgz
                                    """
                                    withCredentials([usernamePassword(credentialsId: 'nexus-raw', passwordVariable: 'passwd', usernameVariable: 'user')]) {
                                        pushRawArtifactsByApi('raw-tars-hosted', 'io.kyligence.spark', "spark-newten-${releaseName}-hadoop2.tgz", "spark-newten-${releaseName}-hadoop2.tgz", user, passwd)
                                    }
                                    uploadAwsS3('cn-north-1', 'aws_cn_s3_cp', 'download-resource', "kyspark/spark-newten-${releaseName}.tgz", "spark-newten-${releaseName}-hadoop2.tgz")
                                }
                            }
                        }
                    }
                }
                stage('on-perm-nohadoop') {
                    steps {
                        container("build") {
                            dir("on-perm-nohadoop") {
                                script {
                                    def releaseName = params.release_version.replace("-kylin", "")
                                    sh script: """
                                        sleep 10
                                        export MAVEN_OPTS="-Xmx4g -XX:ReservedCodeCacheSize=1g -Xss512m"
                                        dev/make-distribution.sh --name ${params.release_version} -Phadoop-provided -Phive-provided -Phive-thriftserver -Pyarn -Pkubernetes -pl assembly
                                        cp ../depedencies/log4j/*.jar dist/jars/
                                        mv dist spark-newten-${releaseName}
                                        tar czf spark-newten-${releaseName}.tgz spark-newten-${releaseName}
                                    """
                                    withCredentials([usernamePassword(credentialsId: 'nexus-raw', passwordVariable: 'passwd', usernameVariable: 'user')]) {
                                        pushRawArtifactsByApi('raw-tars-hosted', 'io.kyligence.spark', "spark-newten-${releaseName}.tgz", "spark-newten-${releaseName}.tgz", user, passwd)
                                    }
                                    uploadAwsS3('us-west-2', 'aws_global_s3_cp', 'kyligencecloud-ci', "packages/spark-cloud/spark-newten-${releaseName}.tgz", "spark-newten-${releaseName}.tgz")

                                }
                            }
                        }
                    }
                }
                stage('cloud-hadoop3') {
                    steps {
                        container("build") {
                            dir("cloud-hadoop3") {
                                script {
                                    def releaseName = params.release_version.replace("-kylin", "")
                                    sh script: """
                                        sleep 20
                                        export MAVEN_OPTS="-Xmx4g -XX:ReservedCodeCacheSize=1g -Xss512m"
                                        dev/make-distribution.sh --name ${params.release_version} -Phadoop-3.2 -Phive-thriftserver -pl assembly
                                        cp ../depedencies/log4j/*.jar dist/jars/
                                        cp ../depedencies/cloud_log4j/*.jar dist/jars/
                                        rm  dist/jars/log4j-1.2-api-*.jar
                                        cp ../depedencies/hadoop3/* dist/jars/
                                        cp -r ../hive_1_2_2  dist/
                                        cp ../depedencies/log4j/spark-executor-log4j.xml dist/conf/spark-executor-log4j.xml
                                        mv dist spark-newten-${releaseName}-cloud-hadoop3
                                        tar czf spark-newten-${releaseName}-cloud-hadoop3.tgz spark-newten-${releaseName}-cloud-hadoop3
                                    """
                                    withCredentials([usernamePassword(credentialsId: 'nexus-raw', passwordVariable: 'passwd', usernameVariable: 'user')]) {
                                        pushRawArtifactsByApi('raw-tars-hosted', 'io.kyligence.spark', "spark-newten-${releaseName}-cloud-hadoop3.tgz", "spark-newten-${releaseName}-cloud-hadoop3.tgz", user, passwd)
                                    }
                                    uploadAwsS3('us-west-2', 'aws_global_s3_cp', 'kyligencecloud-ci', "packages/spark-cloud/spark-newten-${releaseName}-cloud-hadoop3.tgz", "spark-newten-${releaseName}-cloud-hadoop3.tgz")

                                }
                            }
                        }
                    }
                }
                stage('cloud-gcp') {
                    steps {
                        container("build") {
                            dir("cloud-gcp") {
                                script {
                                    def releaseName = params.release_version.replace("-kylin", "")
                                    sh script: """
                                        sleep 30
                                        export MAVEN_OPTS="-Xmx4g -XX:ReservedCodeCacheSize=1g -Xss512m"
                                        dev/make-distribution.sh --name ${params.release_version} -Phadoop-3.2 -Phive-thriftserver -pl assembly
                                        cp ../depedencies/log4j/*.jar dist/jars/
                                        cp ../depedencies/cloud_log4j/*.jar dist/jars/
                                        rm  dist/jars/log4j-1.2-api-*.jar
                                        cp ../depedencies/gcp/* dist/jars/
                                        cp -r ../hive_1_2_2  dist/
                                        cp ../depedencies/log4j/spark-executor-log4j.xml dist/conf/spark-executor-log4j.xml
                                        mv dist spark-newten-${releaseName}-cloud-gcp
                                        tar czf spark-newten-${releaseName}-cloud-gcp.tgz spark-newten-${releaseName}-cloud-gcp
                                    """
                                    withCredentials([usernamePassword(credentialsId: 'nexus-raw', passwordVariable: 'passwd', usernameVariable: 'user')]) {
                                        pushRawArtifactsByApi('raw-tars-hosted', 'io.kyligence.spark', "spark-newten-${releaseName}-cloud-gcp.tgz", "spark-newten-${releaseName}-cloud-gcp.tgz", user, passwd)
                                    }
                                    uploadAwsS3('us-west-2', 'aws_global_s3_cp', 'kyligencecloud-ci', "packages/spark-cloud/spark-newten-${releaseName}-cloud-gcp.tgz", "spark-newten-${releaseName}-cloud-gcp.tgz")
                                }
                            }
                        }
                    }
                }
                stage('cloud-huawei') {
                    steps {
                        container("build") {
                            dir("cloud-huawei") {
                                script {
                                    def releaseName = params.release_version.replace("-kylin", "")
                                    sh script: """
                                        sleep 40
                                        export MAVEN_OPTS="-Xmx4g -XX:ReservedCodeCacheSize=1g -Xss512m"
                                        dev/make-distribution.sh --name ${params.release_version} -Phadoop-3.2 -Phive-thriftserver -pl assembly
                                        cp ../depedencies/log4j/*.jar dist/jars/
                                        cp ../depedencies/cloud_log4j/*.jar dist/jars/
                                        rm  dist/jars/log4j-1.2-api-*.jar
                                        cp -r ../hive_1_2_2  dist/
                                        cp ../depedencies/huawei/* dist/jars/
                                        cp ../depedencies/log4j/spark-executor-log4j.xml dist/conf/spark-executor-log4j.xml
                                        mv dist spark-newten-${releaseName}-cloud-huawei
                                        tar czf spark-newten-${releaseName}-cloud-huawei.tgz spark-newten-${releaseName}-cloud-huawei
                                    """
                                    withCredentials([usernamePassword(credentialsId: 'nexus-raw', passwordVariable: 'passwd', usernameVariable: 'user')]) {
                                        pushRawArtifactsByApi('raw-tars-hosted', 'io.kyligence.spark', "spark-newten-${releaseName}-cloud-huawei.tgz", "spark-newten-${releaseName}-cloud-huawei.tgz", user, passwd)
                                    }
                                    uploadAwsS3('us-west-2', 'aws_global_s3_cp', 'kyligencecloud-ci', "packages/spark-cloud/spark-newten-${releaseName}-cloud-huawei.tgz", "spark-newten-${releaseName}-cloud-huawei.tgz")
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}