#!groovy

@Library('devopslib@devops-0307') _

pipeline {
    options {
        timeout(time: 2, unit: 'HOURS')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/yaml/jenkins-package-agent-large.yaml'
        }
    }

    parameters {
        string(name: 'repo', defaultValue: 'git://10.1.2.192/Kyligence/spark.git', description: 'spark repo')
        string(name: 'branch', defaultValue: 'kyspark-3.2.x-4.x', description: 'spark branch')
        string(name: 'release_version', defaultValue: '', description: 'spark release version for example: 3.2.0-kylin-4.x-r52')
        booleanParam(name: 'with_hive1', defaultValue: true, description: 'package support hive_1_2_2')
    }

    stages {
        stage("Checkout Source Code") {
            steps {
                container("build") {
                    dir("sourcecode") {
                        retry(3) {
                            timestamps {
                                checkout([$class         : 'GitSCM',
                                        branches         : [[name: "${params.branch}"]],
                                        userRemoteConfigs: [[credentialsId: "kyligence-git",
                                                            name         : "origin",
                                                            refspec      : "+refs/pull/*:refs/remotes/origin/pr/* +refs/heads/*:refs/remotes/origin/*",
                                                            url          : "${repo}"]],
                                        browser          : [$class: 'GithubWeb', repoUrl: "https://github.com/Kyligence/spark"],
                                        extensions       : [
                                                [$class: 'CleanBeforeCheckout'],
                                                [$class: 'CloneOption', depth: 0, noTags: false, shallow: false, timeout: 60]
                                        ]
                                ])
                            }
                        }
                    }
                    sh script: """
                        cp -r sourcecode ./on-perm
                        cp -r sourcecode ./cloud
                    """
                }
            }
        }
        stage('Package on-perm') {
            steps {
                container("build") {
                    dir("on-perm") {
                        script {
                            def releaseName = params.release_version.replace("-kylin", "") 
                            sh script: """
                                #1、package kyspark
                                ./build/mvn versions:set -DnewVersion=${params.release_version}
                                dev/make-distribution.sh --name ${params.release_version} --tgz -Phadoop-2.7 -Phive -Phive-thriftserver -Pmesos -Pyarn -Pkubernetes

                                #2、rename and repackage
                                tar xf spark-${params.release_version}-bin-*
                                mv spark-${params.release_version}-bin-${params.release_version} spark-newten-${releaseName}
                            """
                            if (params.with_hive1) {
                                sh script: """
                                    #3 download hive_1_2_2
                                    wget -q https://s3.cn-north-1.amazonaws.com.cn/download-resource/kyspark/hive_1_2_2.tar.gz
                                    tar xf hive_1_2_2.tar.gz --directory ./spark-newten-${releaseName}
                                    ls -al ./spark-newten-${releaseName}
                                    rm ./hive_1_2_2.tar.gz
                                    tar czf spark-newten-${releaseName}.tgz spark-newten-${releaseName}
                                """
                            }
                            // sh script: """
                            //    ./build/mvn deploy -settings /root/.m2/settings.xml -Ppro -Phadoop-2.7 -Phive -Phive-thriftserver -Pmesos -Pyarn -Pkubernetes -DskipTests=true
                            // """
                            withAWS(region: 'cn-north-1', credentials: 'aws_global_s3_cp') {
                                s3Upload(bucket: 'download-resource', path: "kyspark/", includePathPattern: "spark-newten-${releaseName}.tgz")
                            }
                        }
                    }
                }
            }
        }
        stage('Package cloud') {
            steps {
                container("build") {
                    dir("cloud") {
                        script {
                            def releaseName = sh "echo \"${params.release_version}-hadoop3\" | sed \"s/-kylin//g\""
                            sh script: """
                                #1、package kyspark
                                ./build/mvn versions:set -DnewVersion=${params.release_version}
                                dev/make-distribution.sh --name ${params.release_version} --tgz -Phadoop-3.2 -Phive-thriftserver -Padl-support
                                mv spark-${params.release_version}-bin-${params.release_version}.tgz spark-newten-${releaseName}.tgz
                            """
                            withAWS(region: 'cn-north-1', credentials: 'aws_global_s3_cp') {
                                s3Upload(bucket: 'download-resource', path: "kyspark/", includePathPattern: "spark-newten-${releaseName}.tgz")
                            }
                        }
                    }
                }
            }
        }
    }
}
