#!groovy

@Library('devopslib') _

pipeline {
    options {
        timeout(time: 3, unit: 'HOURS')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/yaml/jenkins-agent-opencicd-kylin-ci.yaml'
        }
    }

    parameters {
        string(name: 'branch', defaultValue: '', description: 'Kylin branch?')
        string(name: 'args', defaultValue: '', description: 'Extra JVM options for maven test')
    }

    stages {
        stage("Checkout Source Code") {
            steps {
                container("git") {
                    dir("sourcecode") {
                        script {
                            sh "env"
                            githubCheckout 'kylin-test', params.branch, 'https', 'github.com', '+refs/pull/*:refs/remotes/origin/pr/* +refs/heads/*:refs/remotes/origin/*', 'Mukvin', 'FutureComingSoon'
                            sh 'ls -lha'
                        }
                    }
                }
            }
        }
        stage('Maven Install') {
            steps {
                container("maven") {
                    dir("sourcecode") {
                        script {
                            retry(3) {
                                sh script: "mvn -U clean install -T 2C -Dmaven.compile.fork=true -DskipTests"
                            }
                        }
                    }
                }
            }
        }
        stage('Testing') {
            steps {
                script {
                    dynamicKylinParallelTest()
                }
            }
            post {
                always {
                    timestamps {
                        junit skipPublishingChecks: true, testResults: '*Test-Stage-*/**/target/surefire-reports/*.xml'
                    }
                    // s3Archive4YingLong('upload-without-build_result')
                }
            }
        }
        // stage('SonarCloud') {
        //     steps {
        //         sonarAnalyze("""-Dsonar.pullrequest.base=${ghprbTargetBranch} \
        //                         -Dsonar.pullrequest.branch=${ghprbSourceBranch} \
        //                         -Dsonar.pullrequest.key=${ghprbPullId} \
        //                         -Dsonar.projectKey=Kyligence_kylin2 """)
        //     }
        // }
    }
}
