apiVersion: batch/v1
kind: Job
metadata:
  name: hive-initschema-job
  namespace: <<<namespace>>>
spec:
  backoffLimit: 0
  template:
    spec:
      imagePullSecrets:
      - name: docker-registry-secret
      volumes:
        - name: config
          configMap:
            name: yarn-xml
      containers:
        - name: hive-initschema-job
          volumeMounts:
          - name: config
            mountPath: /opt/apache-hive-1.2.2-bin/conf/hive-site.xml
            subPath: hive-site.xml
          image: 10.1.9.11:31500/hive:1.2.2-hadoop-2.10.1
          imagePullPolicy: IfNotPresent
          env:
          - name: FORMAT_MESSAGES_PATTERN_DISABLE_LOOKUPS
            value: "true"
          command: ["/opt/apache-hive-1.2.2-bin/bin/schematool"]
          args: ["-verbose" ,"-initSchema" , "-dbType", "mysql"]
      restartPolicy: Never