#!groovy

@Library('devopslib') _

packageFilename = ''
namespace = 'cicd'

pipeline {
    options {
        timeout(time: 1, unit: 'HOURS')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/yaml/jenkins-package-agent.yaml'
        }
    }

    parameters {
        string(name: 'remote_dir', defaultValue: '/data/dev/sdc/data/4.5test', description: 'gw07 KE work dir')
        string(name: 'kepackage_dir', defaultValue: '/home/4xuser/data/devops', description: 'gw07 KE4.5 stroage dir')
        string(name: 'ke_workdir',defaultValue:'Kyligence-Enterprise-newten-current',description: 'ke work dir')
        string(name: 'package_name', defaultValue: '', description: 'KE defualt version')
        credentials(name: 'certificate', credentialType: 'com.cloudbees.plugins.credentials.common.StandardCredentials', defaultValue: 'kyligence-git', required: true)
    }

    stages {  
        stage('Auto Deploy KE on Azure gw07') {
            steps {
                container('build') {
                    script {
                        def remote = [:]
                        remote.name = 'azure_env-gw07'
                        withCredentials([usernamePassword(credentialsId: 'azure-4xuser',
                                usernameVariable: 'REMOTE_USERNAME',
                                passwordVariable: 'REMOTE_PASSWORD')]) {
                            remote.user = REMOTE_USERNAME
                            remote.password = REMOTE_PASSWORD
                        }
                        remote.host = '159.27.120.141'
                        remote.allowAnyHosts = true         
                        sshCommand remote: remote, command: """
                            cd ${remote_dir}
                            rm -rf ke_package/*.tar.gz
                            cp ${kepackage_dir}/${package_name} ke_package/
                            if test -d new_kedir
                            then
                                rm -rf new_kedir
                                mkdir new_kedir
                                tar -xf ke_package/${package_name} -C new_kedir/
                            else
                                mkdir new_kedir
                                tar -xf ke_package/${package_name} -C new_kedir/
                            fi
                            if test -d ${ke_workdir}
                            then
                                bash ${ke_workdir}/bin/kylin.sh stop
                            else
                                echo "The KE server is not running"
                            fi
                            tmp_ke_dir=`ls new_kedir`
                            bash new_kedir/\${tmp_ke_dir}/bin/upgrade.sh ${ke_workdir} --silent
                            touch ${ke_workdir}/bin/check-env-bypass
                            echo "skip check env"
                            bash ${ke_workdir}/bin/kylin.sh start
                            cat ${ke_workdir}/commit_SHA1
                            echo "upgrade gw07-ke-env finished"
                            """                                          
                    }
                }
            }
        }
        stage('Auto Deploy KE on Azure gw09') {
            steps {
                container('build') {
                    script {
                        def remote = [:]
                        remote.name = 'azure_env_gw09'
                        withCredentials([usernamePassword(credentialsId: 'azure-4xuser',
                                usernameVariable: 'REMOTE_USERNAME',
                                passwordVariable: 'REMOTE_PASSWORD')]) {
                            remote.user = REMOTE_USERNAME
                            remote.password = REMOTE_PASSWORD
                        }
                        remote.host = '159.27.120.138'
                        remote.allowAnyHosts = true         
                        sshCommand remote: remote, command: """
                            cd ${remote_dir}
                            rm -rf ke_package/*.tar.gz
                            scp 4xuser@10.0.0.28:${kepackage_dir}/${package_name} ke_package/
                            if test -d new_kedir
                            then
                                rm -rf new_kedir
                                mkdir new_kedir
                                tar -xf ke_package/${package_name} -C new_kedir/
                            else
                                mkdir new_kedir
                                tar -xf ke_package/${package_name} -C new_kedir/
                            fi
                                                        if test -d ${ke_workdir}
                            then
                                bash ${ke_workdir}/bin/kylin.sh stop
                            else
                                echo "The KE server is not running"
                            fi
                            tmp_ke_dir=`ls new_kedir`
                            bash new_kedir/\${tmp_ke_dir}/bin/upgrade.sh ${ke_workdir} --silent
                            touch ${ke_workdir}/bin/check-env-bypass
                            echo "skip check env"
                            bash ${ke_workdir}/bin/kylin.sh start
                            cat ${ke_workdir}/commit_SHA1
                            echo "upgrade gw09-138-ke-env finished"
                            """                                          
                    }
                }
            }
        }
    }
}
