#!groovy

@Library('devopslib') _

pipeline {
    options {
        timeout(time: 2, unit: 'HOURS')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/yaml/jenkins-docker-package-agent.yaml'
        }
    }

    environment {
        repo = 'harbor-ofs.kyligence.com'
        dockerRegistryUrl = "http://${repo}"
        registryCredential = 'harbor-docker'
        client = ''
        server = ''
    }

    parameters {
        string(name: 'GIT_BRANCH', defaultValue: 'main', description: 'kyligence server starter parent repo branch')
        string(name: 'CLIENT_DOCKER_TAG', defaultValue: '0.0.1', description: 'client版本号')
        string(name: 'SERVER_DOCKER_TAG', defaultValue: '0.0.1', description: 'server版本号')
        booleanParam(name: 'DEPLOY', defaultValue:true, description:'部署到服务器')
    }

    stages {
        stage('1.Pull Code') {
            steps {
                container('build') {
                    dir('sourcecode') {
                        script {
                            if (!params.GIT_BRANCH) {
                                error 'GIT_BRANCH 参数不能为空'
                            }

                            echo 'checkout kyligence server starter parent'
                            retry(3) {
                                githubCheckout 'chameleon', params.GIT_BRANCH, 'https', 'github.com', '+refs/pull/*:refs/remotes/origin/pr/* +refs/heads/*:refs/remotes/origin/*', 'kyligence-git', 'Kyligence'
                            }
                        }
                    }
                }
            }
        }
        stage('2.Build Client') {
            steps {
                container('build') {
                    dir('sourcecode/packages/client') {
                        script {
                            sh("cp conf/env-qa .env")

                            sh('npm i -g yarn && yarn && yarn build --network-timeout 600000')
                        }
                    }
                }
            }
        }
        stage('3.Build Client Docker Image') {
            steps {
                container('docker') {
                    dir('sourcecode/packages/client') {
                        script {
                            sh("cp conf/nginx-qa default.conf.template")

                            client = docker.build('frontend/chameleon-client', "-f ${env.WORKSPACE}/pipelines/local/FE/Chameleon-CD/docker/Dockerfile-FE .")
                        }
                    }
                }
            }
        }
        stage('4.Build Server') {
            steps {
                container('build') {
                    dir('sourcecode/packages/server') {
                        script {
                            sh("cp conf/env-qa .env")

                            sh('npm i -g yarn && yarn && yarn build && yarn install --prod')
                        }
                    }
                }
            }
        }
        stage('5.Build Server Docker Image') {
            steps {
                container('docker') {
                    dir('sourcecode/packages/server') {
                        script {
                            server = docker.build('frontend/chameleon-server', "-f ${env.WORKSPACE}/pipelines/local/FE/Chameleon-CD/docker/Dockerfile-BE .")
                        }
                    }
                }
            }
        }

        stage('6.Push Docker Image') {
            steps {
                container('docker') {
                    script {
                        docker.withRegistry(dockerRegistryUrl, registryCredential) {
                            client.push("$CLIENT_DOCKER_TAG")
                            client.push('latest')
                            server.push("$SERVER_DOCKER_TAG")
                            server.push('latest')
                        }
                    }
                }
            }
        }
        stage('7.Deploy Docker Image') {
            steps {
                container('build') {
                    script {
                        if (params.DEPLOY) {
                            sshCmdWithCredentials(
                                '''
                                    docker pull harbor-ofs.kyligence.com/frontend/chameleon-client:latest
                                    docker stop chameleon-client
                                    docker rm -f chameleon-client
                                    docker run -d -p 22080:80 --restart=always --name chameleon-client harbor-ofs.kyligence.com/frontend/chameleon-client:latest

                                    docker pull harbor-ofs.kyligence.com/frontend/chameleon-server:latest
                                    docker stop chameleon-server
                                    docker rm -f chameleon-server
                                    docker run -d -p 22090:3000 --restart=always --name chameleon-server harbor-ofs.kyligence.com/frontend/chameleon-server:latest
                                ''',
                                'fe',
                                ['name':'FrontendServer', 'host':'10.1.2.111', 'allowAnyHosts': true]
                            )
                        }
                    }
                }
            }
        }
    }
}
