# beeline -u "jdbc:hive2://hive-server2:10000" -n hive -p hive

apiVersion: v1
kind: Service
metadata:
  namespace: <<<namespace>>>
  name: hive-server2
  labels:
    metrics-exporter: prometheus
spec:
  selector:
    app: hive-server2
  ports:
    - port: 10000
      name: jdbc
    - port: 8080
      name: metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-server2
  namespace: <<<namespace>>>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-server2
  template:
    metadata:
      labels:
        app: hive-server2
    spec:
      imagePullSecrets:
      - name: docker-registry-secret
      initContainers:
      - name: jmx-exporter
        image: repo-ofs.kyligence.com/jmx-prometheus-javaagent:0.16.1
        volumeMounts:
        - name: exporter-dir
          mountPath: /opt/jmx-exporter/
        command: ["cp", "/opt/jmx_prometheus_javaagent-0.16.1.jar", "/opt/jmx-exporter/"]
      containers:
      - name: hive-server2
        image: repo-ofs.kyligence.com/hive:1.2.2-hadoop-2.10.1
        ports:
        - containerPort: 10000
          name: jdbc
        volumeMounts:
        - name: config
          mountPath: /opt/apache-hive-1.2.2-bin/conf/hive-site.xml
          subPath: hive-site.xml
        - name: config
          mountPath: /opt/hadoop-2.10.1/etc/hadoop/core-site.xml
          subPath: core-site.xml
        - name: exporter-dir
          mountPath: /opt/jmx-exporter/
        - name: jmx-config
          mountPath: /opt/jmx-exporter/config.yaml
          subPath: config.yaml
        command: ["/opt/apache-hive-1.2.2-bin/bin/hive"]
        args: ["--service", "hiveserver2"]
        env:
        - name: HADOOP_HEAPSIZE
          value: "1024"
        - name: FORMAT_MESSAGES_PATTERN_DISABLE_LOOKUPS
          value: "true"
        - name: HADOOP_OPTS
          value: -javaagent:/opt/jmx-exporter/jmx_prometheus_javaagent-0.16.1.jar=8080:/opt/jmx-exporter/config.yaml
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 20
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          tcpSocket:
            port: jdbc
        readinessProbe:
          failureThreshold: 20
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          tcpSocket:
            port: jdbc
      volumes:
        - name: config
          configMap:
            name: yarn-xml
        - name: exporter-dir
          emptyDir: {}
        - name: jmx-config
          configMap:
            name: jmx-exporter-config