apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iam.fullname" . }}-secret
  labels:
    {{- include "iam.labels" . | nindent 4 }}
type: Opaque
data:
  MYSQL_DATABASE_USERNAME: cm9vdA==
  MYSQL_DATABASE_PASSWORD: a3lsaWdlbmNl
