kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "yl-query.fullname" . }}-conf
data:
  fairscheduler.xml: |
    <?xml version="1.0"?>
    <allocations>
        <pool name="query_pushdown">
            <schedulingMode>FAIR</schedulingMode>
            <weight>1</weight>
            <minShare>1</minShare>
        </pool>
        <pool name="extreme_heavy_tasks">
            <schedulingMode>FAIR</schedulingMode>
            <weight>3</weight>
            <minShare>1</minShare>
        </pool>
        <pool name="heavy_tasks">
            <schedulingMode>FAIR</schedulingMode>
            <weight>5</weight>
            <minShare>1</minShare>
        </pool>
        <pool name="lightweight_tasks">
            <schedulingMode>FAIR</schedulingMode>
            <weight>10</weight>
            <minShare>1</minShare>
        </pool>
        <pool name="vip_tasks">
            <schedulingMode>FAIR
            </schedulingMode>
            <weight>15</weight>
            <minShare>1</minShare>
        </pool>
    </allocations>
  check-env-bypass: ''
  log4j2.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration name="Log4j1">
        <Appenders>
            <Console name="server" target="SYSTEM_OUT">
                <JsonTemplateLayout eventTemplateUri="classpath:EcsLayout.json">
           			<EventTemplateAdditionalField key="category" value="kylin_log"/>
          		</JsonTemplateLayout>
            </Console>
            <Routing name="routing">
                <Routes pattern="$${ctx:logCategory}">
                    <Route>
                        <Console name="rolling-${ctx:logCategory}" target="SYSTEM_OUT">
                            <JsonTemplateLayout eventTemplateUri="classpath:EcsLayout.json">
           						<EventTemplateAdditionalField key="category" value="kylin_${ctx:logCategory}"/>
          					</JsonTemplateLayout>
                        </Console>
                    </Route>
                    <Route ref="server" key="$${ctx:logCategory}"/>
                </Routes>
            </Routing>
            <Console name="query-log-spark" target="SYSTEM_OUT">
                <JsonTemplateLayout eventTemplateUri="classpath:EcsLayout.json">
           			<EventTemplateAdditionalField key="category" value="kylin_query"/>
          		</JsonTemplateLayout>
            </Console>
        </Appenders>
        <Loggers>
            <Root level="INFO">
                <AppenderRef ref="routing"/>
            </Root>
            <Logger name="org.apache.spark.scheduler.TaskSetManager" level="INFO" additivity="false">
                <AppenderRef ref="query-log-spark"/>
            </Logger>
            <Logger name="org.apache.spark.scheduler.DAGScheduler" level="INFO" additivity="false">
                <AppenderRef ref="query-log-spark"/>
            </Logger>
            <Logger name="org.apache.spark.scheduler.YarnScheduler" level="INFO" additivity="false">
                <AppenderRef ref="query-log-spark"/>
            </Logger>
            <Logger name="io.kyligence" level="DEBUG"/>
            <Logger name="org.springframework" level="WARN"/>
            <Logger name="org.apache.kylin" level="DEBUG"/>
            <Logger name="org.apache.spark.ui" level="WARN"/>
            <Logger name="org.apache.spark.sql.execution.ui" level="WARN"/>
            <Logger name="org.springframework.security" level="INFO"/>
            <Logger name="org.apache.spark.ContextCleaner" level="WARN"/>
            <Logger name="io.kyligence.kap.ext" level="INFO"/>
            <!--  Query log  -->
            <Logger name="io.kyligence.kap.query" level="INFO"/>
            <Logger name="org.apache.kylin.query" level="INFO"/>
            <Logger name="io.kyligence.kap.metadata.cube.model.NDataflowCapabilityChecker" level="INFO" />
            <Logger name="org.apache.kylin.common.util.CheckUtil" level="INFO" />
            <Logger name="io.kyligence.kap.metadata.cube.cuboid.NQueryLayoutChooser" level="INFO" />
            <Logger name="io.kyligence.kap.query.runtime.plan.ResultPlan" level="INFO" />
            <Logger name="org.apache.spark.sql.kylin.external.LogEx" level="INFO" />
            <Logger name="io.kyligence.kap.engine.spark.utils.LogEx" level="INFO" />
        </Loggers>
    </Configuration>