#!groovy

@Library('devopslib') _

pipeline {
    options {
        timeout(time: 3, unit: 'HOURS')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/Newten-CI-On_Cloud/jenkins-agent.yaml'
        }
    }

    parameters {
        string(name: 'repo', defaultValue: 'Kyligence', description: 'Kap repo?')
        string(name: 'branch', defaultValue: 'newten-dev', description: 'Kap branch?')
        credentials(name: 'certificate', credentialType: 'com.cloudbees.plugins.credentials.common.StandardCredentials', defaultValue: 'kyligencegit', required: true)
    }

    stages {
        stage("Checkout Source Code") {
            steps {
                container("git") {
                    dir("sourcecode") {
                        script {
                            retry(3) {
                                githubCheckout 'KAP', 'https', 'github.com', '+refs/pull/*:refs/remotes/origin/pr/*', 'newten-dev'
                            }
                            sh "git apply /jenkinscommon/license/newten.patch"
                            sh "git checkout -- ."
                        }
                    }
                }
            }
        }
        stage('Maven Install') {
            steps {
                container("maven") {
                    dir("sourcecode") {
                        sh script: """
                            mvn -U clean install -T 2C -pl src/external -Dmaven.compile.fork=true -DskipTests
                            mvn -U clean install -T 2C -Dmaven.compile.fork=true -DskipTests
                        """
                    }
                }
            }
        }
        stage('Testing') {
            steps {
                script {
                    simpleNewtenParallelTest()
                }
            }
            post {
                always {
                    timestamps {
                        junit skipPublishingChecks: true, testResults: '*Test-Stage-*/**/target/surefire-reports/*.xml'
                    }
                }
            }
        }
        stage('SonarQube') {
            steps {
                container("sonar-cloud") {
                    dir("sourcecode") {
                        withSonarQubeEnv(credentialsId: 'sonar_credential', installationName: 'sonar cloud') {
                            // You can override the credential to be used
                            sh "mvn sonar:sonar -T 2C -Dsonar.coverage.jacoco.xmlReportPaths=${WORKSPACE}/**/jacoco.xml"
                        }
                    }
                }
            }
        }
    }
}