apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
  finalizers:
  - kubernetes.io/pv-protection
  name: nexus-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2Ti
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: nexus-pvc
    namespace: cicd
  local:
    path: /nexus-data/nexus
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node3
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  volumeMode: Filesystem
