#!groovy

@Library('devopslib') _

pipeline {
    options {
        timeout(time: 2, unit: 'HOURS')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/aws/sfz-cd/jenkins-agent.yaml'
        }
    }

    parameters {
        string(name: 'repo', defaultValue: 'Kyligence', description: 'Kap repo?')
        string(name: 'branch', defaultValue: 'newten-dev', description: 'Kap branch?')
        string(name: 'commitid', defaultValue: 'newten-dev', description: 'Kap branch?')
        string(name: 'version', defaultValue: '4.5.x', description: 'Kap version?')
        credentials(name: 'certificate', credentialType: 'com.cloudbees.plugins.credentials.common.StandardCredentials', defaultValue: 'kyligencegit', required: true)
    }

    stages {
        
        stage("Checkout Source Code") {
            steps {
                container("build") {
                    dir("sourcecode") {
                        script {
                             awsGithubCheckOut 'KAP'
                             sh """ 
                                 echo "------------------------------------------------"
                                     pwd
                                     ls -al
                                 echo "-------------------------------------------------"
                                """
                        }
                    }
                }
            }
        }

        stage('Building Package') {
            steps {
                container("build") {
                    dir("sourcecode") {
                       sh """#!/bin/bash
                                pwd
                                ls -al 
                                mkdir -pv dist
                                touch dist/123.tar.gz
                                cd  kystudio
                                echo "-------------------------------------------------------"
                                cat .npmrc
                                sed -i s#http://10.1.2.111:4873#http://devops-nexus:8081/repository/kyligence-npm#g .npmrc
                                cat .npmrc
                                echo "------------------------------------------------------------"
                                echo -e '\nemail=binbin.zou@kyligence.io' >> .yarnrc
                                echo 'always-auth=true' >> .yarnrc
                                echo '_auth=bnBtLWRldjpucG0tZGV2' >> .yarnrc
                        """
                        //buildNewten(params.version)
                         archiveArtifacts artifacts: 'dist/*.tar.gz', fingerprint: true, followSymlinks: false, onlyIfSuccessful: true
                        sh "ls -al && mkdir -p /var/cicd/artifacts/dev/newten &&  \
                        cp dist/*.tar.gz /var/cicd/artifacts/dev/newten/${version}-`git rev-parse --short HEAD`-${BUILD_NUMBER}-.tar.gz"
                    }
                }
            }
        }
    }
}
