apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv
  namespace: cicd
spec:
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    #volumeHandle: fs-020f20b8abf2b9330::fsap-01fe8e22198132fcc
    volumeHandle: fs-06dbd98a1c4896b01::fsap-0c348454eb8f5480c
