#!groovy

@Library('devopslib') _

def modules = [
        ['name': 'ke-common', 'path': 'kyligence/src/ke-common-booter', 'imageName': 'yinglong-common', 'image': ''],
        ['name': 'data-loading', 'path': 'kylin/src/data-loading-booter', 'imageName': 'yinglong-data-loading', 'image': ''],
        ['name': 'query', 'path': 'kylin/src/query-booter', 'imageName': 'yinglong-query', 'image': ''],
        ['name': 'yinglong-smart', 'path': 'kyligence/src/smart-booter', 'imageName': 'yinglong-smart', 'image': ''],
        ['name': 'yinglong-resource', 'path': 'kyligence/src/resource-booter', 'imageName': 'yinglong-resource', 'image': ''],
        ['name': 'ke-ops', 'path': 'kyligence/src/ops-booter', 'imageName': 'yinglong-ops', 'image': '']
    ]

pipeline {
    options {
        timeout(time: 4, unit: 'HOURS')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/yaml/jenkins-helm-docker-package-agent.yaml'
        }
    }

    environment {
        repo = 'harbor-ofs.kyligence.com'
        dockerRegistryUrl = "http://${repo}"
        registryCredential = 'harbor-docker'
        common = ''
        data_loading = ''
        query = ''
        smart = ''
        frontend = ''
        spark = ''
    }

    parameters {
        string(name: 'commitId_back', defaultValue: 'yinglong-dev', description: '后端Repo(KAP)的branch或者commitid（必填）注：填commitid的时候前端的必填')
        string(name: 'commitId_front', defaultValue: 'yinglong', description: '前端repo(KAP_Frontend)的branch或者commitid（后端填分支名时，该参数可以不填）')
        string(name: 'tag', defaultValue: 'yl-5.0.0', description: '填写版本号，格式：4.5.10，4.3.11，前两位版本号必须规范')
        booleanParam(name: 'build', defaultValue:true, description:'是否构建')
        string(name: 'profiles', defaultValue: 'kubernetes,iam', description: '指定的 profile，kubernetes 会打包 yinglong，iam 会添加 iam 的 jar')
        booleanParam(name: 'push', defaultValue:true, description:'推送镜像')
        choice(name: 'deploy', choices: 'skip\nupgrade\ninstall', description: '部署方式:\nskip - 跳过\nupgrade - 更新\ninstall - 重新部署')
        choice(name: 'namespace', choices: 'yinglong-dev\nyinglong-dev2', description: '选择要部署的namespace')
        string(name: 'hadoop_prefix', defaultValue: 'hadoop', description: 'hadoop environment')
        string(name: 'tenant_id', defaultValue: '', description: 'tenant id')
        string(name: 'metadata_table_name', defaultValue: 'yinglong_metadata', description: 'metadata table name')
        string(name: 'extra_settings', defaultValue: '', description: 'helm set parameter, each set starts with --set , seprated by space')
    }

    stages {
        stage('1.Pull Code') {
            when {
                environment name: 'build', value: 'true'
            }
            steps {
                container('build') {
                    dir('sourcecode') {
                        script {
                            if (!params.commitId_back) {
                                error 'commitId_back 参数不能为空'
                            }

                            echo 'checkout KAP'
                            retry(3) {
                                pullCodeFromGitMirror 'KAP', params.commitId_back
                            }

                            def front
                            if (!params.commitId_front) {
                                echo 'Not commitId_front, use the commitId_back: ${params.commitId_back}'
                                front = params.commitId_back
                            }else {
                                echo 'checkout KAP_Frontend to kystudio, use the commitid: ${params.commitId_front}'
                                front = params.commitId_front
                            }

                            sh 'rm -rf ./kystudio'
                            dir('kystudio') {
                                retry(3) {
                                    pullCodeFromGitMirror 'KAP_Frontend', front
                                }
                            }
                        }
                    }
                }
            }
        }
        stage('2.Building Package') {
            when {
                environment name: 'build', value: 'true'
            }
            steps {
                container('build') {
                    dir('sourcecode') {
                        script {
                            if (!tag) {
                                error 'tag 版本号不能为空'
                            }

                            sh '''
                                sh build/script_newten/download-spark.sh
                                mv build/spark spark
                            '''

                            if (!profiles) {
                                sh '''
                                    mvn -U clean install -T 4C -DskipTests -Dmaven.compile.fork=true
                                '''
                            } else {
                                sh """
                                    mvn -U clean install -T 4C -DskipTests -Dmaven.compile.fork=true -P ${profiles}
                                """
                            }

                            for (m in modules) {
                                dir(m.path) {
                                    sh """
                                        pwd
                                        ls -al target
                                        cp ${env.WORKSPACE}/docker/yinglong-jdk8/Dockerfile Dockerfile
                                        sed -i "s#&&replace_package&&#target/${m.name}*.tar.gz#g" Dockerfile
                                        sed -i "s#&&replace_dir&&#${m.name}#g" Dockerfile
                                        cat Dockerfile
                                    """
                                }
                            }
                        }
                    }
                }
            }
        }
        stage('3.build docker image') {
            when {
                environment name: 'push', value: 'true'
            }
            parallel {
                stage('3.1.image front') {
                    steps {
                        container('docker') {
                            dir('sourcecode') {
                                script {
                                    dir('kystudio') {
                                        sh """
                                            pwd
                                            ls -alt
                                            cat .npmrc
                                            rm -f .npmrc
                                            echo "registry = 'https://repo-ofs.kyligence.com/repository/npm-public/'" > .npmrc
                                            cat .npmrc
                                        """
                                        frontend = docker.build('yinglong/yinglong-frontend', "-f ${env.WORKSPACE}/docker/nginx-node-10.24.1/Dockerfile .")
                                    }
                                }
                            }
                        }
                    }
                }
                stage('3.2.images') {
                    steps {
                        container('docker') {
                            script {
                                for (m in modules) {
                                    sh "ls -lh sourcecode/${m.path}"
                                    dir("sourcecode/${m.path}") {
                                        retry(2) {
                                            println(m.toString())
                                            sh 'ls -lh '
                                            m.image = docker.build("yinglong/${m.imageName}")
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                stage('3.3 image spark'){
                    steps {
                        container('docker') {
                            dir('sourcecode'){
                                script {
                                    sh "ls -alt"
                                    spark = docker.build('yinglong/yinglong-spark', "-f ${env.WORKSPACE}/docker/yinglong-jdk8/Dockerfile4Spark .")
                                }
                            }
                        }
                    }
                }
            }
        }
        stage('4.push images') {
            when {
                environment name: 'push', value: 'true'
            }
            steps {
                container('docker') {
                    script {
                        docker.withRegistry(dockerRegistryUrl, registryCredential) {
                            frontend.push(tag)
                            frontend.push('latest')
                            spark.push(tag)
                            spark.push('latest')
                        }
                        for (m in modules) {
                            retry(2) {
                                docker.withRegistry(dockerRegistryUrl, registryCredential) {
                                    m.image.push(tag)
                                    m.image.push('latest')
                                }
                            }
                        }
                    }
                }
            }
        }
        stage('5.deploy') {
            steps {
                echo 'Up in K8S at office env'
                container('helm') {
                    withCredentials([file(credentialsId: 'admin.kubeconfig', variable: 'KUBECONFIG')]) {
                        script {
                            if (params.deploy == "upgrade") {
                                sh 'pwd && ls -alt'
                                sh "mkdir -p ~/.kube && cp ${KUBECONFIG} ~/.kube/config"

                                sh returnStatus: true , script: """
                                    helm -n ${namespace} list
                                    helm -n ${namespace} upgrade yinglong ./helm/yinglong \
                                        --set global.image.tag=${tag} \
                                        --set global.image.pullPolicy=Always \
                                        --set global.hadoopPrefix=${hadoop_prefix} \
                                        --set global.tenantId=${tenant_id} \
                                        --set global.publicGroup=yinglong \
                                        --set global.nacos.discovery.serverAddrNoHttp=nacos-naming-svc.yinglong:8848 \
                                        --set global.nacos.config.serverAddrNoHttp=nacos-config-svc.yinglong:8848 \
                                        --set 'global.metadata.url=${metadata_table_name}@jdbc\\,driverClassName=com.mysql.jdbc.Driver\\,url=jdbc:mysql://10.1.9.111:3306/kylin?allowMasterDownConnections=true&allowSlavesDownConnections=true&useSSL=false&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8\\,username=yinglong\\,password=cA*BUi#4\\,maxTotal=50\\,maxIdle=8' \
                                        --set 'yl-gateway.image.tag=5.0.1-private' \
                                        --set 'yl-gateway.nacos.serverAddr=nacos-naming-svc.yinglong:8848' \
                                        --set 'yl-gateway.saas.nacos.discovery.group=${tenant_id}' \
                                        --set 'yl-gateway.saas.nacos.discovery.publicGroup=yinglong' ${extra_settings}
                                    helm -n ${namespace} list
                                """
                            } else if (params.deploy == "install") {
                                sh "echo 'not support now'"
                            } else {
                                sh "echo 'skip deploy'"
                            }
                        }
                    }
                }
            }
        }
    }
}
