#!groovy

@Library('devopslib') _

def modules = [
        ['name': 'ke-common', 'path': 'kyligence/src/ke-common-booter', 'imageName': 'yinglong-common', 'image': ''],
        ['name': 'data-loading', 'path': 'kylin/src/data-loading-booter', 'imageName': 'yinglong-data-loading', 'image': ''],
        ['name': 'query', 'path': 'kylin/src/query-booter', 'imageName': 'yinglong-query', 'image': ''],
        ['name': 'yinglong-smart', 'path': 'kyligence/src/smart-booter', 'imageName': 'yinglong-smart', 'image': '']
    ]

pipeline {
    options {
        timeout(time: 4, unit: 'HOURS')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/yaml/jenkins-helm-docker-package-agent.yaml'
        }
    }

    environment {
        repo = 'harbor-ofs.kyligence.com'
        dockerRegistryUrl = "http://${repo}"
        registryCredential = 'harbor-docker'
        common = ''
        data_loading = ''
        query = ''
        smart = ''
        frontend = ''
    }

    parameters {
        string(name: 'commitId_back', defaultValue: 'yinglong-dev', description: '后端Repo(KAP)的branch或者commitid（必填）注：填commitid的时候前端的必填')
        string(name: 'commitId_front', defaultValue: 'yinglong', description: '前端repo(KAP_Frontend)的branch或者commitid（后端填分支名时，该参数可以不填）')
        string(name: 'tag', defaultValue: 'yl-5.0.0', description: '填写版本号，格式：4.5.10，4.3.11，前两位版本号必须规范')
        booleanParam(name: 'build', defaultValue:true, description:'是否构建')
        string(name: 'profiles', defaultValue: 'kubernetes,iam', description: '指定的 profile，kubernetes 会打包 yinglong，iam 会添加 iam 的 jar')
        booleanParam(name: 'include_spark', defaultValue:true, description:'是否内置spark包')
        booleanParam(name: 'push', defaultValue:true, description:'推送镜像')
        booleanParam(name: 'deploy', defaultValue:false, description:'部署在 k8s')
        string(name: 'namespace', defaultValue: 'dev', description: 'namespace to deploy')
        string(name: 'hadoop_prefix', defaultValue: 'hadoop-0', description: 'hadoop environment')
        string(name: 'tenant_id', defaultValue: '', description: 'tenant id')
        string(name: 'extra_settings', defaultValue: '', description: 'helm set parameter, each set starts with --set , seprated by space')
    }

    stages {
        stage {
            steps {
                container('docker') {
                    script {
                        sh 'ls -lh /root/.docker/'
                        sh 'cat /root/.docker/config.json'
                    }
                }
            }
        }
        stage('1.Pull Code') {
            when {
                environment name: 'build', value: 'true'
            }
            steps {
                container('build') {
                    dir('sourcecode') {
                        script {
                            if (!params.commitId_back) {
                                error 'commitId_back 参数不能为空'
                            }

                            echo 'checkout KAP'
                            retry(3) {
                                pullCodeFromGitMirror 'KAP', params.commitId_back
                            }

                            def front
                            if (!params.commitId_front) {
                                echo 'Not commitId_front, use the commitId_back: ${params.commitId_back}'
                                front = params.commitId_back
                            }else {
                                echo 'checkout KAP_Frontend to kystudio, use the commitid: ${params.commitId_front}'
                                front = params.commitId_front
                            }

                            sh 'rm -rf ./kystudio'
                            dir('kystudio') {
                                retry(3) {
                                    pullCodeFromGitMirror 'KAP_Frontend', front
                                }
                            }
                        }
                    }
                }
            }
        }
        stage('2.Building Package') {
            when {
                environment name: 'build', value: 'true'
            }
            steps {
                container('build') {
                    dir('sourcecode') {
                        script {
                            if (!tag) {
                                error 'tag 版本号不能为空'
                            }

                            if (include_spark) {
                                sh '''
                                    sh build/script_newten/download-spark.sh
                                '''
                            }

                            if (!profiles) {
                                sh '''
                                    mvn -U clean install -T 4C -DskipTests -Dmaven.compile.fork=true
                                '''
                            } else {
                                sh """
                                    mvn -U clean install -T 4C -DskipTests -Dmaven.compile.fork=true -P ${profiles}
                                """
                            }

                            for (m in modules) {
                                dir(m.path) {
                                    sh """
                                        pwd
                                        ls -al
                                        cp ${env.WORKSPACE}/docker/yinglong-jdk8/Dockerfile Dockerfile
                                        sed -i "s#&&replace_package&&#target/${m.name}*.tar.gz#g" Dockerfile
                                        sed -i "s#&&replace_dir&&#${m.name}#g" Dockerfile
                                        cat Dockerfile
                                    """
                                }
                            }
                        }
                    }
                }
            }
        }
        stage('3.build docker image') {
            when {
                environment name: 'push', value: 'true'
            }
            parallel {
                stage('3.1.image front') {
                    steps {
                        container('docker') {
                            dir('sourcecode') {
                                script {
                                    dir('kystudio') {
                                        sh """
                                            pwd
                                            ls -alt
                                            cat .npmrc
                                            rm -f .npmrc
                                            echo "registry = 'https://repo-ofs.kyligence.com/repository/npm-public/'" > .npmrc
                                            cat .npmrc
                                        """
                                        frontend = docker.build('yinglong/yinglong-frontend', "-f ${env.WORKSPACE}/docker/nginx-node-10.24.1/Dockerfile .")
                                    }
                                }
                            }
                        }
                    }
                }
                stage('3.2.images') {
                    steps {
                        container('docker') {
                            script {
                                sh 'ls -lh /root/.docker/'
                                sh 'cat /root/.docker/config.json'
                                for (m in modules) {
                                    dir("sourcecode/${m.path}") {
                                        retry(2) {
                                            m.image = docker.build("yinglong/${m.imageName}")
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        stage('4.push images') {
            when {
                environment name: 'push', value: 'true'
            }
            steps {
                script {
                    pushImage(frontend, tag)
                    for (m in modules) {
                        retry(2) {
                            docker.withRegistry(dockerRegistryUrl, registryCredential) {
                                m.image.push(release_tag_back)
                                m.image.push('latest')
                            }
                        }
                    }
                }
            }
        }
        stage('5.deploy') {
            when {
                environment name: 'deploy', value: 'true'
            }
            steps {
                echo 'Up in K8S at office env'
                container('helm') {
                    withCredentials([file(credentialsId: 'kubeconfig', variable: 'KUBECONFIG')]) {
                        script {
                            sh 'pwd && ls -alt'
                            sh "mkdir -p ~/.kube && cp ${KUBECONFIG} ~/.kube/config"

                            try {
                                sh returnStatus: true , script: """
                                    helm -n ${namespace} list
                                    helm -n ${namespace} uninstall yinglong
                                """
                            } catch (Exception err) {
                                echo err.getMessage()
                                echo 'delete resource failed, but we will continue.'
                            }

                            sh returnStatus: true , script: """
                                helm -n ${namespace} install yinglong ./helm/yinglong
                                    --set yinglong-common.image.tag=${tag}
                                    --set yinglong-data-loading.image.tag=${tag}
                                    --set yinglong-query.image.tag=${tag}
                                    --set yinglong-smart.image.tag=${tag}
                                    --set yinglong-frontend.image.tag=${tag}
                                    --set global.hadoopPrefix=${hadoop_prefix}
                                    --set global.tenantId=${params.tenant_id} ${params.extra_settings}
                                helm -n ${namespace} list
                            """
                        }
                    }
                }
            }
        }
    }
}
