# Default values for global-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  nacos:
    discovery:
      group: global-service

  redis:
    host: redis-svc.xuanwu-depend.svc.cluster.local
    database: 0
    password:

  mysql:
    host: mysql-svc.xuanwu-depend.svc.cluster.local
    port: 3306
    user: root
    password: kyligence
    connectionOptions: createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false

  kyligence:
    deployMode: KA

gateway:
  tenantName: "saas-kyiam saas-tenant"
  imagePullSecrets: []
  #  - name: "image pull secret"
  image:
    pullPolicy: IfNotPresent
    repository: registry.cn-shanghai.aliyuncs.com/kyligence-xuanwu/gateway
    tag: gatewaytaglatest
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }

iam:
  kyligence:
    request:
      domain: xuanwurootdomain
  imagePullSecrets: []
  #  - name: "image pull secret"
  image:
    pullPolicy: IfNotPresent
    repository: registry.cn-shanghai.aliyuncs.com/kyligence-xuanwu/iam-server
    tag: xuanwutaglatest
  frontend:
    image:
      pullPolicy: IfNotPresent
      repository: registry.cn-shanghai.aliyuncs.com/kyligence-xuanwu/iam-frontend
      tag: iamfrontendtaglatest
  config:
    mysql:
      db: saas-kyiam
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }

nacos:
  config:
    imagePullSecrets: []
    #  - name: "image pull secret"
    image:
      pullPolicy: IfNotPresent
      repository: registry.cn-shanghai.aliyuncs.com/kyligence-xuanwu/kynacos
      tag: kynacostaglatest
  naming:
    imagePullSecrets: []
    #  - name: "image pull secret"
    image:
      pullPolicy: IfNotPresent
      repository: registry.cn-shanghai.aliyuncs.com/kyligence-xuanwu/kynacos
      tag: kynacostaglatest
  mysql:
    db: nacos
    imagePullSecrets: []
    #  - name: "image pull secret"
    image:
      repository: registry.cn-shanghai.aliyuncs.com/kyligence-xuanwu/mysql
      pullPolicy: IfNotPresent
      tag: 5.7
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }

nacos-frontend:
  iam:
    serverAddr: http://iam.xuanwurootdomain
  config:
    serverAddr: http://config.xuanwurootdomain
  imagePullSecrets: []
  #  - name: "image pull secret"
  image:
    pullPolicy: IfNotPresent
    repository: registry.cn-shanghai.aliyuncs.com/kyligence-xuanwu/kynacos-frontend
    tag: kynacosfrontendtaglatest
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }

openldap:
  env:
    LDAP_ORGANISATION: "Example Inc."
    LDAP_DOMAIN: "example.org"
  adminPassword: xuanwu
  configPassword: xuanwu
  imagePullSecrets: []
  #  - name: "image pull secret"
  image:
    pullPolicy: IfNotPresent
    repository: registry.cn-shanghai.aliyuncs.com/kyligence-xuanwu/openldap
    tag: openldaptaglatest
  persistence:
    enabled: true
    storageClass: local-path
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }

phpldapadmin:
  imagePullSecrets: []
  #  - name: "image pull secret"
  image:
    pullPolicy: IfNotPresent
    repository: registry.cn-shanghai.aliyuncs.com/kyligence-xuanwu/phpldapadmin
    tag: phpldapadmintaglatest
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }

