apiVersion: v1
kind: Service
metadata:
  name: hdfs-namenode
  namespace: <<<namespace>>>
spec:
  ports:
    - name: "50070"
      port: 50070
      targetPort: 50070
    - name: "9870"
      port: 9870
      targetPort: 9870
    - name: "8020"
      port: 8020
      targetPort: 8020
  selector:
    io.kompose.service: hdfs-namenode
