apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: hdfs-namenode
  name: hdfs-namenode
  namespace: <<<namespace>>>
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hdfs-namenode
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: hdfs-namenode
    spec:
      initContainers:
      - name: jmx-exporter
        image: repo-ofs.kyligence.com:5000/jmx-prometheus-javaagent:0.16.1
        volumeMounts:
        - name: exporter-dir
          mountPath: /opt/jmx-exporter/
        - mountPath: /hadoop/dfs/name
          name: hdfs-namenode-claim0
        command:
          - sh
          - "-c"
          - |
            set -x
            rm -rf /hadoop/dfs/name/lost+found
            cp /opt/jmx_prometheus_javaagent-0.16.1.jar /opt/jmx-exporter/
      containers:
      - name: hdfs-namenode
        envFrom:
        - configMapRef:
            name: hdfs-env
        env:
          - name: CLUSTER_NAME
            value: test-kylin
          - name: HADOOP_MODE
            value: namenode
          - name: HADOOP_WEBHDFS_PORT
            value: "50070"
          - name: FORMAT_MESSAGES_PATTERN_DISABLE_LOOKUPS
            value: "true"
          - name: HADOOP_OPTS
            value: -javaagent:/opt/jmx-exporter/jmx_prometheus_javaagent-0.16.1.jar=8080:/opt/jmx-exporter/config.yaml
        image: kyligence/hadoop:2.10.1
        ports:
          - containerPort: 50070
          - containerPort: 8020
        livenessProbe:
          failureThreshold: 20
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          httpGet:
            path: /
            port: 50070
        readinessProbe:
          failureThreshold: 20
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          httpGet:
            path: /
            port: 50070
        volumeMounts:
          - mountPath: /hadoop/dfs/name
            name: hdfs-namenode-claim0
          - name: exporter-dir
            mountPath: /opt/jmx-exporter/
          - name: jmx-config
            mountPath: /opt/jmx-exporter/config.yaml
            subPath: config.yaml
      volumes:
        - name: hdfs-namenode-claim0
          persistentVolumeClaim:
            claimName: hdfs-namenode-claim0
        - name: exporter-dir
          emptyDir: {}
        - name: jmx-config
          configMap:
            name: jmx-exporter-config
