#!groovy

@Library('devopslib') _

pipeline {
    options {
        timeout(time: 2, unit: 'HOURS')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/yaml/jenkins-package-agent.yaml'
        }
    }

    parameters {
        string(name: 'repo', defaultValue: 'Kyligence', description: 'bi-adapter repo')
        string(name: 'branch', defaultValue: 'master', description: 'branch')
        string(name: 'version', defaultValue: '', description: 'input sdk version')
        booleanParam(name: 'skipTests', defaultValue: false, description: 'skip ut tests')
        booleanParam(name: 'isDeploy', defaultValue: false, description: 'is deploy')
        booleanParam(name: 'isDeploySolution', defaultValue: false, description: 'is deploy to solution')
    }

    environment {
        ENVIRONMENT_TEST_FLAG = 'NO'
    }

    stages {
        stage("Checkout Source Code") {
            steps {
                container("build") {
                    dir("sourcecode") {
                        script {
                            retry(3) {
                                githubCheckout 'inspection-tool', "${branch ?: params.branch ?: 'main'}", 'https', 'github.com', '+refs/heads/*:refs/remotes/origin/*','kyligence-git'
                            }
                        }
                    }
                }
            }
        }
        stage('Maven Install') {
            steps {
                container("build") {
                    sh "cat /root/.m2/settings.xml"
                    dir("sourcecode") {
                        script {
                            if (params.skipTests) {
                                sh script: """
                                    echo "skip tests"
                                    mvn clean install -DskipTests
                                """
                            } else {
                                sh script: """
                                    mvn clean install
                                """
                            }
                        }
                        sh script: """
                            echo "start deploy SNAPSHOT ${params.isDeploy}"
                            mvn clean deploy  -DskipTests -Pcse
                        """
                    }
                }
            }
        }
        stage('Deploy') {
            when {
                expression {
                    return params.isDeploy
                }
            }
            steps {
                container("build") {
                    sh "cat /root/.m2/settings.xml"
                    dir("sourcecode") {
                        sh script: """
                            echo "start deploy ${params.isDeploy}"
                            mvn versions:set -DnewVersion=${version}
                            mvn clean deploy  -DskipTests -Pcse
                        """
                    }
                }
            }
        }
        stage('tag') {
            when {
                expression {
                    return params.isDeploy
                }
            }
            steps {
                container("build") {
                    dir("sourcecode") {
                        script {
                            def branch = "${branch ?: params.branch ?: 'master'}"
                            def version = "${params.version}"
                            cmd = "sh /root/KETEST/do_tag.sh inspection-tool " + branch + " " + version
                            echo "cmd: ${cmd}"
                            sshCmdWithCredentials(
                                    cmd,
                                    'shuiaileiroot',
                                    ['name':'localhost','host':'10.1.2.181', 'allowAnyHosts': true]
                            )
                        }
                    }
                }
            }
        }
        stage('deploy to solution') {
            when {
                expression {
                    return params.isDeploySolution && params.isDeploy
                }
            }
            steps {
                script {
                    def version = "${params.version}"
                    cmd = "sh /home/solution/public/inspection-web/restart-by-jenkins.sh jenkins " + version
                    echo "cmd: ${cmd}"
                    sshCmdWithCredentials(
                            cmd,
                            'jiahangsolution',
                            ['name':'solution','host':'10.1.3.61', 'allowAnyHosts': true]
                    )
                }
            }
        }
    }
}
