#!groovy

@Library('devopslib') _

pipeline {
    options {
        timeout(time: 2, unit: 'HOURS')
        ansiColor('xterm')
    }

    agent {
        label '10.1.1.118-hdp2.4'
    }

    parameters {
        string(name: 'repo', defaultValue: 'Kyligence', description: '')
        string(name: 'branch', defaultValue: 'kycalcite-1.16.0.x-3.x', description: '')
        string(name: 'WHORU', defaultValue: 'anonymous', description: 'who are you?')
    }

    stages {
        stage('Pull Code') {
            steps {
                script {
                    currentBuild.displayName = "#${BUILD_NUMBER} for ${params.WHORU}"
                }
                dir('kycalcite') {
                    timestamps {
                        script {
                            retry(3) {
                                pullCodeFromGitMirror "calcite", "${params.branch}", false, "${params.repo}"
                            }
                        }
                    }
                }

            }
        }

        stage('Build') {
            steps {
                dir("kycalcite"){
                    sh script: """
                        mvn -s /mnt/jenkins/pom-for-deploy/settings_kycalcite.xml clean deploy -DskipTests=true -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dmaven.wagon.http.ssl.ignore.validity.dates=true
                    """
                }
            }
        }
    }
}
