{
 "title": "Volcano Queue Overview",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "queue",
    "query": {
     "query": "label_values(volcano_queue_share,queue_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Queue Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Running Jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "volcano_queue_pod_group_running_count{queue_name=\"$queue\"}"
    }
   ]
  },
  {
   "title": "InQueue Jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "volcano_queue_pod_group_inqueue_count{queue_name=\"$queue\"}"
    }
   ]
  },
  {
   "title": "Pending Jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "volcano_queue_pod_group_pending_count{queue_name=\"$queue\"}"
    }
   ]
  },
  {
   "title": "Overused",
   "type": "stat",
   "description": "This is to indicate the resource is overused",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "volcano_queue_overused{queue_name=\"$queue\"}"
    }
   ]
  },
  {
   "title": "Running Jobs Trend",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "volcano_queue_pod_group_running_count{queue_name=\"$queue\"}",
     "legendFormat": "Running Jobs"
    }
   ]
  },
  {
   "title": "Request CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "volcano_queue_request_milli_cpu{queue_name=\"$queue\"}",
     "legendFormat": "volcano_job"
    }
   ]
  },
  {
   "title": "Request Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "volcano_queue_request_memory_bytes{queue_name=\"$queue\"}",
     "legendFormat": "volcano_job"
    }
   ]
  },
  {
   "title": "Allocated CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "volcano_queue_allocated_milli_cpu{queue_name=\"$queue\"}",
     "legendFormat": "volcano_job"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "volcano_queue_allocated_memory_bytes{queue_name=\"$queue\"}",
     "legendFormat": "volcano_job"
    }
   ]
  },
  {
   "title": "Pending Jobs Trend",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "volcano_queue_pod_group_pending_count{queue_name=\"$queue\"}",
     "legendFormat": "Pending Jobs"
    }
   ]
  },
  {
   "title": "Jobs Breakdown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Queue Running Job Scheduling Duration",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "increase(volcano_e2e_job_scheduling_duration{queue=\"$queue\"}[24h]) != 0  "
    }
   ]
  },
  {
   "title": "Running CPU Trend",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "volcano_queue_allocated_milli_cpu{queue_name=\"$queue\"}",
     "legendFormat": "CPU Cores"
    }
   ]
  },
  {
   "title": "Running Memory Trend",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "volcano_queue_allocated_memory_bytes{queue_name=\"$queue\"}"
    }
   ]
  }
 ]
}