apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "iam.fullname" . }}
data:
  config.yaml: |
    spring:
      datasource:
        driver-class-name: {{ .Values.config.db.driverClassName }}
        # url: {{ .Values.config.db.url }}
        url: jdbc:mysql://{{ .Values.config.mysql.host }}:{{ .Values.config.mysql.port }}/{{ .Values.config.mysql.db }}?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: {{ .Values.config.db.username }}
        password: {{ .Values.config.db.password }}
      redis:
        host: {{ .Values.global.redis.host }}
        database: {{ .Values.global.redis.database }}
        password: {{ .Values.global.redis.password }}
    saas:
      nacos:
        discovery:
          group: {{ ((.Values.nacos).discovery).group | default .Release.Namespace }}
          public-group: {{ ((.Values.nacos).discovery).publicGroup | default .Release.Namespace }}
          server-addr: {{ .Values.nacos.discovery.serverAddr }}
        config:
          server-addr: {{ .Values.nacos.config.serverAddr }}
    kyligence:
      user:
        msg:
          webhook: {{ .Values.kyligence.webhook }}
        sync:
          enable: {{ .Values.kyligence.sync }}
      request:
        domain: {{ .Values.kyligence.request.domain }}
  IAM_DEPLOY_MODE: {{ .Values.kyligence.deployMode }}