#!groovy

@Library('devopslib') _

pipeline {
    options {
        timeout(time: 1, unit: 'HOURS')
    }

    agent any

    parameters {
        string(name: 'package_version', defaultValue: '', description: 'package version?')
        string(name: 'run_env', defaultValue: '', description: 'start env?')
    }

    stages {
        stage('Running') {
            steps {
                sh "echo Kyligence-Enterprise-${package_version}.${run_env}.tar.gz"
                sh "exit 1"
            }
        }
    }
}