apiVersion: v1
kind: ConfigMap
metadata:
  name: saas-gateway
data:
  config.yaml: |
    spring:
      redis:
        host: {{ .Values.config.redis.host }}
        database: {{ .Values.config.redis.database }}
        password: {{ .Values.config.redis.password }}

    saas:
      gateway:
        integrate:
          iam: {{.Values.saas.gateway.integrate.iam}}