{
 "title": "Volcano Global Overview Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "TPH –Schedule Task In 1 Hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max_over_time(kube_pod_container_status_running{job=\"kube-state-metrics\"}[1h]) != 0)"
    }
   ]
  },
  {
   "title": "Volcano Node",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_info{job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Volcano CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{job=\"kube-state-metrics\", resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Volcano Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{job=\"kube-state-metrics\", resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Volcano GPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_node_status_capacity{resource=\"nvidia_com_gpu\",job=\"kube-state-metrics\"}"
    }
   ]
  },
  {
   "title": "Volcano CPU Usage Sort By Queue",
   "type": "table",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(volcano_queue_allocated_milli_cpu) by (queue_name)",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Volcano Memory Usage Sort By Queue",
   "type": "table",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(volcano_queue_allocated_memory_bytes) by (queue_name)",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Volcano Job Scheduling Avg Duration By Queue",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(volcano_e2e_job_scheduling_duration{}) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Volcano Job Scheduling Duration",
   "type": "table",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "increase(volcano_e2e_job_scheduling_duration{}[24h]) != 0"
    }
   ]
  },
  {
   "title": "Volcano Latency Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "increase(volcano_e2e_job_scheduling_latency_milliseconds_bucket[1h])",
     "legendFormat": "{{le}} ms"
    }
   ]
  },
  { "title": "Volcano Effectiveness", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Volcano Cluster Average CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n(sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (pod,namespace)) * on(pod) (max(kube_pod_container_status_running{}) \nby (pod,namespace)))/\nsum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\"})"
    }
   ]
  },
  {
   "title": "Volcano Cluster Average Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (pod,namespace)) * on(pod) (max(kube_pod_container_status_running{}) by (pod,namespace)))/sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\"})"
    }
   ]
  },
  {
   "title": "Volcano Cluster Average GPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((sum(kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}) by (pod,namespace)) * on(pod) (max(kube_pod_container_status_running{}) by (pod,namespace)))/sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"})"
    }
   ]
  },
  {
   "title": "Node Resource Coefficient Of Variation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "stddev(sum by (node) (kube_pod_container_resource_requests{resource=\"cpu\"}))/avg(sum by (node) (kube_pod_container_resource_requests{resource=\"cpu\"}))",
     "legendFormat": "CV (CPU)"
    },
    {
     "expr": "stddev(sum by (node) (kube_pod_container_resource_requests{resource=\"memory\"}))/avg(sum by (node) (kube_pod_container_resource_requests{resource=\"memory\"}))",
     "legendFormat": "CV (Memory)"
    },
    {
     "expr": "stddev(sum by (node) (kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}))/avg(sum by (node) (kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}))",
     "legendFormat": "CV (Nvidia GPU)"
    }
   ]
  },
  {
   "title": "Volcano Fairness",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job Duration Coefficient Of Variation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "stddev(volcano_e2e_job_scheduling_duration)/avg(volcano_e2e_job_scheduling_duration)",
       "legendFormat": "CV (Job Duration)"
      }
     ]
    }
   ]
  }
 ]
}