apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data-pv
spec:
  storageClassName: managed-nfs-storage
  capacity:
    storage: 30Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/sonar/postgresql  # 指定nfs的挂载点
    server: 10.1.9.11  # 指定nfs服务地址