---
apiVersion: v1
kind: "Pod"
name: "jenkins-agent"
spec:
  nodeSelector:
    cicd: ''
  tolerations:
    - key: cicd
      operator: Equal
      effect: NoSchedule
  containers:
    - name: "helm"
      image: "bsord/helm-push:latest"
      imagePullPolicy: "IfNotPresent"
      tty: true
      command:
        - "cat"
      resources:
        request:
          cpu: "100m"
          memory: "500Mi"
        limits:
          cpu: "300m"
          memory: "800Mi"
