#!groovy

@Library('devopslib') _

pipeline {
    options {
        timeout(time: 2, unit: 'HOURS')
        ansiColor('xterm')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/yaml/jenkins-parquet-agent.yaml'
        }
    }

    parameters {
        string(name: 'repo', defaultValue: 'Kyligence', description: '')
        string(name: 'branch', defaultValue: 'kyparquet-1.12.2-4.x', description: '')
        // string(name: 'WHORU', defaultValue: 'anonymous', description: 'who are you?')
    }

    stages {
        stage('Pull Code') {
            steps {
                container('build') {
                    timestamps {
                        script {
                            dir('kyparquet') {
                                sh "thrift -version"
                                if(params.repo && params.repo != "Kyligence") {
                                    println "暂不支持其他仓库"
                                }else{
                                    pullCodeFromGitMirror "parquet-mr", "${params.branch}", false, "${params.repo}"
                                }
                            }
                            sh "cp -r kyparquet ./kyparquet2"
                            sh "cp -r kyparquet ./kyparquet3"
                        }
                    }
                }
            }
        }
        stage('Build') {
            steps {
                container('build') {
                    dir("kyparquet"){
                        sh "mvn clean install -DskipTests=true -Paliyun -U"
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                container('build') {
                    dir("kyparquet") {
                        sh "mvn deploy -DskipTests=true -Pdev"
                        sh "mvn deploy -DskipTests=true -Paws"
                        sh "mvn deploy -DskipTests=true -Ppro"
                    }
                }
            }
        }
    }
}
