#!groovy

@Library('devopslib') _

pipeline {
    options {
        timeout(time: 2, unit: 'HOURS')
        ansiColor('xterm')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/yaml/jenkins-parquet-agent.yaml'
        }
    }

    parameters {
        string(name: 'repo', defaultValue: 'Kyligence', description: '')
        string(name: 'branch', defaultValue: 'kyparquet-1.12.2-4.x', description: '')
        // string(name: 'WHORU', defaultValue: 'anonymous', description: 'who are you?')
    }

    stages {
        stage('Pull Code') {
            steps {
                container('build') {
                    dir('kycalcite') {
                        timestamps {
                            script {
                                sh "thrift -version"
                                retry(3) {
                                    pullCodeFromGitMirror "parquet-mr", "${params.branch}", false, "${params.repo}"
                                }
                            }
                        }
                    }
                }
            }
        }
        stage('Deploy') {
            parallel {
                stage('Deploy Ofs') {
                    steps {
                        container('build') {
                            dir("kycalcite"){
                                sh script: """
                                    mvn clean deploy -DskipTests=true -Pdev --settings /root/.m2/settings.xml
                                """
                            }
                        }
                    }
                }
                stage('Deploy OpenSource') {
                    steps {
                        container('build') {
                            dir("kycalcite"){
                                sh script: """
                                    mvn clean deploy -DskipTests=true -Ppro --settings /root/.m2/settings.xml
                                """
                            }
                        }
                    }
                }
            }
        }
    }
}
