kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "yinglong-data-loading.fullname" . }}-conf
data:
  fairscheduler.xml: |
    <?xml version="1.0"?>
    <allocations>
        <pool name="query_pushdown">
            <schedulingMode>FAIR</schedulingMode>
            <weight>1</weight>
            <minShare>1</minShare>
        </pool>
        <pool name="extreme_heavy_tasks">
            <schedulingMode>FAIR</schedulingMode>
            <weight>3</weight>
            <minShare>1</minShare>
        </pool>
        <pool name="heavy_tasks">
            <schedulingMode>FAIR</schedulingMode>
            <weight>5</weight>
            <minShare>1</minShare>
        </pool>
        <pool name="lightweight_tasks">
            <schedulingMode>FAIR</schedulingMode>
            <weight>10</weight>
            <minShare>1</minShare>
        </pool>
        <pool name="vip_tasks">
            <schedulingMode>FAIR
            </schedulingMode>
            <weight>15</weight>
            <minShare>1</minShare>
        </pool>
    </allocations>
  check-env-bypass: ''
  log4j2.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration name="Log4j1">
        <Appenders>
            <RollingRandomAccessFile name="server" fileName="${env:KYLIN_HOME}/logs/kylin.log" append="true"
                                     filePattern="${env:KYLIN_HOME}/logs/kylin.log.%i" immediateFlush="false">
                <Policies>
                    <SizeBasedTriggeringPolicy size="268435456"/>
                </Policies>
                <DefaultRolloverStrategy max="10"/>
                <PatternLayout pattern="%d{ISO8601} %-5p %X{request.project}[%t] %c{2} : %mask{%m}%n"/>
            </RollingRandomAccessFile>
        </Appenders>
        <Loggers>
            <Root level="TRACE">
                <AppenderRef ref="server"/>
            </Root>
        </Loggers>
    </Configuration>
