apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "yinglong-data-loading.fullname" . }}
  labels:
    {{- include "yinglong-data-loading.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "yinglong-data-loading.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "yinglong-data-loading.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: spark
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: lib-ext
            persistentVolumeClaim:
              claimName: yinglong-lib-ext
        - name: newten-conf
          configMap:
            name: {{ include "yinglong-data-loading.fullname" . }}-conf
            defaultMode: 511
        - configMap:
            name: {{ .Values.global.hadoopPrefix }}-yarn-xml
          name: yarn-xml
      {{- if .Values.skyWalking.enabled }}
        - name: skywalking-agent
          emptyDir: { }
      initContainers:
        - name: agent-container
          image: apache/skywalking-java-agent:8.7.0-alpine
          volumeMounts:
            - name: skywalking-agent
              mountPath: /agent
          command: [ "/bin/sh" ]
          args: [ "-c", "cp -R /skywalking/agent /agent/" ]
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: KYLIN_HOME
              value: /opt/kyligence
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NACOS_CONFIG_SERVER_ADDR
              value: {{ .Values.global.nacos.config.serverAddr | default .Values.global.nacos.serverAddr}}
            - name: NACOS_DISCOVERY_SERVER_ADDR
              value: {{ .Values.global.nacos.discovery.serverAddr | default .Values.global.nacos.serverAddr}}
            - name: TENANT_ID
              value:  {{ .Values.global.tenantId | quote}}
            - name: DISCOVERY_PUBLIC_GROUP
              value:  {{ .Values.global.publicGroup | quote}}
            - name: SPRING_SESSION_STORE_TYPE
              value: jdbc
            - name: KYLIN_ENV_ZOOKEEPER_CONNECT_STRING  
              value: {{ .Values.global.zookeeper.address | default (printf "%s-zk-cs:2181" .Values.global.hadoopPrefix) }}
            - name: KYLIN_ENV_HDFS_WORKING_DIR
              value: {{ .Values.global.hdfs.workingDir | default (printf "/kylin/%s_%s" (.Values.global.metadata.identifierPrefix) (.Release.Namespace)) }}
            - name: KYLIN_METADATA_URL
              value: {{ .Values.global.metadata.url | default (printf "%s_%s@jdbc,driverClassName=com.mysql.jdbc.Driver,url=jdbc:mysql://%s-mysql:3306/%s?allowMasterDownConnections=true&allowSlavesDownConnections=true&useSSL=false&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8,username=%s,password=%s,maxTotal=50,maxIdle=8" .Values.global.metadata.identifierPrefix  .Release.Namespace  .Values.global.hadoopPrefix .Values.global.metadata.database .Values.global.metadata.user .Values.global.metadata.password ) }}
            - name: HADOOP_CONF_DIR
              value: $(KYLIN_HOME)/hadoop_conf
            - name: HADOOP_CLASSPATH
              value: /opt/hadoop-2.10.1/share/hadoop/tools/lib/*
            {{- if .Values.skyWalking.enabled }}
            - name: SW_AGENT_NAME
              value: "{{ include "yinglong-data-loading.fullname" . }}"
            - name: SW_AGENT_NAMESPACE
              value: "{{ .Release.Namespace }}"
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "{{ .Values.skyWalking.backendServerAddr }}"
            {{- end }}
          command:
            - sh
            - "-x"
            - "-c"
            - |
              {{- $skyWalking := "" -}}
              {{- if .Values.skyWalking.enabled }}
              {{- $skyWalking = "-javaagent:/skywalking/agent/skywalking-agent.jar" }}
              {{- end }}
              {{- $javaDebug := "" -}}
              {{- if .Values.debug.enabled }}
              {{- $javaDebug = "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"}}
              {{- end}}
              date
              mkdir ${KYLIN_HOME}/logs
              cd ${KYLIN_HOME}/server
              nohup java {{ $skyWalking }} -server -Xms1g -Xmx8g -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:G1HeapRegionSize=16m -XX:+PrintReferenceGC -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCDateStamps -XX:+PrintAdaptiveSizePolicy -XX:+UnlockDiagnosticVMOptions -XX:+G1SummarizeConcMark -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/kyligence/logs -Xloggc:/opt/kyligence/logs/kylin.gc.%p -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=64M {{ $javaDebug }} -Dlog4j2.contextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector -DAsyncLogger.RingBufferSize=8192 -Dfile.encoding=UTF-8 -Dlogging.path=/opt/kyligence/logs -Dspring.profiles.active=prod -Dlogging.config=file:/opt/kyligence/conf/log4j2.xml -Dkylin.hadoop.conf.dir=/opt/kyligence/hadoop_conf -Dhdp.version=current -Dloader.path="/opt/kyligence/hadoop_conf,/opt/kyligence/conf,/opt/kyligence/lib/ext,/opt/kyligence/server/jars,/opt/kyligence/spark/jars" -XX:OnOutOfMemoryError="sh /opt/kyligence/bin/guardian.sh kill" -jar /opt/kyligence/server/newten.jar --kylin.server.mode=all 2>&1 < /dev/null & 
              echo $! >> /opt/kyligence/pid 
              while [[ ! -f $KYLIN_HOME/logs/kylin.log ]];
              do
              echo "kylin not startup, will sleep 10 sec"
              sleep 10
              done
              tail -300f $KYLIN_HOME/logs/kylin.log
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: debug
              containerPort: {{ .Values.service.debugPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /opt/kyligence/conf/fairscheduler.xml
              name: newten-conf
              subPath: fairscheduler.xml
            - mountPath: /opt/kyligence/bin/check-env-bypass
              name: newten-conf
              readOnly: false
              subPath: check-env-bypass
            - mountPath: /opt/kyligence/hadoop_conf/core-site.xml
              name: yarn-xml
              subPath: core-site.xml
            - mountPath: /opt/kyligence/hadoop_conf/hive-site.xml
              name: yarn-xml
              subPath: hive-site.xml
            - mountPath: /opt/kyligence/hadoop_conf/hiveserver2-site.xml
              name: yarn-xml
              subPath: hive-site.xml
            - mountPath: /opt/kyligence/hadoop_conf/hivemetastore-site.xml
              name: yarn-xml
              subPath: hive-site.xml
            - mountPath: /opt/kyligence/hadoop_conf/hdfs-site.xml
              name: yarn-xml
              subPath: hdfs-site.xml
            - mountPath: /opt/kyligence/hadoop_conf/yarn-site.xml
              name: yarn-xml
              subPath: yarn-site.xml
            - mountPath: /opt/kyligence/hadoop_conf/fair-scheduler.xml
              name: yarn-xml
              subPath: fair-scheduler.xml
            - mountPath: /opt/kyligence/conf/log4j2.xml
              name: newten-conf
              subPath: log4j2.xml
            {{- if .Values.skyWalking.enabled }}
            - name: lib-ext
              mountPath: /opt/kyligence/lib/ext
            - name: skywalking-agent
              mountPath: /skywalking
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
