apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "query.fullname" . }}
  labels:
    {{- include "query.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "query.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "query.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: spark
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: lib-ext
          persistentVolumeClaim:
            claimName: yinglong-lib-ext
        - name: newten-conf
          configMap:
            name: {{ include "query.fullname" . }}-conf
            defaultMode: 511
        - configMap:
            name: {{ .Values.global.hadoopPrefix }}-yarn-xml
          name: yarn-xml
        {{- if .Values.global.configcenter.disabled }}
        - configMap:
            name: kylin.properties.yaml
          name: kylin-properties
        {{- end }}
      {{- if .Values.skyWalking.enabled }}
        - name: skywalking-agent
          emptyDir: { }
      {{- end }}
        - name: spark
          emptyDir: { }
      initContainers:
        - name: spark-init
          image: "{{ .Values.global.spark.image.repository }}:{{ .Values.global.spark.image.tag }}"
          imagePullPolicy: {{ .Values.global.spark.image.pullPolicy | default .Values.global.image.pullPolicy }}
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 1
              memory: 1Gi
          volumeMounts:
            - name: spark
              mountPath: /spark
          command: [ "/bin/sh" ]
          args: [ "-c", "cp -R /opt/spark/* /spark/" ]
      {{- if .Values.skyWalking.enabled }}
        - name: agent-container
          image: apache/skywalking-java-agent:8.7.0-alpine
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 200Mi
          volumeMounts:
            - name: skywalking-agent
              mountPath: /agent
          command: [ "/bin/sh" ]
          args: [ "-c", "cp -R /skywalking/agent /agent/" ]
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository | default (printf "%s/query" .Values.global.image.registry) }}:{{ .Values.image.tag | default .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default .Values.global.image.pullPolicy }}
          env:
            - name: APP_NAME
              value: query
            - name: SPARK_CONF_DIR
              value: /opt/kyligence/spark/conf
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{- if .Values.skyWalking.enabled }}
            - name: SW_AGENT_NAME
              value: "{{ include "query.fullname" . }}"
            - name: SW_AGENT_NAMESPACE
              value: "{{ .Release.Namespace }}"
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "{{ .Values.skyWalking.backendServerAddr }}"
            {{- end }}
          envFrom:
            - configMapRef:
                name: kylin.init.yaml
          command:
            - sh
            - "-x"
            - "-c"
            - |
              {{- $skyWalking := "" -}}
              {{- if .Values.skyWalking.enabled }}
              {{- $skyWalking = "-s" }}
              {{- end }}
              {{- $javaDebug := "" -}}
              {{- if .Values.debug.enabled }}
              {{- $javaDebug = "-d"}}
              {{- end}}
              sh ${KYLIN_HOME}/sbin/yinglong-bootstrap.sh start {{ $skyWalking }} {{ $javaDebug }}
              tail -f
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: debug
              containerPort: {{ .Values.service.debugPort }}
              protocol: TCP
          livenessProbe:
            { { - toYaml .Values.livenessProbe | nindent 12 } }
          readinessProbe:
            { { - toYaml .Values.readinessProbe | nindent 12 } }
          startupProbe:
            { { - toYaml .Values.startupProbe | nindent 12 } }
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /opt/kyligence/conf/fairscheduler.xml
              name: newten-conf
              subPath: fairscheduler.xml
            - mountPath: /opt/kyligence/bin/check-env-bypass
              name: newten-conf
              readOnly: false
              subPath: check-env-bypass
            - mountPath: /opt/kyligence/hadoop_conf/core-site.xml
              name: yarn-xml
              subPath: core-site.xml
            - mountPath: /opt/kyligence/hadoop_conf/hive-site.xml
              name: yarn-xml
              subPath: hive-site.xml
            - mountPath: /opt/kyligence/hadoop_conf/hiveserver2-site.xml
              name: yarn-xml
              subPath: hive-site.xml
            - mountPath: /opt/kyligence/hadoop_conf/hivemetastore-site.xml
              name: yarn-xml
              subPath: hive-site.xml
            - mountPath: /opt/kyligence/conf/log4j2.xml
              name: newten-conf
              subPath: log4j2.xml
            - name: lib-ext
              mountPath: /opt/kyligence/lib/ext
            {{- if .Values.skyWalking.enabled }}
            - name: skywalking-agent
              mountPath: /skywalking
            {{- end }}
            - name: spark
              mountPath: /opt/kyligence/spark
            {{- if .Values.global.configcenter.disabled }}
            - mountPath: /opt/kyligence/conf/kylin.properties.override
              name: kylin-properties
              subPath: kylin.properties
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
