#!groovy

@Library('devopslib') _

pipeline {
    options {
        timeout(time: 2, unit: 'HOURS')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/yaml/jenkins-package-agent-aws.yaml'
        }
    }

    parameters {
        string(name: 'repo', defaultValue: 'Kyligence', description: 'Kap repo?')
        string(name: 'branch', defaultValue: 'newten-dev', description: 'Kap branch?')
        string(name: 'commitid', defaultValue: 'newten-dev', description: 'Kap branch?')
        string(name: 'version', defaultValue: '4.5.9', description: 'Kap version?')
        credentials(name: 'certificate', credentialType: 'com.cloudbees.plugins.credentials.common.StandardCredentials', defaultValue: 'kyligencegit', required: true)
    }

    stages {
        
        stage("Checkout Source Code") {
            steps {
                container("build") {
                    dir("sourcecode") {
                        script {
                             awsGithubCheckOut 'KAP'
                             sh """ 
                                 echo "------------------------------------------------"
                                     pwd
                                     ls -al
                                 echo "-------------------------------------------------"
                                """
                        }
                    }
                }
            }
        }

        stage('Building Package') {
            steps {
                container("build") {
                    dir("sourcecode") {
                       sh """#!/bin/bash
                                pwd
                                ls -al 
                                cd  kystudio
                                echo  -e  '\n------------------------------------------------------------'
                                cat .npmrc
                                sed -i s#http://10.1.2.111:4873#http://devops-nexus:8081/repository/kyligence-npm#g .npmrc
                                echo  -e  '\n------------------------------------------------------------'
                                cat .npmrc
                                echo '\n------------------------------------------------------------'
                                echo -e '\nemail=binbin.zou@kyligence.io' >> .npmrc
                                echo 'always-auth=true' >> .npmrc
                                echo '_auth=bnBtLWRldjpucG0tZGV2' >> .npmrc
                                cat .npmrc
                                echo  -e  '\n-----------------------------------------------------------'
                        """

                        buildNewten(params.version)
                        archiveArtifacts artifacts: 'dist/*.tar.gz', fingerprint: true, followSymlinks: false, onlyIfSuccessful: true
                        //def commitid = sh(returnStdout:true, script: "git rev-parse --short HEAD | sed -e 's/\r//g'").trim()
                        //    print commitid
                        //sh "ls -al dist/ && mkdir -p /var/cicd/artifacts/dev/newten &&  \
                        //cp dist/*.tar.gz /var/cicd/artifacts/dev/newten/${version}-`git rev-parse --short HEAD`-${BUILD_NUMBER}-.tar.gz"
                        
                      //--s3 上传方式 借用 焦恩伟的 s3上传代码 在https://github.com/Kyligence/devopslib/tree/master/vars/s3Archive.groovy
                      withAWS(region: 'us-west-2', credentials: 'aws_global_s3_cp') {
                            sh script: """
                                #!/bin/bash
                                echo -e '\n-------------------'
                                pwd
                                echo -e '\n-------------------'
                                ls -al dist/
                                echo -e '\n-------------------'
                                mv dist/*.tar.gz  KE-${version}-DEV-${BUILD_NUMBER}-`git rev-parse --short HEAD`.tar.gz
                                ls -al dist/
                             """
                       s3Upload(bucket: 'k8s-bucket-devops', path: "ke-cd/dev/newten/", includePathPattern: "*.tar.gz")
                       }
                    }
                }
            }
        }
    }
}
