apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nacos.fullname" .}}-config-cm
data:
  MYSQL_SERVICE_HOST: {{ .Values.global.mysql.host | default .Values.config.mysql.host }}
  MYSQL_SERVICE_DB_NAME: {{ .Values.mysql.db | default .Values.config.mysql.db }}
  MYSQL_SERVICE_PORT: "{{ .Values.global.mysql.port | default .Values.config.mysql.port }}"
  MYSQL_SERVICE_DB_PARAM: {{ .Values.mysql.param | default "characterEncoding=utf8&connectTimeout=10000&socketTimeout=10000&autoReconnect=true&useSSL=false" }}