#!groovy

@Library('devopslib') _

pipeline {
    options {
        timeout(time: 2, unit: 'HOURS')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/yaml/jenkins-agent.yaml'
        }
    }

    parameters {
        string(name: 'repo', defaultValue: '', description: 'Kap repo?')
        string(name: 'branch', defaultValue: '', description: 'Kap branch?')
        credentials(name: 'certificate', credentialType: 'com.cloudbees.plugins.credentials.common.StandardCredentials', defaultValue: 'kyligencegit', required: true)
    }

    stages {
        stage("Checkout Source Code") {
            steps {
                container("git") {
                    dir("sourcecode") {
                        script {
                            retry(3) {
                                githubCheckout 'KAP', null, 'https', 'github.com', '+refs/pull/*:refs/remotes/origin/pr/* +refs/heads/*:refs/remotes/origin/*'
                            }
                        }
                    }
                }
            }
        }
        stage('Maven Install') {
            steps {
                container("maven") {
                    dir("sourcecode") {
                        sh script: """
                            mvn -U clean install -T 2C -Dmaven.compile.fork=true -DskipTests
                        """
                    }
                }
            }
        }
        stage('Testing') {
            steps {
                simpleNewtenParallelTest2()
            }
            post {
                always {
                    timestamps {
                        junit skipPublishingChecks: true, testResults: '*Test-Stage-*/**/target/surefire-reports/*.xml'
                    }
                }
            }
        }
        stage('SonarCloud') {
            steps {
                container("sonar-cloud") {
                    dir("sourcecode") {
                        withSonarQubeEnv(credentialsId: 'sonar_credential', installationName: 'sonar cloud') {
                            // You can override the credential to be used
                            sh script: """
                                mvn sonar:sonar -T 4C \
                                -Dsonar.pullrequest.base=${ghprbTargetBranch} \
                                -Dsonar.pullrequest.branch=${ghprbSourceBranch} \
                                -Dsonar.pullrequest.key=${ghprbPullId} \
                                -Dsonar.projectKey=Kyligence_KAP \
                                -Dsonar.organization=kyligence \
                                -Dsonar.host.url=https://sonarcloud.io \
                                -Dsonar.coverage.jacoco.xmlReportPaths=${WORKSPACE}/*Test-Stage-*/**/*jacoco.xml
                            """
                        }
                    }
                }
            }
        }
    }
}
