{
 "title": "Spark Application2",
 "time": { "from": "2022-10-24T08:20:00.000Z", "to": "2022-10-24T09:59:59.000Z" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "application_name",
    "label": "Application Name",
    "query": {
     "query": "label_values(spark_executor_totalDuration_seconds_total{}, application_name)"
    }
   },
   {
    "name": "application_id",
    "label": "Application ID",
    "query": {
     "query": "label_values(spark_executor_totalDuration_seconds_total{}, application_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Executors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  count(spark_executor_memoryUsed_bytes{ executor_id!=\"driver\", application_id=\"$application_id\"})\n  by ( executor_id, application_id,  application_name))\nby ( application_id, application_name)",
     "legendFormat": "app={{application_name}} executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Executor Storage Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spark_executor_memoryUsed_bytes{executor_id!=\"driver\", application_id=\"$application_id\"}) by (application_id)\n/\nsum(spark_executor_maxMemory_bytes{executor_id!=\"driver\", application_id=\"$application_id\"}) by (application_id)"
    }
   ]
  },
  {
   "title": "Driver Storage Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(spark_executor_memoryUsed_bytes{executor_id=\"driver\", application_id=\"$application_id\"}) by (application_id)\n/ \nmax(spark_executor_maxMemory_bytes{executor_id=\"driver\", application_id=\"$application_id\"}) by (application_id)"
    }
   ]
  },
  {
   "title": "Max Executor GC time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(rate(spark_executor_totalGCTime_seconds_total{ application_id=\"$application_id\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total GC time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spark_executor_totalGCTime_seconds_total{application_id=\"$application_id\"})"
    }
   ]
  },
  {
   "title": "Max Tasks on Executor",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(spark_executor_activeTasks{ application_id=\"$application_id\"})",
     "legendFormat": "app={{application_name}} executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Total Failed Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(spark_executor_failedTasks_total{ executor_id!=\"driver\"})",
     "legendFormat": "app={{application_name}} executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Total Completed Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(spark_executor_completedTasks_total{ executor_id!=\"driver\", application_id=\"$application_id\"})"
    }
   ]
  },
  {
   "title": "Total Running Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(spark_executor_activeTasks{ executor_id!=\"driver\", application_id=\"$application_id\"})"
    }
   ]
  },
  {
   "title": "Total Pending Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(spark_executor_completedTasks_total{ executor_id!=\"driver\", application_id=\"$application_id\"})"
    }
   ]
  },
  {
   "title": "Active Jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "spark_driver_DAGScheduler_job_activeJobs{ app_id=\"$application_id\"}"
    }
   ]
  },
  {
   "title": "All Jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(spark_driver_DAGScheduler_job_allJobs{ app_id=\"$application_id\"})"
    }
   ]
  },
  {
   "title": "Failed Stages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "spark_driver_DAGScheduler_stage_failedStages{ app_id=\"$application_id\"}"
    }
   ]
  },
  {
   "title": "Running Stages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(spark_driver_DAGScheduler_stage_runningStages{  app_id=\"$application_id\"})"
    }
   ]
  },
  {
   "title": "Waiting Stages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(spark_driver_DAGScheduler_stage_waitingStages{  app_id=\"$application_id\"})"
    }
   ]
  },
  {
   "title": "Total Completed Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(spark_executor_completedTasks_total{ executor_id!=\"driver\", application_id=\"$application_id\"})"
    }
   ]
  },
  {
   "title": "Executors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Application Executors Current Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max_over_time(\r\n  max(spark_executor_totalDuration_seconds_total{ application_id=\"$application_id\"})\r\n  by (kubernetes_pod_name,application_id,application_name, executor_id)[$__range:1m]\r\n)"
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Tasks Time per Executor",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(spark_executor_totalDuration_seconds_total{ application_id=\"$application_id\"}) by (executor_id)",
     "legendFormat": "{{executor_id}}"
    }
   ]
  },
  {
   "title": "Executor Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "spark_executor_memoryUsed_bytes{ application_id=\"$application_id\"}",
     "legendFormat": "[{{name}}] executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Total Duration / Seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(spark_executor_totalDuration_seconds_total{application_id=\"$application_id\", executor_id!=\"driver\"}[2m])) \nby ( application_name)",
     "legendFormat": "[{{name}}]"
    }
   ]
  },
  {
   "title": "Active Tasks per Executor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_executor_activeTasks{application_id=\"$application_id\"}",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Executor GC time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(spark_executor_totalGCTime_seconds_total{ application_id=\"$application_id\"}[1m])",
     "legendFormat": "app={{application_name}} executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Executor GC time / Total time Percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(spark_executor_totalGCTime_seconds_total { application_id=\"$application_id\"}[2m])\n/\nrate(spark_executor_totalDuration_seconds_total{ application_id=\"$application_id\"}[2m])",
     "legendFormat": "app={{application_name}} executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Shuffle Bytes Read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(spark_executor_totalShuffleRead_bytes_total{ application_id=\"$application_id\"}[5m])",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Shuffle Bytes Written",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(spark_executor_totalShuffleWrite_bytes_total{application_id=\"$application_id\"}[5m])",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Records Read Counts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  sum(\n  rate(spark_executor_recordsRead_total{app_id=\"$application_id\"}[2m])) \nby ( spark_app_name)",
     "legendFormat": "app: {{spark_app_name}}/{{app_id}}"
    }
   ]
  },
  {
   "title": "Records Write Counts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  sum(\n  rate(spark_executor_recordsWritten_total{app_id=\"$application_id\"}[2m])) \nby ( spark_app_name,app_id)",
     "legendFormat": "app: {{spark_app_name}}/{{app_id}}"
    }
   ]
  },
  {
   "title": "Total Input Bytes/Seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(spark_executor_totalInputBytes_bytes_total{application_id=\"$application_id\"}[5m])",
     "legendFormat": "executor={{executor_id}}"
    }
   ]
  },
  {
   "title": "Total Shuffle IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(spark_executor_totalShuffleWrite_bytes_total{ application_id=\"$application_id\"}[5m]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(spark_executor_totalShuffleRead_bytes_total{application_id=\"$application_id\"}[5m]))",
     "legendFormat": "Read"
    }
   ]
  }
 ]
}