apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "yl-log.fullname" . }}-backup-cronjob
  labels:
  {{- include "yl-log.labels" . | nindent 4 }}
spec:
  jobTemplate:
    spec:
      template:
        spec:
          {{- if .Values.imagePullSecrets }}
          imagePullSecrets:
            - name: {{ .Values.imagePullSecrets }}
          {{- end }}
          containers:
          - args:
            - -config.file=/etc/config/config.yaml
            env:
            - name: ACCESSKEYID
              valueFrom:
                secretKeyRef:
                  key: AccessKeyID
                  name: {{ include "yl-log.fullname" . }}-backup-secret
                  optional: true
            - name: ACCESSKEY
              valueFrom:
                secretKeyRef:
                  key: AccessKey
                  name: {{ include "yl-log.fullname" . }}-backup-secret
                  optional: true
            image: "{{ .Values.backup.backup.image.registry | default .Values.global.image.registry }}/{{ .Values.backup.backup.image.repository }}:{{ .Values.backup.backup.image.tag |default .Values.global.image.logTag}}"
            imagePullPolicy: {{ .Values.api.api.image.imagePullPolicy | default "Always" | quote }}
            name: backup
            volumeMounts:
            - mountPath: /etc/config
              name: config
          restartPolicy: OnFailure
          volumes:
          - configMap:
              defaultMode: 420
              name: {{ include "yl-log.fullname" . }}-backup-config
            name: config
  schedule: 0 */1 * * *