apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "yl-log.fullname" . }}-api
  labels:
    app: log
    component: api
  {{- include "yl-log.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: log
      component: api
    {{- include "yl-log.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: log
        component: api
      {{- include "yl-log.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      containers:
      - args:
        - -config.file=/etc/config/config.yaml
        - -config.backup=/etc/backup/config.yaml
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        image: "{{ .Values.api.api.image.registry | default .Values.global.image.registry }}/{{ .Values.api.api.image.repository }}:{{ .Values.api.api.image.tag |default .Values.global.image.logTag}}"
        imagePullPolicy: {{ .Values.api.api.image.imagePullPolicy | default "Always" | quote }}
        name: api
        resources: {{- toYaml .Values.api.api.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /etc/config
          name: config
        - mountPath: /etc/backup
          name: configbackup
      volumes:
      - configMap:
          defaultMode: 420
          name: {{ include "yl-log.fullname" . }}-api-config
        name: config
      - configMap:
          defaultMode: 420
          name: {{ include "yl-log.fullname" . }}-backup-config
        name: configbackup