apiVersion: v1
kind: Service
metadata:
  name: yarn-historyserver
  namespace: <<<namespace>>>
spec:
  ports:
    - name: "8188"
      port: 8188
      targetPort: 8188
  selector:
    io.kompose.service: yarn-historyserver
