#!groovy

@Library('devopslib') _

pipeline {
    options {
        timeout(time: 1, unit: 'HOURS')
    }

    // agent {
    //     kubernetes {
    //         yamlFile 'pipelines/yaml/jenkins-agent.yaml'
    //     }
    // }

    agent any

    parameters {
        string(name: 'branch', defaultValue: 'newten-qa', description: 'Kap branch?')
        string(name: 'repo', defaultValue: 'Kyligence', description: 'Kap repo?')
        string(name: 'version', defaultValue: 'newten-qa', description: 'Kap version?')
        credentials(name: 'certificate', credentialType: 'com.cloudbees.plugins.credentials.common.StandardCredentials', defaultValue: 'kyligence-git', required: true)
    }

    stages {
        stage("Checkout Source Code") {
            steps {
                script {
                    sh('install.sh --package_file=/data/jenkins-common/newten-cicd/artifacts/dev/NEWTEN-QA-INPUT-ID-CD/newten-qa-newten-qa-5.tar.gz --namespace=test-1')
                }
            }
        }
        stage('Building Package') {
            steps {
                echo 'nothing'
            }
        }
    }
}
