#!groovy

@Library('devopslib') _

pipeline {
    options {
        timeout(time: 1, unit: 'HOURS')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/Newten-CD/jenkins-agent.yaml'
        }
    }

    parameters {
        string(name: 'version', defaultValue: '4.5.x_Beta', description: 'Kap version?')
        string(name: 'repo', defaultValue: 'Kyligence', description: 'Kap repo?')
        string(name: 'branch', defaultValue: 'newten-qa', description: 'Kap branch?')
        credentials(name: 'certificate', credentialType: 'com.cloudbees.plugins.credentials.common.StandardCredentials', defaultValue: 'kyligence-git', required: true)
    }

    stages {
        stage("Checkout Source Code") {
            steps {
                container("git") {
                    dir("sourcecode") {
                        script {
                            retry(3) {
                                githubCheckout 'KAP'
                            }

                            //
                            if (params.branch ==~ /yinglong/ ) {
                                echo 'checkout KAP_Frontend to kystudio'
                                deleteDir 'kystudio'
                                dir('kystudio') {
                                    retry(3) {
                                        githubCheckout 'KAP_Frontend', 'newten', 'https', 'github.com', '+refs/heads/*:refs/remotes/origin/*'
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        stage('Building Package') {
            steps {
                container("build") {
                    dir("sourcecode") {
                        buildNewten(params.version)
                        archiveArtifacts artifacts: 'dist/*.tar.gz', fingerprint: true, followSymlinks: false, onlyIfSuccessful: true
                        sh "mkdir -p /var/cicd/artifacts/dev/${BUILD_NUMBER} && \
                            cp dist/*.tar.gz /var/cicd/artifacts/dev/Kyligence-Enterprise-${version}.${BUILD_NUMBER}.tar.gz"
                    }
                }
            }
        }
        stage('Starting Newten') {
            steps {
                warnError(catchInterruptions: false, message: 'Start Newten failed...') {
                    script {
                        r = build propagate: false, job: 'Newten-Starter', parameters: [string(name: 'package_version', value: "${params.version}"), string(name: 'run_env', value: 'dev')]
                        if(r.result != 'SUCCESS'){
                            sh 'exit 1'
                        }
                    }
                }
            }
        }
    }
}