apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nacos.fullname" . }}-naming-secret
  labels:
    {{- include "nacos.labels" . | nindent 4 }}
type: Opaque
data:
  MYSQL_SERVICE_USER: {{ .Values.global.mysql.user | b64enc }}
  MYSQL_SERVICE_PASSWORD: {{ .Values.global.mysql.password | b64enc }}