apiVersion: v1
kind: Service
metadata:
  name: {{ include "nacos.fullname" . }}-naming-headless
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  ports:
    - name: server
      port: {{ .Values.naming.service.port }}
      protocol: TCP
      targetPort: {{ .Values.naming.service.port }}
    - name: client-rpc
      port: {{ .Values.naming.service.port | int | add 1000 }}
      protocol: TCP
      targetPort: {{ .Values.naming.service.port | int | add 1000 }}
    - name: raft-rpc
      port: {{ .Values.naming.service.port | int | add 1001 }}
      protocol: TCP
      targetPort: {{ .Values.naming.service.port | int | add 1001 }}
    - name: old-raft-rpc
      port: {{ .Values.naming.service.port | int | add -1000 }}
      protocol: TCP
      targetPort: {{ .Values.naming.service.port | int | add -1000 }}
  selector:
    {{- include "nacos.selectorLabels" . | nindent 4 }}
    app: {{ include "nacos.fullname" . }}-naming
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nacos.fullname" . }}-naming-svc
  labels:
    {{- include "nacos.labels" . | nindent 4 }}
    app: {{ include "nacos.fullname" . }}-naming
spec:
  type: {{ .Values.naming.service.type }}
  ports:
    - name: server
      port: {{ .Values.naming.service.port }}
      protocol: TCP
      targetPort: {{ .Values.naming.service.port }}
    - name: client-rpc
      port: {{ .Values.naming.service.port | int | add 1000 }}
      protocol: TCP
      targetPort: {{ .Values.naming.service.port | int | add 1000 }}
    - name: raft-rpc
      port: {{ .Values.naming.service.port | int | add 1001 }}
      protocol: TCP
      targetPort: {{ .Values.naming.service.port | int | add 1001 }}
    - name: old-raft-rpc
      port: {{ .Values.naming.service.port | int | add -1000 }}
      protocol: TCP
      targetPort: {{ .Values.naming.service.port | int | add -1000 }}
  selector:
    {{- include "nacos.selectorLabels" . | nindent 4 }}
    app: {{ include "nacos.fullname" . }}-naming