#!groovy

@Library('devopslib@quard-auto') _

import hudson.model.*;
import jenkins.model.*;

properties([
    parameters([
        [
            $class: 'ChoiceParameter',
            name: 'regtype',
            choiceType: 'PT_SINGLE_SELECT',
            filterable: false,
            script:
            [
                $class: 'GroovyScript',
                script:
                [
                    classpath: [],
                    sandbox: true,
                    script:
                    """
                    return ["ga", "sp", "daily", "other"]
                    """
                ],
                fallbackScript:
                [
                    classpath: [],
                    sandbox: false,
                    script: ''
                ],
            ]
        ],
        string(name: 'kc_version',       defaultValue: '4.5.21',                                                                               description: "KC版本号"),
        string(name: 'ke_version',       defaultValue: '4.6.1.0',                                                                              description: "KE版本号"),
        string(name: 'ke_job_url',       defaultValue: '',                                                                                     description: "当提供ke包的job_id时, 可以加速构建过程(省去1个小时的打包时间). \n https://cicd-ofs.kyligence.com/job/KE4/view/正式交付/job/KE-All-CD-2.0/1360/"),
        string(name: 'upgrade_package',  defaultValue: 's3://download.kyligence.io/product/kap/4.0.x/Kyligence-Enterprise-4.5.19.0-GA.tar.gz', description: "升级回滚包路径(最小跨度), 下面列出最常用的版本\ns3://download.kyligence.io/product/kap/4.0.x/Kyligence-Enterprise-4.5.1.3081-GA.tar.gz\ns3://download.kyligence.io/product/kap/4.0.x/Kyligence-Enterprise-4.5.17.0-GA.tar.gz"),
        string(name: 'spark_file',       defaultValue: 'spark-newten-3.2.0-4.6.1.0-cloud-hadoop3.tgz',                                         description: "Spark的包，存放在S3的kyligence-ci/packages/spark-cloud下."),
        string(name: 'notify',           defaultValue: 'tong.zheng@kyligence.io',                                                              description: "结果通知, 可填写两个不同类型的值. \n - 个人账号: tong.zheng@kyligence.io \n - 飞书群的webhook地址: https://open.feishu.cn/open-apis/bot/v2/hook/xxxxxxxx-826d-48fd-9c81-xxxxxxxxxxxx \n - 卡片通知: 填写群名称(需要先邀请Quard机器人入群)")
    ])
])

pipeline {

    // 日报流程

    // TODO:
    // 1. aws 自动生成 kyligence_cloud_aws_3_0_quard.json 文件.
    // 2. aws 和 azure 自动回收环境.
    // 3. 报告写feishu文档
    // 4. 跑完之后启动切分支出来

    options {
        timestamps()
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/yaml/jenkins-quard-agent.yaml'
        }
    }

    environment{
        githubrepo="zhengtong0898"
        githubbranch="quard-4.x-dev"
        githubtoken="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"

        quard_jenkins_server="http://10.1.2.38:8080"
        quard_jenkins_username="quard"
        quard_jenkins_token="11d3a455b9af7fce8ad4f84265bb926295"

        feishu_app_id="cli_a384621def7c100c"
        feishu_app_secret="pN2wI1O9fRnvUBkbkBt6Tf8iudbkVnCP"
    }

    stages {
        stage("Pull Code") {
            steps {
                container('build') {
                    dir('sourcecode') {
                        script {
                            echo 'checkout kyQA-Quard'
                            retry(3) {
                                pullCodeFromGitMirror 'kyQA-Quard', env.githubbranch, false
                            }
                        }
                    }
                }
            }
        }
        stage("Install") {
            steps {
                container('python3') {
                    dir('sourcecode') {
                        script {
                            // sh 'ls -lh /mnt/jenkins'
                            sh 'ls -lh'
                            sh 'pip install -r ./requirements.txt --no-index'
                        }
                    }
                }
            }
        }
    }
}