apiVersion: apps/v1
kind: Deployment
metadata:
  name: yinglong-query-{{ .Release.Namespace }}
  labels:
    {{- include "yinglong.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "yinglong.selectorLabels" . | nindent 6 }}
      app: yinglong-query-{{ .Release.Namespace }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "yinglong.selectorLabels" . | nindent 8 }}
        app: yinglong-query-{{ .Release.Namespace }}
    spec:
      volumes:
        - name: newten-conf
          configMap:
            name: yinglong-config-{{ .Release.Namespace }}
            defaultMode: 511
        - configMap:
            name: {{ .Values.hadoopPrefix }}-yarn-xml
          name: yarn-xml
      containers:
        - name: yinglong-query-{{ .Release.Namespace }}
          image: 10.1.9.200:5000/kyligence/yinglong-query
          env:
            - name: KYLIN_HOME
              value: /opt/kyligence
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command:
            - sh
            - "-c"
            - |
              echo "$(POD_IP)"
              touch /opt/kyligence/conf/kylin.properties.override
              echo "kylin.storage.columnar.spark-conf.spark.driver.host=$(POD_IP)" >> /opt/kyligence/conf/kylin.properties.override
              echo "kylin.engine.spark-conf.spark.driver.host=$(POD_IP)" >> /opt/kyligence/conf/kylin.properties.override
              echo "kylin.env.channel=cloud" >> /opt/kyligence/conf/kylin.properties.override
              echo "spring.cloud.nacos.server-addr={{ .Values.nacos.serverAddr }}"  >> /opt/kyligence/conf/kylin.properties.override
              echo "spring.cloud.nacos.discovery.server-addr={{ .Values.nacos.serverAddr }}" >> /opt/kyligence/conf/kylin.properties.override
              echo "spring.cloud.nacos.discovery.group={{ .Release.Namespace }}"  >> /opt/kyligence/conf/kylin.properties.override
              echo "spring.session.store-type=jdbc"  >> /opt/kyligence/conf/kylin.properties.override
              bash $(KYLIN_HOME)/bin/kylin.sh start
              if [ -f $KYLIN_HOME/logs/kylin.log ]
              then
                tail -300f $KYLIN_HOME/logs/kylin.log
              else
                tail -300f $KYLIN_HOME/logs/shell.stderr
              fi
          resources:
            limits:
              cpu: '2'
              memory: 2Gi
            requests:
              cpu: '2'
              memory: 2Gi
          volumeMounts:
            - mountPath: /opt/kyligence/conf/kylin.properties
              name: newten-conf
              subPath: kylin.properties
            - mountPath: /opt/kyligence/conf/fairscheduler.xml
              name: newten-conf
              subPath: fairscheduler.xml
            - mountPath: /opt/kyligence/bin/check-env-bypass
              name: newten-conf
              readOnly: false
              subPath: check-env-bypass
            - mountPath: /opt/kyligence/hadoop_conf/core-site.xml
              name: yarn-xml
              subPath: core-site.xml
            - mountPath: /opt/kyligence/hadoop_conf/hive-site.xml
              name: yarn-xml
              subPath: hive-site.xml
            - mountPath: /opt/kyligence/hadoop_conf/hiveserver2-site.xml
              name: yarn-xml
              subPath: hive-site.xml
            - mountPath: /opt/kyligence/hadoop_conf/hivemetastore-site.xml
              name: yarn-xml
              subPath: hive-site.xml
            - mountPath: /opt/kyligence/hadoop_conf/hdfs-site.xml
              name: yarn-xml
              subPath: hdfs-site.xml
            - mountPath: /opt/kyligence/hadoop_conf/yarn-site.xml
              name: yarn-xml
              subPath: yarn-site.xml
            - mountPath: /opt/kyligence/hadoop_conf/fair-scheduler.xml
              name: yarn-xml
              subPath: fair-scheduler.xml
            - mountPath: /etc/hadoop/conf/core-site.xml
              name: yarn-xml
              subPath: core-site.xml
            - mountPath: /etc/hadoop/conf/hdfs-site.xml
              name: yarn-xml
              subPath: hdfs-site.xml
            - mountPath: /etc/hadoop/conf/yarn-site.xml
              name: yarn-xml
              subPath: yarn-site.xml
            - mountPath: /etc/hive/conf/hive-site.xml
              name: yarn-xml
              subPath: hive-site.xml
            - mountPath: /etc/hadoop/conf/fair-scheduler.xml
              name: yarn-xml
              subPath: fair-scheduler.xml

