apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hdfs.fullname" . }}-jmx-exporter-config
data:
  config.yaml: |
    ssl: false
    lowercaseOutputName: false
    lowercaseOutputLabelNames: false