apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-claim
  # namespace: nfs
spec:
  storageClassName: nfs-dynamic
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi