# Default values for yinglong.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  hadoopPrefix: hadoop
  hdfs: {}
    # workingDir: 

  metadata:
    url: "*****"
  nacos:
    config:
      serverAddrNoHttp: nacos-config-svc.yinglong-middle-qa:8848
    discovery:
      serverAddrNoHttp: nacos-naming-svc.yinglong-middle-qa:8848
    # serverAddr:
  
  tenantId: "103074753383407618"
  publicGroup: "xuanwu-system"

  zookeeper: {}
    # address: localhost:2181
  tz: "Asia/Shanghai"

  configcenter:
    disabled: false

yinglong-common:
  image:
    tag: yl-5.0.10
  fullnameOverride: yinglong-common-with-a-very-long-name
  serviceAccount:
    name: spark-abc

yinglong-data-loading:
  image:
    tag: yl-5.0.10
  fullnameOverride: yinglong-data-loading-with-a-very-long-name

yinglong-query:
  image:
    tag: yl-5.0.10
  fullnameOverride: yinglong-query-with-a-very-long-name

yinglong-smart:
  image:
    tag: yl-5.0.10

yinglong-frontend:
  image:
    tag: yl-5.0.10
  gateway:
    serverAddr: gateway:8080
  iam:
    serverAddr: https://iam-qa.dev.kyligence.com/
  config:
    serverAddr: https://nacos-qa.dev.kyligence.com/

gateway:
  image:
    tag: "5.0.1-private"
  fullnameOverride: gateway
  config: # must same with middle ware
    redis:
      host: redis-master.yinglong.svc.cluster.local
      database: 3
      password: "******"
