# Default values for yinglong.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
monitor:
  enabled: false
log:
  enabled: true
global:
  hadoopPrefix: hadoop
  hdfs: {}
    # workingDir: 

  image:
    registry: harbor-ofs.kyligence.com/enterprise
    tag: "latest"
    pullPolicy: IfNotPresent
    logTag: "latest"

  metadata:
    url: "*****" # yinglong所在的mysql的URL地址, (用户名和密码在参数上)
  nacos:
    config:
      serverAddrNoHttp: nacos-config-svc.yinglong:8848
    discovery:
      serverAddrNoHttp: nacos-naming-svc.yinglong:8848
    # serverAddr:
  
  tenantId: "9223372036854775707" # 部署一个yinglong-release需要的租户ID
  publicGroup: ""   # 租户中心在nacos-naming中的组

  zookeeper: {}
    # address: localhost:2181
  tz: "Asia/Shanghai"        # 部署yinglong的时区, 必须考虑实际情况.

  configcenter:
    disabled: false         # 使用非配置中心版本的yinglong (beta) 为xuanwu-offering 10月演示特殊设置.

  spark:
    image:
      repository: harbor-ofs.kyligence.com/yinglong/yinglong-spark
      tag: latest
      pullPolicy:

  sparkPod:
    image:
      repository: repo-ofs.kyligence.com/spark
      tag: 3.3.0-kylin-4.5.17.0-SNAPSHOT
    uploadPath: s3a://yinglong-dep

  s3:
    endpoint: http://10.1.9.101:7480
    ak: WAXC3I4MY90TH6OR7NFL
    sk: VJ0CBjdMCqVu2kXVxx0m5ioqOJ04yGtgqZBumakq
    bucket: yinglong
  metastore:
    uris: hadoop-hive-metastore.yinglong:9083

frontend:
  image:
    tag: "latest"
#   iam:
#     serverAddr: https://iam.dev.kyligence.com/   # 租户中心的访问地址.
#   config:
#     serverAddr: https://nacos.dev.kyligence.com/   # 配置中心的访问地址.
#   ingress:
#     hosts:
#       - host: dev.kyligence.com  # yinglong 最终的访问地址是 https://{helm-release-name}.{k8s-namespace}.{host}/
#         paths:
#           - path: /
#             pathType: ImplementationSpecific

# gateway:
#   image:
#     repository: repo-ofs.kyligence.com/gateway
#     tag: "repo-ofs.kyligence.com/gateway:5.1.2-DEV-03e40ed"
#   config: # redis参数必须和租户中心的gateway所使用的redis一致.
#     redis:
#       host: redis-master.yinglong.svc.cluster.local
#       database: 6
#       password: "******"
