#!groovy

@Library('devopslib') _

// git获取spark 代码（预先触发同步git mirror）
def gitSparkCodeKe(repo, branch) {
    script {
        if (repo == 'Kyligence') {
            pullCodeFromGitMirror 'spark', branch
        } else {
            githubCheckout 'spark', branch, 'https', 'github.com', '+refs/heads/*:refs/remotes/origin/*', 'kyligence-git', repo
        }
    }

}

def hadoopParam = 'hadoop-3'
def dependencyTarName = 'spark-image-dependencies-hadoop3'

pipeline {
    options {
        timeout(time: 4, unit: 'HOURS')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/yaml/jenkins-docker-package-agent.yaml'
        }
    }

    environment {
        repo = 'harbor-ofs.kyligence.com'
        dockerRegistryUrl = "http://${repo}"
        registryCredential = 'harbor-docker'
    }

    parameters {
        string(name: 'repo', defaultValue: 'Kyligence', description: 'spark repo  https://github.com/Kyligence/spark.git--> Kyligence\nhttps://github.com/apache/spark.git--> apache')
        string(name: 'branch', defaultValue: 'kyspark-3.3.x-4.x', description: 'spark branch  \n kyspark-2.4.1.x-4.x \n kyspark-3.2.x-4.x ')
        string(name: 'imageRepo', defaultValue: 'harbor-ofs.kyligence.com/spark', description: 'docker image repo')
        string(name: 'version', defaultValue: '', description: 'eg 3.3.0-kylin-4.5.17.0 spark version and docker tag name')
        choice(name: 'hadoopVersion', choices: 'hadoop3\nhadoop2\nhadoop3-with-glue', description: 'hadoop的版本:hadoop2+aws2.10/hadoop3+hadoop-aws-3.2.2/hadoop3+hadoop-aws-3.2.2+glue')
        choice(name: 'arch', choices: ['linux/amd64', 'linux/arm64','linux/amd64,linux/arm64'], description: '选择spark镜像的linux架构，默认为 linux/amd64')
    }


    stages {
        stage("Checkout Source Code") {
            steps {
                container("build") {
                    dir("sourcecode") {
                        gitSparkCodeKe(params.repo, params.branch)
                    }
                }
            }
        }
        stage('package') {
            steps {
                container('build') {
                    dir('sourcecode') {
                        script {
                            if (params.hadoopVersion == 'hadoop2') {
                                hadoopParam = 'hadoop-2.10,hadoop2-aws'
                                dependencyTarName = "spark-image-dependencies-hadoop2"
                            }
                            if (params.hadoopVersion == 'hadoop3-with-glue') {
                                dependencyTarName = "spark-image-dependencies-hadoop3-with-glue"
                            }
                            sh script: """
                                ./build/mvn versions:set -DnewVersion=${params.version}
                                ./build/mvn -Pkubernetes,volcano,${hadoopParam},scala-2.12,hive  -DskipTests clean package    
                                wget https://repo-ofs.kyligence.com/repository/raw-public/io.kyligence.spark/spark-image-dependency/${dependencyTarName}.tar.gz
                                tar -zxvf ${dependencyTarName}.tar.gz
                                cp ${dependencyTarName}/*.jar assembly/target/scala-2.12/jars/
                                wget https://s3.cn-north-1.amazonaws.com.cn/download-resource/kyspark/hive_1_2_2.tar.gz
                                tar -zxvf hive_1_2_2.tar.gz
                                pwd
                                ls
                            """
                        }
                    }
                }
            }
        }

        stage('image') {
            steps {
                container('docker') {
                    dir('sourcecode') {
                        script {
                            docker.withRegistry(dockerRegistryUrl, registryCredential) {
                                sh script: """
                                export DOCKER_CLI_EXPERIMENTAL=enabled
                                docker buildx create --name yinglongMultiarchBuilder && docker buildx use yinglongMultiarchBuilder || true
                                ARCHS="--platform  ${params.arch}" ./bin/docker-image-tool.sh -X -r ${params.imageRepo} -t ${params.version} build
                                """
                            }
                        }
                    }
                }
            }
        }
    }
}