apiVersion: v1
kind: Service
metadata:
  name: yarn-nodemanager
  namespace: <<<namespace>>>
spec:
  clusterIP: None
  ports:
    - name: "8042"
      port: 8042
      targetPort: 8042
  selector:
    io.kompose.service: yarn-nodemanager
