@Library('devopslib') _
pipeline { 
    agent any 
    
    stages {
        stage('Example'){
            steps {
                pullCodeFromGitMirror 'KAP', 'newten'
            }
        }
    }
}
