#!groovy

@Library('devopslib') _

import groovy.json.*
import hudson.model.*

// GA包名
def ga_name = ''
// 发布分支(前端)
def release_branch_front = ''
// 发布分支(后端)
def release_branch_back = ''

def release_commitid_front = ''
def release_commitid_back = ''
// 包存在
def exist_package = false
// 包信息对象
def package_info =  [:]

// 根据发布类型自动获取分支
def getBranch(deployType, envStage, version) {
    print "getBranch -> deployType[${deployType}],envStage[${envStage}],version[${version}]"
    def _result
    def _branch_release = ''
    def _branch_qa = ''
    def _branch_dev = ''
    def branchCollection = ['newten', 'ke-4.5.x-sp', 'ke-4.3.x', 'ke-4.3.x-sp']

    switch (deployType) {
        case 'Regular':
            _branch_release = branchCollection[0]
            _branch_qa = "ke-${version}-qa"
            _branch_dev = "${_branch_release}-dev"
            break
        case 'SP-4.5.x':
            _branch_release = branchCollection[0]
            _branch_qa = "${branchCollection[1]}-dev"
            _branch_dev = "${branchCollection[1]}-dev"
            break
        case 'KE-4.3.x':
            _branch_release = branchCollection[2]
            _branch_qa = "ke-${version}-qa"
            _branch_dev = "${branchCollection[1]}-dev"
            break
        case 'SP-4.3.x':
            _branch_release = branchCollection[3]
            _branch_qa = "${_branch_release}-dev"
            _branch_dev = "${_branch_release}-dev"
            break
    }

    switch (envStage) {
        case 'DEV':
            _result = _branch_dev
            break
        case 'QA':
            _result = _branch_qa
            break
        case 'RC':
        case 'GA':
            _result = _branch_release
            break
    }
    echo "getBranch: ${_result}"
    return _result
}

// 上传制品包到Aws S3存储
def uploadAwsS3(region, credentials, bucket, path, ga_name) {
    dir('sourcecode') {
        timestamps {
            println("uploadAwsS3 -> path: ${path}, ga_name: ${ga_name}")
            withAWS(region: region, credentials: credentials) {
                s3Upload(bucket: bucket, path: path, file: ga_name)
            }
        }
    }
}

// 上传制品包到Nexus制品库
def uploadNexus(repo, package_path, file_name) {
    timestamps {
        container('build') {
            dir('sourcecode') {
                script {
                    println("repo: ${repo}, package_path: ${package_path}, file_name: ${file_name}")
                    // 上传制品库
                    withCredentials([usernamePassword(credentialsId: 'nexus-raw', passwordVariable: 'passwd', usernameVariable: 'user')]) {
                        pushRawArtifactsByApi(repo, package_path, file_name, file_name, user, passwd)
                    }
                }
            }
        }
    }
}

def uplaodAzure(package_info,remote_path='/home/4xuser/data/devops') {
    script {
        def remote = [:]
        remote.name = 'azure_test_env'
        withCredentials([usernamePassword(credentialsId: 'azure-4xuser',
                usernameVariable: 'REMOTE_USERNAME',
                passwordVariable: 'REMOTE_PASSWORD')]) {
            remote.user = REMOTE_USERNAME
            remote.password = REMOTE_PASSWORD
        }
        remote.host = '159.27.120.141'
        remote.allowAnyHosts = true
        dir('sourcecode') {
            sshPut remote: remote, from: package_info.file_name, into: remote_path
        }
        sshCommand remote: remote, command: """
            ls -lh ${remote_path}
        """
    }
}

// git获取KE代码（预先触发同步git mirror）
def gitCodeKe(back, front) {
    def result = [:]
    container('build') {
        dir('sourcecode') {
            script {
                println "backend branch/commit: ${back}, frontend branch/commit: ${front}"
                if (!back) {
                    error 'commitId_back 参数不能为空'
                }
                pullCodeFromGitMirror 'KAP', back

                release_commitid_back = sh(returnStdout:true, script: "git rev-parse --short HEAD | sed -e 's/\r//g'").trim()
                println "release_commitid_back: ${release_commitid_back}"
                result.release_commitid_back = release_commitid_back

                def _front
                if (!front) {
                    println "No commitId_front, use the commitId_back: ${back}"
                    _front = back
                }else {
                    println "checkout KAP_Frontend to kystudio, use the commitid: ${front}"
                    _front = front
                }

                sh 'rm -rf ./kystudio'
                dir('kystudio') {
                    pullCodeFromGitMirror 'KAP_Frontend', _front
                    release_commitid_front = sh(returnStdout:true, script: "git rev-parse --short HEAD | sed -e 's/\r//g'").trim()
                    println "release_commitid_front: ${release_commitid_front}"
                    result.release_commitid_front = release_commitid_front
                    sh """
                        rm -f .npmrc
                        echo "registry = 'http://repo-ofs.kyligence.tech:8081/repository/npm-public/'" > .npmrc
                        cat .npmrc
                        ls -lh .
                    """
                }
            }
        }
    }
    return result
}

def getPackageInfo(version, envStage, cid, deployType, noSpark=false) {
    println "getPackageInfo -> version[${version}],envStage[${envStage}],cid[${cid}],deployType[${deployType}]"
    def package_path
    def branchCollection = ['4.5.x', '4.5.x-sp', '4.3.x', '4.3.x-sp']
    switch (deployType) {
        case 'Regular':
            package_path = "artifacts/${branchCollection[0]}/${envStage}"
            break
        case 'SP-4.5.x':
            package_path = "artifacts/${branchCollection[1]}/${envStage}"
            break
        case 'KE-4.3.x':
            package_path = "artifacts/${branchCollection[2]}/${envStage}"
            break
        case 'SP-4.3.x':
            package_path = "artifacts/${branchCollection[3]}/${envStage}"
            break
    }
    println "package_path: ${package_path}"

    def withoutSpark = noSpark ? "-NoSpark" : ""

    file_name = "KE-${version}-${cid}${withoutSpark}.tar.gz"
    package_file = "newten-cicd/${package_path}/${file_name}"
    ga_name = "Kyligence-Enterprise-${version}${withoutSpark}.tar.gz"

    println "file_name: ${file_name}"
    println "package_file: ${package_file}"

    def obj = [:]
    obj.package_path = package_path
    obj.package_file = package_file
    obj.file_name = file_name
    obj.ga_name = ga_name
    println obj.toString()
    return obj
}

pipeline {
    options {
        timeout(time: 12, unit: 'HOURS')
        ansiColor('xterm')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/yaml/jenkins-package-agent.yaml'
        }
    }

    environment {
        //变量名，用于存储input步骤的返回值
        paramsMap = ''
        // GA过程参数
        paramsGA = ''
        // K8S启动用包名
        package_file = ''
        // 文件路径
        package_path = ''
        // 文件名(给测试过程中的名字)
        file_name = ''
        // github token
        GIT_JEKNINS_TOKEN = credentials('jenkins-token')
        // tester emails
        tester_emails = '''minhua.feng@kyligence.io;hao.huang@kyligence.io;ye.feng@kyligence.io;meixiu.chen@kyligence.io;guang.you@kyligence.io;junhui.deng@kyligence.io;
        fengjiao.wang@kyligence.io;ao.li@kyligence.io;huiling.li@kyligence.io;chenqing.zhu@kyligence.io;jiang.ren@kyligence.io;lu.sun@kyligence.io'''
        // dev eamils
        dev_regular_emails = 'enwei.jiao@kyligence.io;yifan.zhang@kyligence.io'
        dev_sp_emails = 'wei.chen@kyligence.io;yifan.zhang@kyligence.io'
        dev_front_emails = 'qian.xia@kyligence.io'
        // product emails
        product_emails = 'yong.zhao@kyligence.io;qian.jiang@kyligence.io;kaiqi.xue@kyligence.io;lina.liu@kyligence.io;xinxing.wu@kyligence.io;zhao.han@kyligence.io;yang.li@kyligence.io'
    }

    parameters {
        // string(name: 'branch', defaultValue: 'newten-qa', description: '前后端同步的branch或者commitid（必填）')
        choice(name: 'deployWay', choices:'Auto Select\nManual Select', description:'发布方式: \nAuto Select-根据发布类型自动选择分支; \nManual Select-手动选择分支、CommitId;' )
        choice(name: 'deployType', choices:'Regular\nKE-4.3.x\nSP-4.5.x\nSP-4.3.x', description:'交付版本流程:\nRegular - 指主线发布\nKE-4.3.x - 指对应4.3系列的发布\nSP-4.5.x - 指每周的版本发布4.5系列\nSP-4.3.x - 指每周的版本发布4.3系列' )
        string(name: 'version', defaultValue: '4.5.10.0', description: '填写版本号，格式：4.5.10.0，4.3.11.1.1，版本号由【数字和 . 】组合，最多5段，必须规范,\n特别提醒：选择QA打包阶段，版本号写错是无法匹配到对应分支的！！！')
        choice(name: 'envStage', choices:'DEV\nQA\nRC\nGA', description:'打包阶段，如果要GA，选择GA进行流程' )
        booleanParam(name: 'noSpark', defaultValue: false, description: '打不包含Spark的KE包，会自动上传S3（不了解请勿勾选）')
        // booleanParam(name: 'replaceFouse', defaultValue: false, description: '手动强制打新包，覆盖缓存包')
    }

    stages {
        stage('1.Pull Code') {
            steps {
                script {
                    def reg = /^\d(\.\d+){1,4}$/
                    if (!params.version) {
                        error 'version 版本号不能为空'
                    }
                    if (!params.version.matches(reg)) {
                        error 'version 版本号格式有误'
                    }
                    if (params.deployWay == 'Auto Select') {
                        def _branch = getBranch(params.deployType, params.envStage, params.version)
                        release_branch_front = _branch
                        release_branch_back = _branch
                        def cms = gitCodeKe(_branch, _branch)
                        release_commitid_back = cms.release_commitid_back
                        release_commitid_front = cms.release_commitid_front
                    } else if (params.deployWay == 'Manual Select') {
                        paramsMap = input (
                            message: '请选择要开始的版本?',
                            ok: '确认！',
                            parameters: [
                                string(name: 'commitId_back', defaultValue: '', description: '后端Repo(KAP)的branch或者commitid（必填）注：填commitid的时候前端的必填'),
                                string(name: 'commitId_front', defaultValue: '', description: '前端repo(KAP_Frontend)的branch或者commitid（后端填分支名时，该参数可以不填）')
                            ],
                            // submitter:'liming.meng,admin',
                            submitterParameter:'APPROVER'
                        )
                        release_branch_front = paramsMap['commitId_front']
                        release_branch_back = paramsMap['commitId_back']
                        def cms = gitCodeKe(release_branch_back, release_branch_front)
                        release_commitid_back = cms.release_commitid_back
                        release_commitid_front = cms.release_commitid_front
                    } else {
                        error(message: '请选择足够的信息来确认代码分支')
                    }
                }
            }
        }
        stage('2.Building Package') {
            steps {
                container('build') {
                    timestamps {
                        script {
                            dir('sourcecode') {
                                def _version = "${params.version}-${params.envStage}"
                                package_info = getPackageInfo(_version, params.envStage, release_commitid_back, params.deployType, params.noSpark)

                                try {
                                    if(params.envStage=='GA'){
                                        package_info.file_name = package_info.ga_name
                                    }

                                    // if(!params.replaceFouse) {
                                        // 将已存在的包cp到当前目录，避免重新打包
                                    def existPackage = "${package_info.package_path}/${package_info.file_name}"
                                    sh script: """
                                        ls -l /var/cicd/${package_info.package_path}
                                        cp /var/cicd/${existPackage} ${package_info.file_name}
                                    """
                                    // }

                                    sh 'ls -l'
                                    println "package_info.package_file: ${package_info.package_file}"
                                    exist_package = fileExists(package_info.file_name)
                                    exist_package2 = fileExists("/var/cicd/${package_info.package_path}/${package_info.file_name}")
                                    println "/var/cicd/${package_info.package_path}/${package_info.file_name} is ${exist_package} ${exist_package2}"
                                } catch (Exception err) {
                                    echo err.getMessage()
                                }

                                if (!exist_package) {

                                    buildNewten(_version, params.noSpark)
                                    archiveArtifacts artifacts: 'dist/*.tar.gz', fingerprint: true, followSymlinks: false, onlyIfSuccessful: true

                                    sh script: """
                                        mkdir -p /var/cicd/${package_info.package_path}
                                        mv dist/*.tar.gz ${package_info.file_name}
                                        cp ${package_info.file_name} /var/cicd/${package_info.package_path}
                                    """

                                    exist_package = true
                                // cp ${package_info.file_name} ${package_info.ga_name}
                                } else {
                                    println "The package: ${package_info.file_name} is exist， Please reuse the it. \n 包已存在，不用重复打包"
                                }
                            }
                        }
                    }
                }
            }
            // post {
            //     success {
            //         jiraSendBuildInfo()
            //     }
            // }
        }
        stage('3.Dev/QA Upload') {
            when {
                expression {
                    return params.envStage in ['DEV', 'QA', 'RC', 'GA']
                }
            }
            failFast true
            parallel {
                stage('3.1.Upload to Azure CN') {
                    steps {
                        uplaodAzure(package_info)
                    }
                    post {
                        success {
                            sendNotify('EMAIL',
                                "SUCCESSFUL to Upload the Tar into the Azure CN server'",
                                // "liming.meng@kyligence.io",
                                tester_emails,
                                """<p>SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
                                <p>The Job upload the package ${package_info.file_name} to the Azure server: [159.27.120.141]</p>
                                <p>It saved in the path of [/home/4xuser/data/devops], please check it and use! Tks!</p>"""
                            )
                        }
                    }
                }
                stage('3.2.Upload to Nexus') {
                    steps {
                        uploadNexus('raw-tars-hosted', package_info.package_path, package_info.file_name)
                    }
                }
                stage('3.3.Upload to AWS Global S3') {
                    when{
                        expression {
                            return params.noSpark == true
                        }
                    }
                    steps {
                        println("upload to AWS S3 in Global: ${package_info.file_name}")
                        // 上传S3：https://s3.console.aws.amazon.com/s3/buckets/download.kyligence.io?region=us-west-1&prefix=product/kap/4.0.x/&showversions=false
                        uploadAwsS3('us-west-2', 'aws_global_s3_cp', 'kyligencecloud-ci', "packages/ke-without-spark/${package_info.file_name}", package_info.file_name)
                    }
                }
            }
        }
        stage('4.Approve GA') {
            when {
                expression {
                    return params.envStage == 'GA' && exist_package && !params.noSpark
                }
            }
            steps {
                container('build') {
                    script {
                        def checkMsg = "该版本可以GA吗？\n确认项：\n1.分支情况，前端 ${release_branch_front}，后端 ${release_branch_back}\n2. 发布版本号：${params.version}"
                        println checkMsg
                        // sh 'printenv'
                        paramsGA = input (
                            message: checkMsg,
                            ok: '确认！',
                            submitter:'liming.meng,meixiu.chen,enwei.jiao,chenqing.zhu',
                            submitterParameter:'APPROVER',
                            parameters:[
                                booleanParam(name: "skipUpload", defaultValue: false, description: '是否跳过上传')
                            ]
                        )
                        ga_name = package_info.file_name
                    }
                }
            }
        }
        stage('5.GA Upload') {
            when {
                expression {
                    return params.envStage == 'GA' && exist_package && !params.noSpark && !paramsGA['skipUpload']
                }
            }
            failFast true
            parallel {
                stage('5.1.GA AWS CN') {
                    steps {
                        println("upload to AWS S3 in CN: ${ga_name}")
                        // 上传S3：https://console.amazonaws.cn/s3/buckets/download.kyligence.io?region=cn-north-1&prefix=product/kap/4.0.x/&showversions=false
                        uploadAwsS3('cn-north-1', 'aws_cn_s3_cp', 'download.kyligence.io', "product/kap/4.0.x/${ga_name}", ga_name)
                    }
                }
                stage('5.2.GA AWS Global') {
                    steps {
                        println("upload to AWS S3 in Global: ${ga_name}")
                        // 上传S3：https://s3.console.aws.amazon.com/s3/buckets/download.kyligence.io?region=us-west-1&prefix=product/kap/4.0.x/&showversions=false
                        uploadAwsS3('us-west-1', 'aws_global_s3_cp', 'download.kyligence.io', "product/kap/4.0.x/${ga_name}", ga_name)
                    }
                }
                stage('5.3.GA Nexus') {
                    steps {
                        println("upload to Nexus repo-ofs: ${ga_name}")
                        uploadNexus('raw-ke-ga-tar-hosted', 'product/ke/4.0.x', ga_name)
                    }
                }
            }
        }
        stage('6.Tag') {
            when {
                expression {
                    return params.envStage == 'GA' && exist_package && !params.noSpark
                }
            }
            steps {
                container('build') {
                    script {
                        def _tag = "ke-${version}"
                        def bcid = ''
                        def fcid = ''
                        dir('sourcecode') {
                            println "backend: KAP push tag: ${_tag} on branch ${release_branch_back} in sourcecode folder"
                            githubHelper 'TAG', release_branch_back, 'KAP', _tag
                            bcid = sh(returnStdout:true, script: "git rev-parse HEAD | sed -e 's/\r//g'").trim()
                            println "backend [KAP] commitId: ${bcid}"

                            dir('kystudio') {
                                println "frontend: KAP_Frontend push tag: ${_tag} on branch ${release_branch_front} in kystudio folder"
                                githubHelper 'TAG', release_branch_front, 'KAP_Frontend', _tag
                                fcid = sh(returnStdout:true, script: "git rev-parse HEAD | sed -e 's/\r//g'").trim()
                                println "frontend [KAP_Frontend] commitId: ${fcid}"
                            }
                        }

                        sendNotify(
                            'EMAIL',
                            "KE ${version} SUCCESSFUL GA", 
                            // "liming.meng@kyligence.io",
                            product_emails,
                            """<p>SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
                            <p>The Backend repo of [KAP] commitId: ${bcid}</p>
                            <p>The Frontend repo of [KAP_Frontend] commitId: ${fcid}</p>"""
                        )
                    }
                }
            }
        }
    }
}
