apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring-mysql
  namespace: <<<namespace>>>
spec:
  jobLabel: monitoring-mysql
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - mysql
  namespaceSelector:
    matchNames:
    - <<<namespace>>>
  endpoints:
  - port: metrics
    interval: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring-jmx
  namespace: <<<namespace>>>
spec:
  jobLabel: monitoring-jmx
  selector:
    matchExpressions:
    - key: metrics-exporter
      operator: In
      values:
      - prometheus
  namespaceSelector:
    matchNames:
    - <<<namespace>>>
  endpoints:
  - port: metrics
    interval: 10s