apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-claim-local
  namespace: ops
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi