#!groovy

@Library('devopslib') _

pipeline {
    options {
        timeout(time: 3, unit: 'HOURS')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/yaml/jenkins-agent-aws-dailyci.yaml'
        }
    }

    parameters {
        string(name: 'repo', defaultValue: 'Kyligence', description: 'Kap repo?')
        string(name: 'branch', defaultValue: '', description: 'Kap branch?')
        string(name: 'args', defaultValue: '', description: 'Extra JVM options for maven test')
    }

    stages {
        stage("Checkout Source Code") {
            steps {
                container("git") {
                    dir("sourcecode") {
                        script {
                            currentBuild.description = "${params.branch} ${params.args}"
                            retry(3) {
                                githubCheckout 'KAP', params.branch, 'https', 'github.com', '+refs/pull/*:refs/remotes/origin/pr/* +refs/heads/*:refs/remotes/origin/*', 'kyligencegit', params.repo
                            }
                        }
                        script {
                            if(params.branch == 'newten') {
                                s3Archive('download')
                            }else if(params.branch == "newten-dev") {
                                s3Archive4YingLong('download')
                            }
                        }
                    }
                }
            }
        }
        stage('Maven Install') {
            steps {
                container("maven") {
                    dir("sourcecode") {
                        script {
                            def modules = sh(script:'''
                                mvn help:evaluate -Dexpression=project.modules | grep -v "^\\[" | grep -v "<\\/*strings>" | sed 's/<\\/*string>//g' | sed 's/[[:space:]]//'
                            ''', returnStdout: true).trim().split("\n").collect({ it.trim() }).findAll { it.startsWith("src") }
                            if (modules.contains('src/external')) {
                                sh script: "mvn -U clean install -T 2C -pl src/external -Dmaven.compile.fork=true -DskipTests"
                            }
                            sh script: "mvn -U clean install -T 2C -Dmaven.compile.fork=true -DskipTests"
                        }
                    }
                }
            }
        }
        stage('Testing') {
            steps {
                dynamicNewtenParallelTest()
            }
            post {
                always {
                    timestamps {
                        junit skipPublishingChecks: true, testResults: '*Test-Stage-*/**/target/surefire-reports/*.xml'
                    }
                    container('maven') {
                        script {
                            if(params.branch == 'newten') {
                                s3Archive('upload')
                            }else if(params.branch == "newten-dev") {
                                s3Archive4YingLong('upload')
                            }
                        }
                    }
                }
            }
        }
        stage('SonarQube') {
            steps {
                sonarAnalyze("""-Dsonar.branch.name=${params.branch} \
                                -Dsonar.projectKey=Kyligence_KAP """)
            }
        }
    }

    post {
        failure {
            httpRequest(
                url:"https://open.feishu.cn/open-apis/bot/v2/hook/54fe68e4-e635-414d-b738-002695390743",
                httpMode: "POST",
                consoleLogResponseBody: true,
                contentType: "APPLICATION_JSON",
                requestBody: groovy.json.JsonOutput.toJson([
                    'msg_type': 'text',
                    'content': [
                        'text': "branch: ${params.branch} CI failed.\nsee: ${env.BUILD_URL}"
                    ]
                ])
            )
        }
        aborted {
            httpRequest(
                url:"https://open.feishu.cn/open-apis/bot/v2/hook/54fe68e4-e635-414d-b738-002695390743",
                httpMode: "POST",
                consoleLogResponseBody: true,
                contentType: "APPLICATION_JSON",
                requestBody: groovy.json.JsonOutput.toJson([
                    'msg_type': 'text',
                    'content': [
                        'text': "branch: ${params.branch} CI aborted.\nsee: ${env.BUILD_URL}"
                    ]
                ])
            )
        }
    }
}
