#!groovy

@Library('devopslib') _

pipeline {
    options {
        timeout(time: 6, unit: 'HOURS')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/yaml/jenkins-agent.yaml'
        }
    }

    parameters {
        string(name: 'repo', defaultValue: '', description: 'Kap repo?')
        string(name: 'branch', defaultValue: '', description: 'Kap branch?')
        string(name: 'args', defaultValue: '', description: 'Extra JVM options for maven test')
        credentials(name: 'certificate', credentialType: 'com.cloudbees.plugins.credentials.common.StandardCredentials', defaultValue: 'kyligencegit', required: true)
    }

    stages {
        stage("Checkout Source Code") {
            steps {
                container("git") {
                    dir("sourcecode") {
                        script {
                            currentBuild.description = "${params.branch} ${params.args}"
                            retry(3) {
                                githubCheckout 'KAP', null, 'https', 'github.com', '+refs/pull/*:refs/remotes/origin/pr/* +refs/heads/*:refs/remotes/origin/*'
                            }
                        }
                        s3Archive('download')
                    }
                }
            }
        }
        stage('Maven Install') {
            steps {
                container("maven") {
                    dir("sourcecode") {
                        script {
                            sh script: """
                                mvn -U clean install -T 2C -pl src/external -Dmaven.compile.fork=true -DskipTests
                                mvn -U clean install -T 2C -Dmaven.compile.fork=true -DskipTests
                            """
                        }
                    }
                }
            }
        }
        stage('Testing') {
            steps {
                dynamicNewtenParallelTest()
            }
            post {
                always {
                    timestamps {
                        junit skipPublishingChecks: true, testResults: '*Test-Stage-*/**/target/surefire-reports/*.xml'
                    }
                    container('maven') {
                        s3Archive('upload')
                    }
                }
            }
        }
        stage('SonarQube') {
            steps {
                container("sonar-cloud") {
                    dir("sourcecode") {
                        withSonarQubeEnv(credentialsId: 'sonar_credential', installationName: 'sonar cloud') {
                            // You can override the credential to be used
                            sh script: """
                                mkdir -p coverage/exec
                                mkdir -p coverage/jars
                                i=1
                                outputs=\$(find "${WORKSPACE}" -path '*Test-Stage-*jacoco.exec' | sed 's/.*/&/')
                                for out in \$outputs; do
                                    target_out=\$(echo \$out | rev |cut -d/ -f 3 | rev)
                                    cp -r \$out coverage/exec/"\$target_out-\$i-jacoco.exec"
                                    i=\$((i+1))
                                done
                            """

                            dir("coverage") {
                                script {
                                    try { sh script: "cp ../src/server/target/jars/kap-* jars/" } catch (Exception err) { }
                                    try { sh script: "cp ../src/server/target/jars/yinglong-* jars/" } catch (Exception err) { }
                                    try { sh script: "cp ../src/server/target/jars/ke-* jars/" } catch (Exception err) { }
                                    try { sh script: "rm -f jars/kap-external-curator-* jars/kap-external-guava20-* jars/kap-external-swagger-* jars/kap-external-influxdb-*" } catch (Exception err) { }
                                    try { sh script: "rm -f jars/*-tests.jar" } catch (Exception err) { }
                                    sh script: "java -jar jacococli.jar report ./exec/* --html output --classfiles jars/ --xml jacoco.xml"
                                }
                            }
                            sh script: """
                                mvn sonar:sonar -T 4C \
                                    -Dsonar.host.url=https://sonarcloud.io \
                                    -Dsonar.organization=kyligence \
                                    -Dsonar.projectKey=Kyligence_KAP \
                                    -Dsonar.branch.name=${params.branch} \
                                    -Dsonar.coverage.jacoco.xmlReportPaths=${WORKSPACE}/sourcecode/coverage/jacoco.xml
                            """
                        }
                    }
                }
            }
        }
    }
}
