#!groovy

@Library('devopslib@devops-0307') _

pipeline {
    options {
        timeout(time: 2, unit: 'HOURS')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/yaml/jenkins-agent.yaml'
        }
    }

    parameters {
        string(name: 'repo', defaultValue: '', description: 'Kap repo?')
        string(name: 'branch', defaultValue: '', description: 'Kap branch?')
        string(name: 'args', defaultValue: '', description: 'Extra JVM options for maven test')
    }

    stages {
        stage("Checkout Source Code") {
            steps {
                container("git") {
                    dir("sourcecode") {
                        script {
                            currentBuild.description = "${params.branch} ${params.args}"
                            retry(3) {
                                githubCheckout 'KAP', params.branch, 'https', 'github.com', '+refs/pull/*:refs/remotes/origin/pr/* +refs/heads/*:refs/remotes/origin/*', 'kyligencegit'
                            }
                        }
                        s3Archive('download')
                    }
                }
            }
        }
        stage('Maven Install') {
            steps {
                container("maven") {
                    dir("sourcecode") {
                        script {
                            sh script: """
                                mvn -U clean install -T 2C -Dmaven.compile.fork=true -DskipTests
                            """
                        }
                    }
                }
            }
        }
        stage('Testing') {
            steps {
                dynamicNewtenParallelTest()
            }
            post {
                always {
                    timestamps {
                        junit skipPublishingChecks: true, testResults: '*Test-Stage-*/**/target/surefire-reports/*.xml'
                    }
                    container('maven') {
                        s3Archive('upload')
                    }
                }
            }
        }
        stage('SonarQube') {
            steps {
                sonarAnalyze("-Dsonar.branch.name=${params.branch}")
            }
        }
    }
}
