apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-scripts-pvc
  namespace: zabbix
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeName: zabbix-scripts-pv
  volumeMode: Filesystem
