apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway.fullname" . }}
data:
  config.yaml: |
    spring:
      redis:
        host: {{ .Values.global.redis.host }}
        database: {{ .Values.global.redis.database }}
        password: {{ .Values.global.redis.password }}
    saas:
      gateway:
        integrate:
          iam: {{.Values.saas.gateway.integrate.iam}}