kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: harbor-data
  namespace: harbor
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: ''
  volumeMode: Filesystem
