kind: ConfigMap
apiVersion: v1
metadata:
  name: s3-conf
data:
  s3cfg: |
    [default]
    access_key = {{ .Values.global.s3.ak }}
    secret_key = {{ .Values.global.s3.sk }}
    host_base = {{ .Values.global.s3.endpoint }}
    host_bucket = {{ .Values.global.s3.endpoint }}/%(bucket)
    cloudfront_host = {{ .Values.global.s3.endpoint }}
    use_https = false
