#!groovy

@Library('devopslib') _

pipeline {
    options {
        timeout(time: 3, unit: 'HOURS')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/yaml/jenkins-agent-gluten-ci.yaml'
        }
    }

    parameters {
        string(name: 'branch', defaultValue: '', description: 'gluten branch')
    }


    stages {
        stage('Checkout Source Code') {
            steps {
                container('git') {
                    dir('clickhouse') {
                        script {
                            sh 'env'
                            githubCheckout 'ClickHouse', params.branch, 'https', 'github.com', '+refs/pull/*:refs/remotes/origin/pr/* +refs/heads/*:refs/remotes/origin/*', 'kyligencegit'
                            // replaceRepo()
                            sh 'ls;'
                            sh 'git submodule update --init --recursive;'
                        }
                    }
                    dir('gluten') {
                        script {
                            sh 'env'
                            githubCheckout 'gluten', 'main', 'https', 'github.com', '+refs/pull/*:refs/remotes/origin/pr/* +refs/heads/*:refs/remotes/origin/*', 'kyligencegit', 'oap-project'
                        }
                    }
                }
            }
        }

        stage("Code Style Check") {
            steps {
                container('git') {
                    dir('clickhouse') {
                        script {
                            status = sh returnStatus: true ,script:'''
                            info=`\${WORKSPACE}/clickhouse/utils/local-engine/tool/check-style`
                            if [ -z "$info" ]; then
                                echo "check success"
                            else
                                exit 1
                            fi
                            '''
                            if (status == 1) {
                                error("failed")
                            }
                        }
                    }
                }
            }
        }

        stage('Build CH') {
            steps {
                container('libchbuilder') {
                    dir('clickhouse') {
                        script {
                            sh 'env'
                            sh 'ls;'

                            sh '''mkdir -p /build && cd /build || exit;
                                export CCACHE_DIR=/ccache;
                                export CCACHE_BASEDIR=/build;
                                export CCACHE_NOHASHDIR=true;
                                export CCACHE_COMPILERCHECK=content;
                                export CCACHE_MAXSIZE=15G;

                                cmake -G Ninja  "-DCMAKE_C_COMPILER=$CC" "-DCMAKE_CXX_COMPILER=$CXX" "-DCMAKE_BUILD_TYPE=Release" "-DENABLE_PROTOBUF=1" "-DENABLE_EMBEDDED_COMPILER=$ENABLE_EMBEDDED_COMPILER" "-DENABLE_TESTS=OFF" "-DWERROR=OFF" "-DENABLE_JEMALLOC=1" \${WORKSPACE}/clickhouse/;
                                ninja ch;'''
                        }
                        script {
                            sh 'mkdir output && cp /build/utils/local-engine/libch.so output/libch.so;'
                        }
                    }
                }
            }
        }

        stage('Unit Test') {
            steps {
                container("maven") {
                    dir("gluten") {
                        script {
                            sh script: 'mkdir -p /data && tar -zxf /dataset/tpcds-data-sf1.tar.gz -C /data/'
                            sh script: 'ls -al /data/tpcds-data-sf1'
                            sh script: 'export MAVEN_OPTS="-Xmx5g -XX:ReservedCodeCacheSize=1g" && mvn clean test -Pbackends-clickhouse,spark-3.2 -Dtpcds.data.path=/data/tpcds-data-sf1 -Dclickhouse.lib.path=\${WORKSPACE}/clickhouse/output/libch.so'
                        }
                    }
                }
            }
        }



    }
}
