#!groovy

@Library('devopslib') _

def IS_DEBUG = false

def modules = [
        ['name': 'common', 'path': 'kyligence/src/ke-common-booter', 'imageName': 'common', 'image': ''],
        ['name': 'data-loading', 'path': 'kylin/src/data-loading-booter', 'imageName': 'data-loading', 'image': ''],
        ['name': 'query', 'path': 'kyligence/src/ke-query-booter', 'imageName': 'query', 'image': ''],
        ['name': 'smart', 'path': 'kyligence/src/smart-booter', 'imageName': 'smart', 'image': ''],
        ['name': 'resource', 'path': 'kyligence/src/resource-booter', 'imageName': 'resource', 'image': ''],
        ['name': 'ops', 'path': 'kyligence/src/ops-booter', 'imageName': 'ops', 'image': '']
]
// 以下是依赖的容器镜像，name 作为 tar 包名称，imageName 需要精确到 tag 版本号
def defModules = [
        ['name': 'busybox', imageName: 'busybox'],
        ['name': 'gateway', imageName: 'repo-ofs.kyligence.com/gateway:5.1.2-DEV-beab30ca'],
//        ['name': 'python-hadoop-hive', imageName: 'repo-ofs.kyligence.com/qa/python-hadoop-hive-dev:latest'],
        ['name': 'spark', imageName: 'harbor-ofs.kyligence.com/spark/spark:3.3.0-kylin-4.6.4.0-SNAPSHOT-hadoop3'],
        ['name': 'skywalking-java-agent', imageName: 'apache/skywalking-java-agent:8.10.0-alpine'],
//        ['name': 'auspicious-resource-executor', imageName: 'harbor-ofs.kyligence.com/auspicious/auspicious-resource-executor:latest']
]

// 包信息对象
def package_info = [:]
// 发布分支(前端)
def release_branch_front = ''
// 发布分支(后端)
def release_branch_back = ''
// 前端commitId
def release_commitid_front = ''
// 后端commitId
def release_commitid_back = ''
// 前端镜像tag（版本号）
def release_tag_front = ''
// 后端镜像tag（版本号）
def release_tag_back = ''
//变量名，用于存储input步骤的返回值
def paramsMap = [:]

// 根据发布类型自动获取分支
def getBranch(deployType, envStage, version) {
    print "getBranch -> deployType[${deployType}],envStage[${envStage}],version[${version}]"
    def _result
    def _branch_release = ''
    def _branch_qa = ''
    def _branch_dev = ''
    def branchCollection = ['yinglong']

    switch (deployType) {
        case 'Regular':
            _branch_release = branchCollection[0]
            _branch_qa = "yinglong-${version}-qa"
            _branch_dev = "${_branch_release}-dev"
            break
    }

    switch (envStage) {
        case 'DEV':
            _result = _branch_dev
            break
        case 'QA':
            _result = _branch_qa
            break
        case 'RC':
        case 'ALPHA':
        case 'BETA':
        case 'GA':
            _result = _branch_release
            break
    }
    echo "getBranch: ${_result}"
    return _result
}

// git获取KE代码（预先触发同步git mirror）
def gitCodeKe(back, front, pMap) {
    def result = [:]
    script {
        println "backend branch/commit: ${back}, frontend branch/commit: ${front}"
        if (!back) {
            error 'commitId_back 参数不能为空'
        }

        if (pMap['back_remote']) {
            githubCheckout 'KAP', back, 'https', 'github.com'
        } else {
            pullCodeFromGitMirror 'KAP', back
        }

        release_commitid_back = sh(returnStdout: true, script: "git rev-parse --short HEAD | sed -e 's/\r//g'").trim()
        println "release_commitid_back: ${release_commitid_back}"
        result.release_commitid_back = release_commitid_back

        release_commitid_back_full = sh(returnStdout: true, script: "git rev-parse HEAD | sed -e 's/\r//g'").trim()
        println "release_commitid_back_full: ${release_commitid_back_full}"
        result.release_commitid_back_full = release_commitid_back_full

        def _front
        if (!front) {
            println "No commitId_front, use the commitId_back: ${back}"
            _front = back
        } else {
            println "checkout KAP_Frontend to kystudio, use the commitid: ${front}"
            _front = front
        }

        sh 'ls -lha && ls -lha kystudio'
        sh 'rm -rf kystudio'
        sh 'ls -lha'
        dir('kystudio') {
            sh 'pwd && ls -lha'
            if (pMap['front_remote']) {
                githubCheckout 'KAP_Frontend', _front, 'https', 'github.com'
            } else {
                pullCodeFromGitMirror 'KAP_Frontend', _front
            }

            release_commitid_front = sh(returnStdout: true, script: "git rev-parse --short HEAD | sed -e 's/\r//g'").trim()
            println "release_commitid_front: ${release_commitid_front}"
            result.release_commitid_front = release_commitid_front
            sh """
                rm -f .npmrc
                echo "registry = 'https://repo-ofs.kyligence.com/repository/npm-public/'" > .npmrc
                cat .npmrc
                ls -lha .
            """
        }
    }
    return result
}

//
def getPackageInfo(version, envStage, fcid, bcid, deployType) {
    println "getPackageInfo -> version[${version}],envStage[${envStage}],fcid[${fcid}],bcid[${bcid}],deployType[${deployType}]"
    def package_path = ''
    def branchCollection = ['5.0.x', '5.0.x-sp']
    switch (deployType) {
        case 'Regular':
            package_path = "artifacts/${branchCollection[0]}/${envStage}"
            break
        case 'SP-5.0.x':
            package_path = "artifacts/${branchCollection[1]}/${envStage}"
            break
    }
    println "package_path: ${package_path}"

    file_name = "YL-${version}-${bcid}.tar.gz"
    package_file = "newten-cicd/${package_path}/${file_name}"
    ga_name = "Kyligence-Enterprise-${version}.tar.gz"

    println "file_name: ${file_name}"
    println "package_file: ${package_file}"
    println "ga_name: ${ga_name}"

    def obj = [:]
    obj.package_path = package_path
    obj.package_file = package_file
    obj.file_name = file_name
    obj.ga_name = ga_name

    switch (envStage) {
        case 'DEV':
        case 'QA':
        case 'RC':
            obj.tag_front = "${version}-${envStage}-${fcid}"
            obj.tag_back = "${version}-${envStage}-${bcid}"
            break
        case 'ALPHA':
        case 'BETA':
            obj.tag_back = "${version}-${envStage}"
            break
        case 'GA':
            obj.tag_back = version
            obj.file_name = ga_name
            obj.package_file = "newten-cicd/${package_path}/${ga_name}"
            break
    }
    println obj.toString()
    return obj
}

// docker save 离线镜像并制作压缩包
def dockerSave(imageName) {
    sh script: """
        pwd
        docker save harbor-ofs.kyligence.com/enterprise/${imageName} > ${imageName}.tar
        ls -lth
        mv ${imageName}.tar ${env.WORKSPACE}/sourcecode/offline
        ls -lth ${env.WORKSPACE}/sourcecode/offline
    """
}

pipeline {
    options {
        timeout(time: 12, unit: 'HOURS')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/yaml/jenkins-helm-docker-package-agent.yaml'
        }
    }

    environment {
        repo = 'harbor-ofs.kyligence.com'
        dockerRegistryUrl = "https://${repo}"
        registryCredential = 'harbor-devops'
        common = ''
        data_loading = ''
        query = ''
        smart = ''
        frontend = ''
        release_commitid_back = ''
        release_commitid_back_full = ''
        release_commitid_front = ''
        spark = ''
    }

    parameters {
        choice(name: 'deployWay', choices: 'Auto Select\nManual Select', description: '发布方式: \nAuto Select-根据发布类型自动选择分支; \nManual Select-手动选择分支、CommitId;')
        choice(name: 'deployType', choices: 'Regular\nSP-5.0.x', description: '交付版本流程:\nRegular - 指主线发布\nSP-5.0.x - 指每周的版本发布5.0.x系列')
        string(name: 'version', defaultValue: '5.0.0', description: '填写版本号，格式：5.0.0，5.0.1.1.1，版本号由【数字和 . 】组合，最多5段，必须规范,\n特别提醒：选择QA打包阶段，版本号写错是无法匹配到对应分支的！！！')
        choice(name: 'envStage', choices: 'DEV\nQA\nRC\nALPHA\nBETA\nGA', description: '打包阶段，如果要GA，选择GA进行流程')
        string(name: 'profiles', defaultValue: 'kubernetes,iam', description: '指定的 profile，kubernetes 会打包 yinglong，iam 会添加 iam 的 jar')
        booleanParam(name: 'build', defaultValue: true, description: '是否构建')
        booleanParam(name: 'push', defaultValue: true, description: '推送镜像')
    }

    stages {
        stage('1.Pull Code') {
            when {
                environment name: 'build', value: 'true'
            }
            steps {
                container('build') {
                    dir('sourcecode') {
                        script {
                            // 1. 参数检查：version
                            paramsVerify.version(params.version)
                            // 2. 根据分支规则获取分支
                            if (params.deployWay == 'Auto Select') {
                                // 2.1 根据分支流程规则，自动获取代码分支参数
                                def _branch = getBranch(params.deployType, params.envStage, params.version)
                                release_branch_front = _branch
                                release_branch_back = _branch
                                def cms = gitCodeKe(_branch, _branch, paramsMap)
                                release_commitid_back = cms.release_commitid_back
                                release_commitid_back_full = cms.release_commitid_back_full
                                release_commitid_front = cms.release_commitid_front
                            } else if (params.deployWay == 'Manual Select') {
                                // 2.2 根据手动输入参数设定分支
                                paramsMap = input(
                                        message: '请选择要开始的版本?',
                                        ok: '确认！',
                                        parameters: [
                                                string(name: 'commitId_back', defaultValue: '', description: '后端Repo(KAP)的branch或者commitid（必填）注：填commitid的时候前端的必填'),
                                                string(name: 'commitId_front', defaultValue: '', description: '前端repo(KAP_Frontend)的branch或者commitid（后端填分支名时，该参数可以不填）'),
                                                booleanParam(name: 'overide', defaultValue: false, description: '全新打包，覆盖现有同名包'),
                                                booleanParam(name: 'back_remote', defaultValue: false, description: '后端拉取远程分支（绕开 git mirror）'),
                                                booleanParam(name: 'front_remote', defaultValue: false, description: '前端拉取远程分支（绕开 git mirror）')
                                        ],
                                        // submitter:'liming.meng,admin',
                                        submitterParameter: 'APPROVER'
                                )
                                release_branch_front = paramsMap['commitId_front']
                                release_branch_back = paramsMap['commitId_back']
                                def cms = gitCodeKe(release_branch_back, release_branch_front, paramsMap)
                                release_commitid_back = cms.release_commitid_back
                                release_commitid_back_full = cms.release_commitid_back_full
                                release_commitid_front = cms.release_commitid_front
                            } else {
                                println 'no code pulled'
                            }

                            sh """
                                echo "${release_commitid_back_full}@KAP"
                                echo "Kyligence Enterprise ${params.version}"
                                echo "${release_commitid_back_full}@KAP" > commit_SHA1
                                echo "Build with JENKINS at" `date "+%Y-%m-%d %H:%M:%S"` >> commit_SHA1
                                echo "Kyligence Enterprise ${params.version}" > VERSION
                            """
                        }
                    }
                    dir('global') {
                        script {
                            githubCheckout 'xuanwu-charts', 'main', 'https', 'github.com'
                        }
                    }
                }
            }
        }
        stage('2.Building Package') {
            when {
                environment name: 'build', value: 'true'
            }
            steps {
                container('build') {
                    dir('sourcecode') {
                        script {
                            package_info = getPackageInfo(params.version, params.envStage, release_commitid_front, release_commitid_back, params.deployType)
                            sh """
                                if [ ! -d offline  ];then
                                    mkdir -p offline
                                fi
                                mkdir -p /var/cicd/${package_info.package_path}
                            """

                            if (!profiles) {
                                sh '''
                                    mvn -U clean install -T 4C -DskipTests -Dmaven.compile.fork=true
                                '''
                            } else {
                                sh """
                                    mvn -U clean install -T 4C -DskipTests -Dmaven.compile.fork=true -P ${profiles}
                                """
                            }

                            for (m in modules) {
                                dir(m.path) {
                                    sh """
                                        pwd
                                        ls -al
                                        cp ../../../VERSION VERSION
                                        cp ../../../commit_SHA1 commit_SHA1
                                        cp ${env.WORKSPACE}/docker/yinglong-jdk8/Dockerfile Dockerfile
                                        sed -i "s#&&replace_package&&#target/${m.name}*.tar.gz#g" Dockerfile
                                        sed -i "s#&&replace_dir&&#${m.name}#g" Dockerfile
                                        cat Dockerfile
                                    """
                                }
                            }
                        }
                    }
                }
            }
        }
        stage('3.build docker image') {
            when {
                environment name: 'push', value: 'true'
            }
            parallel {
                stage('3.1.image front') {
                    steps {
                        container('docker') {
                            dir('sourcecode') {
                                script {
                                    dir('kystudio') {
                                        sh """
                                            pwd
                                            ls -alt
                                            cat .npmrc
                                            rm -f .npmrc
                                            echo "registry = 'https://repo-ofs.kyligence.com/repository/npm-public/'" > .npmrc
                                            cat .npmrc
                                        """

                                        frontend = docker.build('enterprise/frontend', "-f ${env.WORKSPACE}/docker/nginx-node-10.24.1/Dockerfile .")
                                    }
                                }
                            }
                        }
                    }
                }
                stage('3.2.images yinglong') {
                    steps {
                        container('docker') {
                            script {
                                for (m in modules) {
                                    dir("sourcecode/${m.path}") {
                                        retry(2) {
                                            m.image = docker.build("enterprise/${m.imageName}")
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                stage('3.3 image spark') {
                    steps {
                        container('docker') {
                            dir('sourcecode') {
                                script {
                                    sh "ls -alt"
                                    spark = docker.build('enterprise/spark', "-f ${env.WORKSPACE}/docker/yinglong-jdk8/Dockerfile4Spark .")
                                }
                            }
                        }
                    }
                }
            }
        }
        stage('4.1.tag & push images') {
            when {
                environment name: 'push', value: 'true'
            }
            steps {
                container('docker') {
                    script {
                        dir('sourcecode') {
                            println "package_info.tag_front: ${package_info.tag_front}"
                            retry(2) {
                                docker.withRegistry(dockerRegistryUrl, registryCredential) {
                                    frontend.push(package_info.tag_front)
                                    frontend.push('latest')
                                    dockerSave("frontend:${package_info.tag_front}")
                                }
                            }
                            println "package_info.tag_back: ${package_info.tag_back}"
                            docker.withRegistry(dockerRegistryUrl, registryCredential) {
                                for (m in modules) {
                                    retry(2) {
                                        m.image.push(package_info.tag_back)
                                        m.image.push('latest')
                                        dockerSave("${m.imageName}:${package_info.tag_back}")
                                    }
                                }
                                retry(2) {
                                    spark.push(package_info.tag_back)
                                    spark.push('latest')
                                    dockerSave("spark:${package_info.tag_back}")
                                }
                            }
                        }
                    }
                }
            }
        }
        stage('4.2.push helm') {
            steps {
                container('helm-pusher') {
                    timestamps {
                        withCredentials([usernamePassword(credentialsId: 'harbor-devops', passwordVariable: 'password', usernameVariable: 'username')]) {
                            script {
                                dir('global') {
                                    sh script: """
                                        pwd
                                        ls -lh .
                                        helm repo add --username $username --password $password harbor-ofs https://harbor-ofs.kyligence.com/chartrepo/enterprise
                                        helm package global-service
                                        ls -lh .
                                        helm cm-push *.tgz harbor-ofs
                                        cp *.tgz ${env.WORKSPACE}/sourcecode/offline
                                    """
                                }
                                dir('sourcecode') {
                                    sh script: """
                                        cd ${env.WORKSPACE}/helm
                                        sed -i 's/5.0.0-ALPHA/${package_info.tag_back}/g' yinglong/Chart.yaml
                                        cat yinglong/Chart.yaml
                                        helm repo add --username $username --password $password harbor-ofs https://harbor-ofs.kyligence.com/chartrepo/enterprise
                                        helm package yinglong
                                        ls -lh .
                                        helm cm-push *.tgz harbor-ofs
                                        cp *.tgz ${env.WORKSPACE}/sourcecode/offline
                                    """
                                }
                            }
                        }
                    }
                }
            }
        }
        stage('4.3.make offline & upload S3') {
            steps {
                container('docker') {
                    script {
                        dir('sourcecode/offline') {
                            defModules.eachWithIndex { LinkedHashMap<String, String> entry, int i ->
                                sh script: """
                                    docker pull ${entry['imageName']}
                                    docker save ${entry['imageName']}  > ${entry['name']}.tar
                                """
                            }

                            sh script: """
                                pwd
                                ls -lh .
                                tar -cvf ${package_info.file_name} ./*
                                cp ${package_info.file_name} /var/cicd/${package_info.package_path}
                            """
                        }
                        // upload to S3
                        println("upload to S3 in AWS CN: ${package_info.file_name}")
                        retry(2) {
                            uploadHelper.uploadAwsS3(package_info.file_name, "product/yinglong/5.0.x/${package_info.file_name}", 'download.kyligence.io', 'cn-north-1', 'aws_cn_s3_cp', 'sourcecode/offline')
                        }
                    }
                }
            }
        }
        stage('5.deploy') {
            input {
                message '请选择部署方式，并配置必须的参数，完成后请点击确认。整个流程12小时后会自动截止）'
                ok '确认！'
                parameters {
                    choice(name: 'deploy', choices: 'skip\nupgrade\ninstall', description: '部署方式:\nskip - 跳过\nupgrade - 更新\ninstall - 重新部署')
                    choice(name: 'namespace', choices: 'yinglong-dev\nyinglong-dev2\nyinglong-qa\nyinglong-test', description: '选择要部署的namespace')
                    string(name: 'hadoop_prefix', defaultValue: 'hadoop', description: 'hadoop environment')
                    string(name: 'tenant_id', defaultValue: '', description: 'tenant id')
                    string(name: 'metadata_table_name', defaultValue: 'yinglong_metadata', description: 'metadata table name')
                    string(name: 'extra_settings', defaultValue: ' ', description: 'helm set parameter, each set starts with --set , seprated by space')
                }
                submitterParameter 'APPROVER'
            }
            steps {
                echo 'Up in K8S at office env'
                container('helm') {
                    withCredentials([file(credentialsId: 'admin.kubeconfig', variable: 'KUBECONFIG')]) {
                        script {
                            sh "echo ${deploy}"
                            if (deploy == "upgrade") {
                                sh 'pwd && ls -alt'
                                sh "mkdir -p ~/.kube && cp ${KUBECONFIG} ~/.kube/config"

                                sh returnStatus: true, script: """
                                    helm -n ${namespace} list
                                    helm -n ${namespace} upgrade yinglong ./helm/yinglong \
                                        --set global.image.tag=${package_info.tag_back} \
                                        --set yl-frontend.image.tag=${package_info.tag_front} \
                                        --set global.image.pullPolicy=Always \
                                        --set global.hadoopPrefix=${hadoop_prefix} \
                                        --set global.tenantId=${tenant_id} \
                                        --set global.publicGroup=yinglong \
                                        --set global.nacos.discovery.serverAddrNoHttp=nacos-naming-svc.yinglong:8848 \
                                        --set global.nacos.config.serverAddrNoHttp=nacos-config-svc.yinglong:8848 \
                                        --set 'global.metadata.url=${metadata_table_name}@jdbc\\,driverClassName=com.mysql.jdbc.Driver\\,url=jdbc:mysql://10.1.9.111:3306/kylin?allowMasterDownConnections=true&allowSlavesDownConnections=true&useSSL=false&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8\\,username=yinglong\\,password=cA*BUi#4\\,maxTotal=50\\,maxIdle=8' \
                                        --set 'yl-gateway.image.tag=5.0.1-private' \
                                        --set 'yl-gateway.nacos.serverAddr=nacos-naming-svc.yinglong:8848' \
                                        --set 'yl-gateway.saas.nacos.discovery.group=${tenant_id}' \
                                        --set 'yl-gateway.saas.nacos.discovery.publicGroup=yinglong' ${extra_settings}
                                    helm -n ${namespace} list
                                """
                            } else if (deploy == "install") {
                                sh "echo 'not support now'"
                            } else {
                                sh "echo 'skip deploy'"
                            }
                        }
                    }
                }
            }
        }
    }
}
