#!groovy

@Library('devopslib') _

def modules = [
    ['name': 'ke-common', 'path': 'kyligence/src/ke-common-booter', 'imageName': 'yinglong-common', 'image': ''],
    ['name': 'data-loading', 'path': 'kylin/src/data-loading-booter', 'imageName': 'yinglong-data-loading', 'image': ''],
    ['name': 'query', 'path': 'kylin/src/query-booter', 'imageName': 'yinglong-query', 'image': ''],
    ['name': 'yinglong-smart', 'path': 'kyligence/src/smart-booter', 'imageName': 'yinglong-smart', 'image': '']
]

// 发布分支(前端)
def release_branch_front = ''
// 发布分支(后端)
def release_branch_back = ''
// 前端commitId
def release_commitid_front = ''
// 后端commitId
def release_commitid_back = ''
// 前端镜像tag（版本号）
def release_tag_front = ''
// 后端镜像tag（版本号）
def release_tag_back = ''
//变量名，用于存储input步骤的返回值
def paramsMap = [:]

// 根据发布类型自动获取分支
def getBranch(deployType, envStage, version) {
    print "getBranch -> deployType[${deployType}],envStage[${envStage}],version[${version}]"
    def _result
    def _branch_release = ''
    def _branch_qa = ''
    def _branch_dev = ''
    def branchCollection = ['yinglong']

    switch (deployType) {
        case 'Regular':
            _branch_release = branchCollection[0]
            _branch_qa = "yinglong-${version}-qa"
            _branch_dev = "${_branch_release}-dev"
            break
    }

    switch (envStage) {
        case 'DEV':
            _result = _branch_dev
            break
        case 'QA':
            _result = _branch_qa
            break
        case 'RC':
        case 'GA':
            _result = _branch_release
            break
    }
    echo "getBranch: ${_result}"
    return _result
}

// git获取KE代码（预先触发同步git mirror）
def gitCodeKe(back, front, pMap) {
    def result = [:]
    script {
        println "backend branch/commit: ${back}, frontend branch/commit: ${front}"
        if (!back) {
            error 'commitId_back 参数不能为空'
        }

        if (pMap['back_remote']) {
            githubCheckout 'KAP', back, 'https', 'github.com'
        }else {
            pullCodeFromGitMirror 'KAP', back
        }

        release_commitid_back = sh(returnStdout: true, script: "git rev-parse --short HEAD | sed -e 's/\r//g'").trim()
        println "release_commitid_back: ${release_commitid_back}"
        result.release_commitid_back = release_commitid_back

        def _front
        if (!front) {
            println "No commitId_front, use the commitId_back: ${back}"
            _front = back
        } else {
            println "checkout KAP_Frontend to kystudio, use the commitid: ${front}"
            _front = front
        }

        sh 'ls -lha && ls -lha kystudio'
        sh 'rm -rf kystudio'
        sh 'ls -lha'
        dir('kystudio') {
            sh 'pwd && ls -lha'
            if (pMap['front_remote']) {
                githubCheckout 'KAP_Frontend', _front, 'https', 'github.com'
            }else {
                pullCodeFromGitMirror 'KAP_Frontend', _front
            }

            release_commitid_front = sh(returnStdout: true, script: "git rev-parse --short HEAD | sed -e 's/\r//g'").trim()
            println "release_commitid_front: ${release_commitid_front}"
            result.release_commitid_front = release_commitid_front
            sh """
                rm -f .npmrc
                echo "registry = 'https://repo-ofs.kyligence.com/repository/npm-public/'" > .npmrc
                cat .npmrc
                ls -lha .
            """
        }
    }
    return result
}

pipeline {
    options {
        timeout(time: 4, unit: 'HOURS')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/yaml/jenkins-helm-docker-package-agent.yaml'
        }
    }

    environment {
        repo = 'harbor-ofs.kyligence.com'
        dockerRegistryUrl = "http://${repo}"
        registryCredential = 'harbor-docker'
        common = ''
        data_loading = ''
        query = ''
        smart = ''
        frontend = ''
        release_commitid_back = ''
        release_commitid_front = ''
    }

    parameters {
        choice(name: 'deployWay', choices: 'Auto Select\nManual Select', description: '发布方式: \nAuto Select-根据发布类型自动选择分支; \nManual Select-手动选择分支、CommitId;')
        choice(name: 'deployType', choices: 'Regular\nSP-5.0.x', description: '交付版本流程:\nRegular - 指主线发布\nSP-5.0.x - 指每周的版本发布5.0.x系列')
        string(name: 'version', defaultValue: '5.0.0', description: '填写版本号，格式：5.0.0，5.0.1.1.1，版本号由【数字和 . 】组合，最多5段，必须规范,\n特别提醒：选择QA打包阶段，版本号写错是无法匹配到对应分支的！！！')
        choice(name: 'envStage', choices:'DEV\nQA\nRC\nGA', description:'打包阶段，如果要GA，选择GA进行流程')
        string(name: 'profiles', defaultValue: 'kubernetes,iam', description: '指定的 profile，kubernetes 会打包 yinglong，iam 会添加 iam 的 jar')
        booleanParam(name: 'include_spark', defaultValue:false, description:'是否内置spark包')
        booleanParam(name: 'build', defaultValue:true, description:'是否构建')
        booleanParam(name: 'push', defaultValue:true, description:'推送镜像')
        booleanParam(name: 'deploy', defaultValue:false, description:'部署在 k8s')
        string(name: 'namespace', defaultValue: 'dev', description: 'namespace to deploy')
        string(name: 'hadoop_prefix', defaultValue: 'hadoop-0', description: 'hadoop environment')
        string(name: 'tenant_id', defaultValue: '', description: 'tenant id')
        string(name: 'extra_settings', defaultValue: '', description: 'helm set parameter, each set starts with --set , seprated by space')
    }

    stages {
        stage('1.Pull Code') {
            when {
                environment name: 'build', value: 'true'
            }
            steps {
                container('build') {
                    dir('sourcecode') {
                        script {
                            // 1. 参数检查：version
                            paramsVerify.version(params.version)
                            // 2. 根据分支规则获取分支
                            if (params.deployWay == 'Auto Select') {
                                // 2.1 根据分支流程规则，自动获取代码分支参数
                                def _branch = getBranch(params.deployType, params.envStage, params.version)
                                release_branch_front = _branch
                                release_branch_back = _branch
                                def cms = gitCodeKe(_branch, _branch, paramsMap)
                                release_commitid_back = cms.release_commitid_back
                                release_commitid_front = cms.release_commitid_front
                            } else if (params.deployWay == 'Manual Select') {
                                // 2.2 根据手动输入参数设定分支
                                paramsMap = input(
                                    message: '请选择要开始的版本?',
                                    ok: '确认！',
                                    parameters: [
                                        string(name: 'commitId_back', defaultValue: '', description: '后端Repo(KAP)的branch或者commitid（必填）注：填commitid的时候前端的必填'),
                                        string(name: 'commitId_front', defaultValue: '', description: '前端repo(KAP_Frontend)的branch或者commitid（后端填分支名时，该参数可以不填）'),
                                        booleanParam(name: 'overide', defaultValue: false, description: '全新打包，覆盖现有同名包'),
                                        booleanParam(name: 'back_remote', defaultValue: false, description: '后端拉取远程分支（绕开 git mirror）'),
                                        booleanParam(name: 'front_remote', defaultValue: false, description: '前端拉取远程分支（绕开 git mirror）')
                                    ],
                                    // submitter:'liming.meng,admin',
                                    submitterParameter: 'APPROVER'
                                )
                                release_branch_front = paramsMap['commitId_front']
                                release_branch_back = paramsMap['commitId_back']
                                def cms = gitCodeKe(release_branch_back, release_branch_front, paramsMap)
                                release_commitid_back = cms.release_commitid_back
                                release_commitid_front = cms.release_commitid_front
                            } else {
                                println 'no code pulled'
                            }
                        }
                    }
                }
            }
        }
        stage('2.Building Package') {
            when {
                environment name: 'build', value: 'true'
            }
            steps {
                container('build') {
                    dir('sourcecode') {
                        script {
                            if (include_spark) {
                                sh '''
                                    sh build/script_newten/download-spark.sh
                                '''
                            }

                            if (!profiles) {
                                sh '''
                                    mvn -U clean install -T 4C -DskipTests -Dmaven.compile.fork=true
                                '''
                            } else {
                                sh """
                                    mvn -U clean install -T 4C -DskipTests -Dmaven.compile.fork=true -P ${profiles}
                                """
                            }

                            for (m in modules) {
                                dir(m.path) {
                                    sh """
                                        pwd
                                        ls -al
                                        cp ${env.WORKSPACE}/docker/yinglong-jdk8/Dockerfile Dockerfile
                                        sed -i "s#&&replace_package&&#target/${m.name}*.tar.gz#g" Dockerfile
                                        sed -i "s#&&replace_dir&&#${m.name}#g" Dockerfile
                                        cat Dockerfile
                                    """
                                }
                            }
                        }
                    }
                }
            }
        }
        stage('3.build docker image') {
            when {
                environment name: 'push', value: 'true'
            }
            parallel {
                stage('3.1.image front') {
                    steps {
                        container('docker') {
                            dir('sourcecode') {
                                script {
                                    dir('kystudio') {
                                        sh """
                                            pwd
                                            ls -alt
                                            cat .npmrc
                                            rm -f .npmrc
                                            echo "registry = 'https://repo-ofs.kyligence.com/repository/npm-public/'" > .npmrc
                                            cat .npmrc
                                        """
                                        frontend = docker.build('yinglong/yinglong-frontend', "-f ${env.WORKSPACE}/docker/nginx-node-10.24.1/Dockerfile .")
                                    }
                                }
                            }
                        }
                    }
                }
                stage('3.2.images') {
                    steps {
                        container('docker') {
                            script {
                                for (m in modules) {
                                    dir("sourcecode/${m.path}") {
                                        retry(2) {
                                            m.image = docker.build("yinglong/${m.imageName}")
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        stage('4.push images') {
            when {
                environment name: 'push', value: 'true'
            }
            steps {
                container('docker') {
                    script {
                        println "release_commitid_front: ${release_commitid_front}"

                        release_tag_front = "${params.envStage}-${release_commitid_front}"
                        if (params.envStage == 'GA') {
                            release_tag_front = params.version
                        }

                        println "release_tag_front: ${release_tag_front}"
                        retry(2) {
                            docker.withRegistry(dockerRegistryUrl, registryCredential) {
                                frontend.push(release_tag_front)
                                frontend.push('latest')
                            }
                        }

                        release_tag_back = "${params.envStage}-${release_commitid_back}"
                        if (params.envStage == 'GA') {
                            release_tag_back = params.version
                        }
                        println "release_tag_back: ${release_tag_back}"
                        for (m in modules) {
                            retry(2) {
                                docker.withRegistry(dockerRegistryUrl, registryCredential) {
                                    m.image.push(release_tag_back)
                                    m.image.push('latest')
                                }
                            }
                        }
                    }
                }
            }
        }
        stage('5.deploy') {
            when {
                environment name: 'deploy', value: 'true'
            }
            steps {
                echo 'Up in K8S at office env'
                container('helm') {
                    withCredentials([file(credentialsId: 'kubeconfig', variable: 'KUBECONFIG')]) {
                        script {
                            sh 'pwd && ls -alt'
                            sh "mkdir -p ~/.kube && cp ${KUBECONFIG} ~/.kube/config"

                            try {
                                sh returnStatus: true , script: """
                                    helm -n ${namespace} list
                                    helm -n ${namespace} uninstall yinglong
                                """
                            } catch (Exception err) {
                                echo err.getMessage()
                                echo 'delete resource failed, but we will continue.'
                            }

                            sh returnStatus: true , script: """
                                helm -n ${namespace} install yinglong ./helm/yinglong
                                    --set yinglong-common.image.tag=${release_tag_back}
                                    --set yinglong-data-loading.image.tag=${release_tag_back}
                                    --set yinglong-query.image.tag=${release_tag_back}
                                    --set yinglong-smart.image.tag=${release_tag_back}
                                    --set yinglong-frontend.image.tag=${release_tag_front}
                                    --set global.hadoopPrefix=${hadoop_prefix}
                                    --set global.tenantId=${params.tenant_id} ${params.extra_settings}
                                helm -n ${namespace} list
                            """
                        }
                    }
                }
            }
        }
    }
}
