{{- if or (eq .Values.function_mode "all") (eq .Values.function_mode "naming") }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nacos.fullname" . }}-naming
  labels:
    {{- include "nacos.labels" . | nindent 4 }}
spec:
  podManagementPolicy: {{ .Values.naming.podManagementPolicy }}
  {{- if not .Values.naming.autoscaling.enabled }}
  replicas: {{ .Values.naming.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.naming.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "nacos.selectorLabels" . | nindent 6 }}
      app: {{ include "nacos.fullname" . }}-naming
  serviceName: {{ include "nacos.fullname" . }}-naming-headless
  template:
    metadata:
      {{- with .Values.naming.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nacos.selectorLabels" . | nindent 8 }}
        app: {{ include "nacos.fullname" . }}-naming
    spec:
      {{- with .Values.naming.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.naming.podSecurityContext | nindent 8 }}
      {{- if .Values.skyWalking.enabled }}
      volumes:
        - name: skywalking-agent
          emptyDir: { }
      {{- end }}
      initContainers:
      - name: "mysql-init"
        image: busybox:1.31
        command: ['sh', '-c', "until telnet $MYSQL_SERVICE_HOST $MYSQL_SERVICE_PORT; do echo waiting for mysql; sleep 20; done;"]
        env:
          - name: MYSQL_SERVICE_PORT
            valueFrom:
              configMapKeyRef:
                key: MYSQL_SERVICE_PORT
                name: {{ include "nacos.fullname" .}}-naming-cm
          - name: MYSQL_SERVICE_HOST
            valueFrom:
              configMapKeyRef:
                key: MYSQL_SERVICE_HOST
                name: {{ include "nacos.fullname" .}}-naming-cm
      {{- if .Values.skyWalking.enabled }}
      - name: agent-container
        image: apache/skywalking-java-agent:8.7.0-alpine
        volumeMounts:
          - name: skywalking-agent
            mountPath: /agent
        command: [ "/bin/sh" ]
        args: [ "-c", "cp -R /skywalking/agent /agent/" ]
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-naming
          securityContext:
            {{- toYaml .Values.naming.securityContext | nindent 12 }}
          image: "{{ .Values.naming.image.repository }}:{{ .Values.naming.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.naming.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.naming.service.port }}
              name: client
              protocol: TCP
            - containerPort: {{ .Values.naming.service.port | int | add 1000 }}
              name: client-rpc
              protocol: TCP
            - containerPort: {{ .Values.naming.service.port | int | add 1001 }}
              name: raft-rpc
              protocol: TCP
            - containerPort: {{ .Values.naming.service.port | int | add -1000 }}
              name: old-raft-rpc
              protocol: TCP
          resources:
            {{- toYaml .Values.naming.resources | nindent 12 }}
          env:
            - name: NACOS_REPLICAS
              value: "{{ .Values.naming.replicaCount }}"
            - name: MYSQL_SERVICE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_SERVICE_DB_NAME
                  name: {{ include "nacos.fullname" .}}-naming-cm
            - name: MYSQL_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_SERVICE_PORT
                  name: {{ include "nacos.fullname" .}}-naming-cm
            - name: MYSQL_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_SERVICE_HOST
                  name: {{ include "nacos.fullname" .}}-naming-cm
            - name: MYSQL_SERVICE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "nacos.fullname" . }}-naming-secret
                  key: MYSQL_SERVICE_USER
            - name: MYSQL_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "nacos.fullname" . }}-naming-secret
                  key: MYSQL_SERVICE_PASSWORD
            - name: NACOS_SERVER_PORT
              value: "{{ .Values.naming.service.port }}"
            - name: NACOS_APPLICATION_PORT
              value: "{{ .Values.naming.service.port }}"
            - name: PREFER_HOST_MODE
              value: hostname
            - name: NACOS_SERVERS
              value: "{{ include "nacos.nacosServers" . }}"
            - name: FUNCTION_MODE
              value: "naming"
            {{- if .Values.skyWalking.enabled }}
            - name: JAVA_OPT
              value: "-javaagent:/skywalking/agent/skywalking-agent.jar"
            - name: SW_AGENT_NAME
              value: "{{ include "nacos.fullname" . }}-naming"
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "{{ .Values.skyWalking.backendServerAddr }}"
            {{- end }}
          volumeMounts:
            - name: skywalking-agent
              mountPath: /skywalking
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
      {{- with .Values.naming.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.naming.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.naming.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}