#!groovy

@Library('devopslib') _

def branch_name = 'master'

pipeline {
    options {
        timeout(time: 2, unit: 'HOURS')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/yaml/jenkins-package-agent.yaml'
        }
    }

    parameters {
        choice(name: 'moduleName',
                choices: ['sqlAdaptor', 'cognosAdaptor', 'tableRouter'],
                description: 'cognos SQL Adaptor & App zen Query Router 自动化验证，发布手册请查看: https://kyligence.feishu.cn/base/bascnDWvIuA3P5j4X8h6IhhNqRe?table=tblnC81M6a7e290d&view=vewlyywfcu')
        string(name: 'KEVersion', defaultValue: '4.5.17.0', description: '指定 KE 的版本')
        string(name: 'toMail', defaultValue: 'fanfan.li@kyligence.io', description: '将函数对比结果发送给此人')
    }

    environment {
        ENVIRONMENT_TEST_FLAG = 'NO'
    }

    stages {
        stage("Checkout Source Code") {
            steps {
                container("build") {
                    dir("SQLAdaptor") {
                        script {
                            retry(3) {
                                githubCheckout 'bi-adapter', 'master', 'https', 'github.com', '+refs/pull/*:refs/remotes/origin/pr/* +refs/heads/*:refs/remotes/origin/*', 'kyligence-git', 'Kyligence'
                            }
                        }
                    }
                }
            }
        }
        stage('Maven Install') {
            steps {
                container("build") {
                    sh "cat /root/.m2/settings.xml"
                    dir("SQLAdaptor") {
                        script {
                            sh script: """
                                    git branch
                                    mvn clean install -DskipTests
                                    mvn clean install -pl cognosAdaptor
                                    mvn clean install -pl tableRouter
                                """
                        }
                    }
                }
            }
        }
        stage('copy_file_to_remote') {
            steps {
                container('build') {
                    dir("SQLAdaptor") {
                        timestamps {
                            script {
                                cmd = "rm -rf /opt/SQLAdaptor"
                                echo "cmd: ${cmd}"
                                sshCmdWithCredentials(
                                        cmd,
                                        'shuiaileiroot',
                                        ['name': 'localhost', 'host': '10.1.2.181', 'allowAnyHosts': true]
                                )
                            }
                            script {
                                def remote = [:]
                                def file_name = "./../SQLAdaptor"
                                def remote_path = "/opt"
                                def remote_ip = "10.1.2.181"
                                remote.name = 'server_test_env'
                                def credentials = "shuiaileiroot"
                                withCredentials([usernamePassword(credentialsId: credentials,
                                        usernameVariable: 'REMOTE_USERNAME',
                                        passwordVariable: 'REMOTE_PASSWORD')]) {
                                    remote.user = REMOTE_USERNAME
                                    remote.password = REMOTE_PASSWORD
                                }
                                remote.host = remote_ip
                                remote.allowAnyHosts = true
                                sshPut remote: remote, from: file_name, into: remote_path
                                sshCommand remote: remote, command: """
                    ls -lh ${remote_path}
                """
                            }
                        }
                    }
                }
            }
        }
        stage('test_prepare') {
            steps {
                container("build") {
                    dir("SQLAdaptor") {
                        script {
                            def installDir = "/opt"
                            def keVersion = "${params.KEVersion}"
                            def host = "10.1.2.181"
                            def cognosAdaptorVersion = sh(script: " mvn help:evaluate -Dexpression=sub.version -pl cognosAdaptor | grep -v \"INFO\" | grep -v \"WARNING\" | tail -n 1 ", returnStdout:true).trim()
                            def tableRouterVersion = sh(script: " mvn help:evaluate -Dexpression=sub.version -pl tableRouter | grep -v \"INFO\" | grep -v \"WARNING\" | tail -n 1 ", returnStdout:true).trim()
                            cmd = "sh " + installDir + "/SQLAdaptor/benchmark/src/main/resources/script/prepareKEEnvironment.sh  " + keVersion + " " + cognosAdaptorVersion + " " + tableRouterVersion
                            echo "cmd: ${cmd}"
                            sshCmdWithCredentials(
                                    cmd,
                                    'shuiaileiroot',
                                    ['name': 'localhost', 'host': host, 'allowAnyHosts': true]
                            )
                            echo "ssh cmd send success"
                            echo "Listen for the KE running status"
                            def url = "http://10.1.2.181:7079/kylin/api/system/license"
                            def i = 0
                            retry(10) {
                                echo "Get KE Status ${++i} "
                                try {
                                    def response = httpRequest     \
                                                httpMode: 'GET',
                                            contentType: 'APPLICATION_JSON',
                                            url: url
                                    def status = response.status
                                    echo "status: ${status}"
                                } catch (e) {
                                    sleep(time: 30, unit: "SECONDS")
                                    echo "check KE status exception: ${e}"
                                    sh 'exit 1'
                                }
                            }
                        }
                    }
                }
            }
        }
        stage('testCognosAdaptor') {
            steps {
                container("build") {
                    dir("SQLAdaptor") {
                        sh script: """
                            mvn test -Dspring.profiles.active=cognosAdaptor -Dapi.kylin.url=http://10.1.2.181:7079 -Dmail.to=${params.toMail} -Dtest=io.kyligence.kap.TestCI#testCognosAdaptorCI -pl benchmark
                        """
                    }
                }
            }
        }

        stage('testTableRouter') {
            steps {
                container("build") {
                    dir("SQLAdaptor") {
                        sh script: """
                            mvn test -Dspring.profiles.active=tableRouter -Dapi.kylin.url=http://10.1.2.181:7079 -Dmail.to=${params.toMail} -Dtest=io.kyligence.kap.TestCI#testQueryRouterCI -pl benchmark
                        """
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                container("build") {
                    dir("SQLAdaptor") {
                        script {
                            sh script: """
                                   sh benchmark/src/main/resources/script/deployRelease.sh ${params.KEVersion}
                                """
                        }
                    }
                }
            }
        }

        stage("doTag") {
            steps {
                container("build") {
                    dir("SQLAdaptor") {
                        script {
                            def sdkVersion = ''
                            if (params.moduleName == 'sqlAdaptor') {
                                sdkVersion = sh(script: " mvn help:evaluate -Dexpression=revision | grep -v \"INFO\" | grep -v \"WARNING\" | tail -n 1 ", returnStdout:true).trim()
                            } else {
                                sdkVersion = sh(script: " mvn help:evaluate -Dexpression=sub.version -pl ${params.moduleName} | grep -v \"INFO\" | grep -v \"WARNING\" | tail -n 1 ", returnStdout:true).trim()
                            }
                            echo "sdkVersion: ${sdkVersion}"
                            if (!sdkVersion.contains("-SNAPSHOT")) {
                                def _tag = "v-" + params.moduleName + "-" + sdkVersion
                                githubHelper 'TAG', branch_name, 'bi-adapter', _tag
                            }
                        }
                    }
                }
            }
        }
    }
}
