apiVersion: v1
kind: Service
metadata:
  name: {{ print (include "kyligence-enterprise.fullname" . ) "-" .Values.version }}
  labels:
    {{- include "kyligence-enterprise.labels" . | nindent 4 }}
    metrics-exporter: prometheus
spec:
  selector:
    app: {{ print (include "kyligence-enterprise.fullname" . ) "-" .Values.version }}
  ports:
  - port: 8080
    name: metrics
  - name: "http"
    port: 7070
    targetPort: 7070
  - name: "spark-ui"
    port: 4041
    targetPort: 4041