#!groovy

@Library('devopslib') _

pipeline {
    options {
        timeout(time: 3, unit: 'HOURS')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/yaml/jenkins-agent-aws-ci.yaml'
        }
    }

    parameters {
        string(name: 'branch', defaultValue: '', description: 'Kap branch?')
        string(name: 'args', defaultValue: '', description: 'Extra JVM options for maven test')
        string(name: 'sha1', defaultValue: '', description: '')
    }

    stages {
        stage('Checkout Source Code') {
            steps {
                container('git') {
                    dir('sourcecode') {
                        timestamps {
                            quicklyCheckout()
                        }
                        s3Archive('download')
                    }
                }
            }
        }
        stage('Maven Install') {
            steps {
                container('maven') {
                    dir('sourcecode') {
                        timestamps {
                            retry(3) {
                                sh script: 'mvn -U clean install -T 2C -Dmaven.compile.fork=true -DskipTests'
                            }
                        }
                    }
                }
            }
        }
        stage('Testing') {
            steps {
                script {
                    dynamicNewtenParallelTest()
                }
            }
            post {
                always {
                    timestamps {
                        junit skipPublishingChecks: true, testResults: '*Test-Stage-*/**/target/surefire-reports/*.xml'
                    }
                    s3Archive('upload-without-build_result')
                }
            }
        }
        stage('SonarCloud') {
            steps {
                sonarAnalyze("""-Dsonar.pullrequest.base=${ghprbTargetBranch} \
                                -Dsonar.pullrequest.branch=${ghprbSourceBranch} \
                                -Dsonar.pullrequest.key=${ghprbPullId} \
                                -Dsonar.projectKey=Kyligence_KAP """)
            }
        }
    }
}

def quicklyCheckout() {
    if (params.sha1) {
        println "checkout from pull request."
        def pullNumber = matchPullNumber(params.sha1)
        checkout([$class: 'GitSCM', branches: [[name: params.sha1]], extensions: [[$class: 'CloneOption', depth: 1, honorRefspec: true, noTags: true, reference: '', shallow: true, timeout: 3]], userRemoteConfigs: [[credentialsId: 'kyligencegit', name: 'origin', refspec: "+refs/pull/${pullNumber}/*:refs/remotes/origin/pr/${pullNumber}/*", url: 'https://github.com/Kyligence/KAP.git']]])
    } else if (params.branch) {
        println "checkout from specified branch."
        checkout([$class: 'GitSCM', branches: [[name: params.branch]], extensions: [[$class: 'CloneOption', depth: 1, honorRefspec: true, noTags: true, reference: '', shallow: true, timeout: 3]], userRemoteConfigs: [[credentialsId: 'kyligencegit', name: 'origin', refspec: "+refs/heads/${params.branch}:refs/remotes/origin/${params.branch}", url: 'https://github.com/Kyligence/KAP.git']]])
    } else {
        throw new RuntimeException("unknown branch")
    }
}

@NonCPS
def matchPullNumber(String sha1) {
    def m = sha1 =~ /^origin\/pr\/(\d+)\/merge$/
    if (!m) {
        throw new RuntimeException("invalid sha1")
    }
    return m.group(1)
}
