#!groovy

@Library('devopslib') _

def replaceRepo() {
    sh """
        env
        sed -i 's#https://repo-ofs.kyligence.com#http://devops-nexus:8081#g' pom.xml
        sed -i 's#https://repository.kyligence.io#http://devops-nexus:8081#g' pom.xml
        cat pom.xml
    """
}

pipeline {
    options {
        timeout(time: 3, unit: 'HOURS')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/yaml/jenkins-agent-aws-ci.yaml'
        }
    }

    parameters {
        string(name: 'branch', defaultValue: '', description: 'Kap branch?')
        string(name: 'args', defaultValue: '', description: 'Extra JVM options for maven test')
    }

    stages {
        stage('Checkout Source Code') {
            steps {
                container('git') {
                    dir('sourcecode') {
                        script {
                            sh 'env'
                            githubCheckout 'KAP', params.branch, 'https', 'github.com', '+refs/pull/*:refs/remotes/origin/pr/* +refs/heads/*:refs/remotes/origin/*', 'kyligencegit'
                            // replaceRepo()

                            def prNo = ghprbCommentBody.minus('retest this please with ').trim()
                            def prBranch = ghprbTargetBranch
                            if (!prNo) {
                                if (prNo.isNumber()) {
                                    prBranch = "origin/pr/${prNo}/merge"

                                    // 替换 kylin 文件夹
                                    println("merge the PR ${prNo} with kylin which is splited repo, prBranch: ${prBranch}")
                                    sh 'ls -lha && ls -lha kylin'
                                    sh 'rm -rf kylin'
                                    dir('kylin') {
                                        sh 'pwd && ls -lha'
                                        githubCheckout 'kylin', prBranch, 'https', 'github.com', '+refs/pull/*:refs/remotes/origin/pr/* +refs/heads/*:refs/remotes/origin/*', 'kyligencegit'
                                        // replaceRepo()
                                    }
                                    sh 'ls -lha && ls -lha kylin'
                                } else {
                                    println('use build-in code in the folder kylin')
                                }
                            } else {
                                println("use build-in code in the folder kylin, prNo: ${prNo}")
                            }
                        }
                        s3Archive4YingLong('download')
                    }
                }
            }
        }
        stage('Maven Install') {
            steps {
                container('maven') {
                    dir('sourcecode') {
                        script {
                            retry(3) {
                                sh script: 'mvn -U clean install -T 2C -Dmaven.compile.fork=true -DskipTests'
                            }
                        }
                    }
                }
            }
        }
        stage('Testing') {
            steps {
                script {
                    dynamicNewtenParallelTest()
                }
            }
            post {
                always {
                    timestamps {
                        junit skipPublishingChecks: true, testResults: '*Test-Stage-*/**/target/surefire-reports/*.xml'
                    }
                    s3Archive4YingLong('upload-without-build_result')
                }
            }
        }
        stage('SonarCloud') {
            steps {
                sonarAnalyze("""-Dsonar.pullrequest.base=${ghprbTargetBranch} \
                                -Dsonar.pullrequest.branch=${ghprbSourceBranch} \
                                -Dsonar.pullrequest.key=${ghprbPullId} \
                                -Dsonar.projectKey=Kyligence_KAP """)
            }
        }
    }
}
