apiVersion: v1
kind: Service
metadata:
  namespace: <<<namespace>>>
  name: kyligence-enterprise
  labels:
    metrics-exporter: prometheus
spec:
  selector:
    app: kyligence-enterprise
  clusterIP: None
  ports:
  - port: 8080
    name: metrics
---
apiVersion: v1
kind: Service
metadata:
  namespace: <<<namespace>>>
  name: kyligence-enterprise-ui
spec:
  selector:
    app: kyligence-enterprise
  ports:
    - name: "http"
      port: 7070
      targetPort: 7070
    - name: "spark-ui"
      port: 4040
      targetPort: 4040
