#!groovy

@Library('devopslib') _

def package_info = [:]
def releaseVersion = '' //最后发布的版本号
def releaseName = ''
def publishToKC = false //是否发布给KC

def getPackageInfo(releaseVersion,packageType) {
    println "getPackageInfo -> releaseVersion[${releaseVersion}],packageType[${packageType}]"
    def file_name = ''
    def package_path = ''
    def releaseName = releaseVersion.replace('-kylin', '')
    switch(packageType) {
        case 'on-perm-hadoop2':
            file_name = "spark-newten-${releaseName}-hadoop2.tgz"
            break
        case 'on-perm-nohadoop':
            file_name = "spark-newten-${releaseName}.tgz"
            break
        case 'cloud-aws':
        case 'cloud-azure':
        case 'cloud-gcp':
        case 'cloud-huawei':
            file_name = "spark-newten-${releaseName}-${packageType}.tgz"
            break
    }
    package_path = "/var/cicd/spark/${releaseName}"
    def obj = [:]
    obj.package_path = package_path
    obj.file_name = file_name
    obj.releaseName = releaseName
    println obj.toString()
    return obj
}

def checkCacheExist(pi) {
    println "checkCacheExist -> package_info[${pi}]"
    def result = false
    try {
        def existPackage = "${pi.package_path}/${pi.file_name}"
        sh script: """
            ls -l /var/cicd/${pi.package_path}
            cp /var/cicd/${existPackage} ${pi.file_name}
        """

        sh 'ls -l'
        // println "pi.package_file: ${pi.package_file}"
        result = fileExists(pi.file_name)
        println "/var/cicd/${pi.package_path}/${pi.file_name} is ${result}"
    } catch (Exception err) {
        println "The package [${pi.file_name}] not exsits, the pipeline will make it next."
        result = false
        // println err.getMessage()
    }

    println "checkCacheExist result: ${result}"
    return result
}

// 上传制品包到Aws S3存储
def uploadAwsS3(region, credentials, bucket, path, ga_name) {
    timestamps {
        println("uploadAwsS3 -> path: ${path}, ga_name: ${ga_name}, retry 3 times")
        withAWS(region: region, credentials: credentials) {
            retry(3) {
                // s3Upload(bucket: bucket, path: path, file: ga_name)
                sh """
                    ls -alt /jenkins-common/jobs/${env.JOB_NAME}/
                    aws s3 cp /jenkins-common/jobs/${env.JOB_NAME}/${ga_name} s3://$bucket/${path}/ --acl public-read
                """
            }
        }
    }
}

def getReleaseVersion(version, deployType) {
    def _result
    _result = version
    switch (deployType) {
        case 'DEV':
            _result = _result + '-DEV-SNAPSHOT'
            break
        case 'QA':
            _result = _result + '-SNAPSHOT'
            break
    }
    return _result.trim()
}

// git获取spark 代码（预先触发同步git mirror）
def gitSparkCodeKe(repo, branch) {
    script {
        if (repo == 'Kyligence') {
            pullCodeFromGitMirror 'spark', branch
        } else {
            githubCheckout 'spark', branch, 'https', 'github.com', '+refs/heads/*:refs/remotes/origin/*', 'kyligence-git', repo
        }
    }
}

def generateCloudPackage(waitTime, cloudType, dependencyDir, releaseVersion) {
    def releaseName = releaseVersion.replace('-kylin', '')
    //kc 使用的的log4j jar 与本地略有区别，这里需要特殊处理 参见 https://olapio.atlassian.net/browse/KE-34130
    //https://olapio.atlassian.net/browse/KE-34066 配置方式也与本地略有区别
    //https://olapio.atlassian.net/browse/KC-12372 delete slf4j-log4j12
    def pi = getPackageInfo(releaseVersion, cloudType)
    if(!checkCacheExist(pi)) {
        sh script: """
            sleep ${waitTime}
            export MAVEN_OPTS="-Xmx4g -XX:ReservedCodeCacheSize=1g -Xss128m"
            dev/make-distribution.sh --name ${releaseVersion} -Phadoop-3.2 -Phive-thriftserver -pl assembly
            cp ../depedencies/log4j/*.jar dist/jars/
            cp ../depedencies/cloud_log4j/*.jar dist/jars/
            rm  dist/jars/log4j-1.2-api-*.jar
            rm  dist/jars/slf4j-log4j12*.jar
            cp -r ../hive_1_2_2  dist/
            cp ../depedencies/${dependencyDir}/* dist/jars/
            cp ../depedencies/log4j/spark-executor-log4j.xml dist/conf/spark-executor-log4j.xml
            #https://olapio.atlassian.net/browse/KC-13052,special handle for azure
            if [ 'cloud-azure' = '${cloudType}' ]; then
                cp dist/jars/azure-identity-extensions*.jar dist/hive_1_2_2/ || :
                cp dist/jars/mysql-connector*.jar dist/hive_1_2_2/ || :
                cp dist/jars/postgresql*.jar dist/hive_1_2_2/ || :
            fi
            mv dist ${pi.filename}
            tar czf ${pi.filename}.tgz ${pi.filename}
        """

        sh script: """
            mkdir -p ${pi.package_path}
            cp ${pi.filename}.tgz ${pi.package_path}
        """
        // withCredentials([usernamePassword(credentialsId: 'nexus-raw', passwordVariable: 'passwd', usernameVariable: 'user')]) {
        //     pushRawArtifactsByApi('raw-tars-hosted', 'io.kyligence.spark', "spark-newten-${releaseName}-${cloudType}.tgz", "spark-newten-${releaseName}-${cloudType}.tgz", user, passwd)
        // }
        // uploadAwsS3('us-west-2', 'aws_global_s3_cp', 'kyligencecloud-ci', "packages/spark-cloud/spark-newten-${releaseName}-${cloudType}.tgz", "spark-newten-${releaseName}-${cloudType}.tgz")
    } else {
        echo "${pi.filename} Is Existed"
        sh "cp ${pi.package_path}/${pi.filename} ."
    }
}

def uploadCloudPackage(releaseVersion,deployType,packageType,uploadOnly=false,uploadS3=true) {
    println "uploadCloudPackage -> releaseVersion[${releaseVersion}],deployType[${deployType}],packageType[${packageType},uploadOnly[${uploadOnly},uploadS3[${uploadS3}]"
    dir(packageType) {
        script {
            def _releaseVersion = getReleaseVersion(releaseVersion,deployType)
            def _releaseName = _releaseVersion.replace('-kylin', '')
            def _packageInfo =  getPackageInfo(_releaseName, packageType)
            
            if(uploadOnly) {
                sh """
                    wget https://repo-ofs.kyligence.com/repository/raw-tars-hosted/io.kyligence.spark/${_packageInfo.filename} --no-check-certificate
                """
            } else {
                retry(3) {
                    // withCredentials([usernamePassword(credentialsId: 'nexus-raw', passwordVariable: 'passwd', usernameVariable: 'user')]) {
                    //     pushRawArtifactsByApi('raw-tars-hosted', 'io.kyligence.spark', _package, _package, user, passwd)
                    // }
                    uploadHelper.uploadNexus(_packageInfo.filename, 'io.kyligence.spark', 'raw-tars-hosted', packageType)
                }
            }
            if(uploadS3){
                uploadAwsS3('us-west-2', 'aws_global_s3_cp', 'kyligencecloud-ci', "packages/spark-cloud/${_packageInfo.filename}", _packageInfo.filename)
            }
        }
    }
}

def deployJars(releaseVersion,deployType,sparkVersion,envProfile) {
    println "deployJars -> releaseVersion[${releaseVersion}],deployType[${deployType}],sparkVersion[${sparkVersion}],publishToKC[${publishToKC}],envProfile[${envProfile}]"
    script {
        def _releaseVersion = getReleaseVersion(releaseVersion, deployType)
        def kubernetesParm = '-Pkubernetes'
        if (sparkVersion == 'spark2.2') {
            kubernetesParm = ''
        }
        retry(3) {
            sh script: """
                export MAVEN_OPTS="-Xmx4g -XX:ReservedCodeCacheSize=1g -Xss128m"
                mvn versions:set -DnewVersion=${_releaseVersion}
                mvn -T 2C deploy -P${envProfile} -Phadoop-provided -Phive-provided -Phive-thriftserver -Pyarn ${kubernetesParm} -DskipTests=true
            """
        }
    }
}

def buildPackage(releaseVersion,deployType,sparkVersion,envProfile) {
    println "buildPackage -> releaseVersion[${releaseVersion}],deployType[${deployType}],sparkVersion[${sparkVersion}],publishToKC[${publishToKC}],envProfile[${envProfile}]"
    script {
        def _releaseVersion = getReleaseVersion(releaseVersion, deployType)
        def kubernetesParm = '-Pkubernetes'
        if (sparkVersion == 'spark2.2') {
            kubernetesParm = ''
        }
        retry(3) {
            sh script: """
                export MAVEN_OPTS="-Xmx8g -XX:ReservedCodeCacheSize=2g -Xss1g"
                mvn versions:set -DnewVersion=${_releaseVersion}
                mvn -T 2C clean install -U -P${envProfile} -Phadoop-provided -Phive-provided -Phive-thriftserver -Pyarn ${kubernetesParm} -DskipTests=true
            """
        }
    }
}

pipeline {
    options {
        timeout(time: 12, unit: 'HOURS')
        ansiColor('xterm')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/yaml/jenkins-spark-agent.yaml'
        }
    }

    parameters {
        string(name: 'repo', defaultValue: 'Kyligence', description: 'spark repo  https://github.com/Kyligence/spark.git--> Kyligence\nhttps://github.com/apache/spark.git--> apache')
        string(name: 'branch', defaultValue: 'kyspark-3.2.x-4.x', description: 'spark branch  \n kyspark-2.4.1.x-4.x \n kyspark-3.2.x-4.x \n kyspark-2.2.1.x-3.x ')
        string(name: 'release_version', defaultValue: '', description: 'spark release version for example: 3.2.0-kylin-4.5.16.0')
        choice(name: 'deployType', choices: 'DEV\nQA\nGA', description: '研发自测用自己分支打包，选择DEV，会在version后面加上 -DEV-SNAPSHOT，并且不会发包给kc，\n' +
                '进代码后基于dev分支发布，选择QA，会在version后面加上 -SNAPSHOT\n GA后基于稳定分支发包，选择GA，version 不做处理')
        choice(name: 'sparkVersion', choices: 'spark3\nspark2.4\nspark2.2', description: 'spark 大版本，spark2.4/2.2 发包不会推到云上')
        string(name: 'cloud_dependency_path', defaultValue: 'cloud-dependency/current', description: 'cloud denpendency directory in repo-ofs,\n 这个路径是制品库spark 目录下的子目录,该目录下必须有depedencies.tar.gz 文件，可以选择旧包的目录打旧版本的spark 包，eg:cloud-dependency/4.6.4.0\n 4.5稳定版发版请用cloud-dependency/4.5.x-current')
        // booleanParam(name: 'deploy_to_ofs', defaultValue: true, description: '默认勾选，取消勾选时跳过本地repo-ofs deploy 以节省时间')
        booleanParam(name: 'deploy_jars', defaultValue: true, description: '默认勾选，取消勾选时跳过本地repo-ofs deploy 以节省时间')
        booleanParam(name: 'deploy_to_kylin', defaultValue: true, description: '勾选时，将会将spark 推送到public repo，供kylin用户使用,重试的时候可以跳过这一步节省时间')
        booleanParam(name: 'deploy_to_aws', defaultValue: false, description: '勾选时，将会将spark 推送到aws repo，供CI使用,重试的时候可以跳过这一步节省时间')
        booleanParam(name: 'publishToKC', defaultValue: false, description: '勾选时，会打云上的包给KC用, 如果只打on promise 包可以取消勾选')
        booleanParam(name: 'upload_only', defaultValue: false, description: '勾选时，将会跳过 deploy jar 包到制品库，并获取repo-ofs raw 中对应版本 tar 包上传到 S3')
    }

    stages {
        stage('approve deploy DI OR Manager') {
            when {
                expression {
                    return params.deployType == 'GA'
                }
            }
            steps {
                container('build') {
                    script {
                        releaseVersion = getReleaseVersion(params.release_version, params.deployType)
                        def checkMsg = "DI部门，确定发布该版本吗？发布repo：${params.repo}, 发布分支：${params.branch}，发布版本号：${releaseVersion}"
                        println checkMsg
                        paramsGA = input(
                                message: checkMsg,
                                ok: '确认！',
                                submitter: 'jiawei.li2,chenliang.lu,biaobiao.sun,luoping.zhang,lu.cao,meixiu.chen,liming.meng',
                                submitterParameter: 'APPROVER'
                        )
                    }
                }
            }
        }
        stage('Checkout Source Code') {
            when {
                expression {
                    return !params.upload_only
                }
            }
            steps {
                container('build') {
                    dir('sourcecode') {
                        gitSparkCodeKe(params.repo, params.branch)
                    }

                    script {
                        releaseVersion = getReleaseVersion(params.release_version, params.deployType)
                        releaseName = releaseVersion.replace('-kylin', '')
                        if (params.sparkVersion == 'spark3' && params.publishToKC) {
                            publishToKC = true
                        }
                        if(params.deploy_to_kylin){
                            sh script: """
                                cp -r sourcecode ./sourcecode2
                                ls -alt sourcecode2
                            """
                        }
                        sh "cp -r sourcecode ./sourcecode3"
                    }
                    sh script: """
                        wget https://repo-ofs.kyligence.com/repository/raw-public/io.kyligence.spark/${params.cloud_dependency_path}/depedencies.tar.gz
                        tar zxf depedencies.tar.gz
                        wget https://s3.cn-north-1.amazonaws.com.cn/download-resource/kyspark/hive_1_2_2.tar.gz
                        tar zxf hive_1_2_2.tar.gz
                    """
                }
            }
        }
        stage('Build') {
            steps {
                container('build') {
                    dir('sourcecode') {
                        def piHadoop = getPackageInfo(params.release_version, 'on-perm-hadoop2')
                        def piNohadoop = getPackageInfo(params.release_version, 'on-perm-nohadoop')
                        if(!checkCacheExist(piHadoop) || !checkCacheExist(piNohadoop)) {
                            buildPackage(params.release_version, params.deployType, params.sparkVersion, 'dev')
                        }
                    }

                    script {
                        sh script: '''
                            cp -r sourcecode ./on-perm-hadoop2
                        '''
                        if(publishToKC) {
                            sh script: '''
                                cp -r sourcecode ./on-perm-nohadoop
                                cp -r sourcecode ./cloud-azure
                                cp -r sourcecode ./cloud-aws
                                cp -r sourcecode ./cloud-gcp
                                cp -r sourcecode ./cloud-huawei
                            '''
                        }
                    }
                }
            }
        }
        stage('Deploy') {
            when {
                expression {
                    return !params.upload_only && params.deploy_jars
                }
            }
            parallel {
                stage('1.to Ofs') {
                    steps {
                        container('build') {
                            dir('sourcecode') {
                                deployJars(params.release_version, params.deployType, params.sparkVersion, 'dev')
                            }
                        }
                    }
                }
                stage('2.to AWS CI') {
                    when {
                        expression {
                            return params.deploy_to_aws
                        }
                    }
                    steps {
                        container('build3') {
                            dir('sourcecode3') {
                                deployJars(params.release_version, params.deployType, params.sparkVersion, 'aws')
                            }
                        }
                    }
                }
                stage('3.to Open Source') {
                    when {
                        expression {
                            return params.deploy_to_kylin
                        }
                    }
                    steps {
                        container('build2') {
                            dir('sourcecode2') {
                                deployJars(params.release_version, params.deployType, params.sparkVersion, 'pro')
                            }
                        }
                    }
                }
            }
        }
        stage('Package') {
            when {
                expression {
                    return !params.upload_only
                }
            }
            parallel {
                stage('on-perm-hadoop2') {
                    steps {
                        container('build') {
                            dir('on-perm-hadoop2') {
                                script {
                                    def pi = getPackageInfo(params.release_version, 'on-perm-hadoop2')
                                    if(!checkCacheExist(pi)) {
                                        def hadoopVersion = 'hadoop-2.7'
                                        if (params.sparkVersion == 'spark2.4') {
                                            hadoopVersion = 'hadoop-2.6'
                                        }
                                        if (params.sparkVersion == 'spark2.2') {
                                            hadoopVersion = 'hadoop-2.6'
                                        }
                                        sh script: """
                                            ls -alh .
                                            export MAVEN_OPTS="-Xmx4g -XX:ReservedCodeCacheSize=1g -Xss128m"
                                            dev/make-distribution.sh --name ${releaseVersion} -P${hadoopVersion} -Phive -Phive-thriftserver -Pyarn 
                                            if [ 'spark3' = '${params.sparkVersion}' ]; then
                                                cp ../depedencies/log4j/*.jar dist/jars/
                                            fi
                                            mv dist ${fi.filename}
                                            tar czf ${fi.filename}.tgz ${fi.filename}
                                            md5sum ${fi.filename}.tgz
                                        """

                                        sh script: """
                                            mkdir -p ${pi.package_path}
                                            cp ${fi.filename}.tgz ${pi.package_path}
                                        """
                                        // uploadCloudPackage(params.release_version, params.deployType,'on-perm-hadoop2', params.upload_only)
                                        // withCredentials([usernamePassword(credentialsId: 'nexus-raw', passwordVariable: 'passwd', usernameVariable: 'user')]) {
                                        //     pushRawArtifactsByApi('raw-tars-hosted', 'io.kyligence.spark', "spark-newten-${releaseName}-hadoop2.tgz", "spark-newten-${releaseName}-hadoop2.tgz", user, passwd)
                                        // }
                                        // uploadAwsS3('cn-north-1', 'aws_cn_s3_cp', 'download-resource', "kyspark/spark-newten-${releaseName}.tgz", "spark-newten-${releaseName}-hadoop2.tgz")
                                    } else {
                                        echo "${pi.filename} Is Existed"
                                        sh "cp ${pi.package_path}/${pi.filename} ."
                                    }
                                }
                            }
                        }
                    }
                }
                stage('on-perm-nohadoop') {
                    when {
                        expression {
                            return publishToKC
                        }
                    }
                    steps {
                        container('build') {
                            dir('on-perm-nohadoop') {
                                script {
                                    def pi = getPackageInfo(params.release_version, 'on-perm-nohadoop')
                                    if(!checkCacheExist(pi)) {
                                        sh script: """
                                            sleep 10
                                            dev/make-distribution.sh --name ${releaseVersion} -Phadoop-provided -Phive-provided -Phive-thriftserver -Pyarn  -pl assembly
                                            mv dist spark-newten-${releaseName}
                                            tar czf spark-newten-${releaseName}.tgz spark-newten-${releaseName}
                                        """

                                        sh script: """
                                            mkdir -p ${pi.package_path}
                                            cp ${fi.filename}.tgz ${pi.package_path}
                                        """
                                        // uploadCloudPackage(params.release_version, params.deployType,'on-perm-nohadoop', params.upload_only, false)
                                        // withCredentials([usernamePassword(credentialsId: 'nexus-raw', passwordVariable: 'passwd', usernameVariable: 'user')]) {
                                        //     pushRawArtifactsByApi('raw-tars-hosted', 'io.kyligence.spark', "spark-newten-${releaseName}.tgz", "spark-newten-${releaseName}.tgz", user, passwd)
                                        // } 
                                    } else {
                                        echo "${pi.filename} Is Existed"
                                        sh "cp ${pi.package_path}/${pi.filename} ."
                                    }
                                }
                            }
                        }
                    }
                }
                stage('cloud-aws') {
                    when {
                        expression {
                            return publishToKC
                        }
                    }
                    steps {
                        container('build') {
                            dir('cloud-aws') {
                                script {
                                    generateCloudPackage('10', 'cloud-aws', 'aws', releaseVersion)
                                    // uploadCloudPackage(params.release_version, params.deployType,'cloud-aws', params.upload_only)
                                }
                            }
                        }
                    }
                }
                stage('cloud-azure') {
                    when {
                        expression {
                            return publishToKC
                        }
                    }
                    steps {
                        container('build') {
                            dir('cloud-azure') {
                                script {
                                    generateCloudPackage('20', 'cloud-azure', 'azure', releaseVersion)
                                    // uploadCloudPackage(params.release_version, params.deployType,'cloud-azure', params.upload_only)
                                }
                            }
                        }
                    }
                }            
                stage('cloud-gcp') {
                    when {
                        expression {
                            return publishToKC
                        }
                    }
                    steps {
                        container('build') {
                            dir('cloud-gcp') {
                                script {
                                    generateCloudPackage('30', 'cloud-gcp', 'gcp', releaseVersion)
                                    // uploadCloudPackage(params.release_version, params.deployType, 'cloud-gcp', params.upload_only)
                                }
                            }
                        }
                    }
                }
                stage('cloud-huawei') {
                    when {
                        expression {
                            return publishToKC
                        }
                    }
                    steps {
                        container('build') {
                            dir('cloud-huawei') {
                                script {
                                    generateCloudPackage('40', 'cloud-huawei', 'huawei', releaseVersion)
                                    // uploadCloudPackage(params.release_version, params.deployType, 'cloud-huawei', params.upload_only)
                                }
                            }
                        }
                    }
                }
            }
        }
        stage('Upload') {
            parallel {
                stage('on-perm-hadoop2') {
                    steps {
                        container('build') {
                            uploadCloudPackage(params.release_version, params.deployType,'on-perm-hadoop2', params.upload_only)
                        }
                    }
                }
                stage('on-perm-nohadoop') {
                    when {
                        expression {
                            return publishToKC
                        }
                    }
                    steps {
                        container('build') {
                            uploadCloudPackage(params.release_version, params.deployType,'on-perm-nohadoop', params.upload_only, false)
                        }
                    }
                }
                stage('cloud-aws') {
                    when {
                        expression {
                            return publishToKC
                        }
                    }
                    steps {
                        container('build') {
                            uploadCloudPackage(params.release_version, params.deployType,'cloud-aws', params.upload_only)
                        }
                    }
                }
                stage('cloud-azure') {
                    when {
                        expression {
                            return publishToKC
                        }
                    }
                    steps {
                        container('build') {
                            uploadCloudPackage(params.release_version, params.deployType,'cloud-azure', params.upload_only)
                        }
                    }
                }            
                stage('cloud-gcp') {
                    when {
                        expression {
                            return publishToKC
                        }
                    }
                    steps {
                        container('build') {
                            uploadCloudPackage(params.release_version, params.deployType, 'cloud-gcp', params.upload_only)
                        }
                    }
                }
                stage('cloud-huawei') {
                    when {
                        expression {
                            return publishToKC
                        }
                    }
                    steps {
                        container('build') {
                            uploadCloudPackage(params.release_version, params.deployType, 'cloud-huawei', params.upload_only)
                        }
                    }
                }
            }
        }
        stage('Tag') {
            when {
                expression {
                    return params.deployType == 'GA'
                }
            }
            steps {
                container('build') {
                    dir('sourcecode') {
                        githubHelper 'TAG', params.branch, 'spark', releaseVersion
                    }
                }
            }
        }
    }
}

