#!groovy

@Library('devopslib') _

def IS_DEBUG = true
def package_info = [:]
def releaseVersion = '' //最后发布的版本号
def releaseName = ''
def publishToKC = false //是否发布给KC

def getPackageInfo(version,deployType,packageType) {
    println "getPackageInfo -> version[${version}],deployType[${deployType}],packageType[${packageType}]"
    def file_name = ''
    def package_path = ''
    def releaseName = ''
    def releaseVersion = getReleaseVersion(version, deployType)
    releaseName = releaseVersion.replace('-kylin', '')
    switch(packageType) {
        case 'on-perm-hadoop2':
            file_name = "spark-newten-${releaseName}-hadoop2"
            break
        case 'on-perm-nohadoop':
            file_name = "spark-newten-${releaseName}"
            break
        case 'cloud-aws':
        case 'cloud-azure':
        case 'cloud-gcp':
        case 'cloud-huawei':
            file_name = "spark-newten-${releaseName}-${packageType}"
            break
    }
    def path_folder = version.replace('-kylin', '')
    package_path = "/var/cicd/spark/${path_folder}/${deployType}"
    def obj = [:]
    obj.package_path = package_path
    obj.file_name = file_name
    obj.package_name = "${file_name}.tgz"
    obj.releaseName = releaseName
    obj.releaseVersion = releaseVersion
    println "getPackageInfo: ${obj.toString()}"
    return obj
}

def checkCacheExist(pi) {
    println "checkCacheExist -> package_info[${pi}]"
    def result = false
    try {
        def existPackage = "${pi.package_path}/${pi.package_name}"
        sh script: """
            ls -alh ${pi.package_path}
            cp ${existPackage} ${pi.package_name}
        """

        sh 'ls -alh'
        // println "pi.package_file: ${pi.package_file}"
        result = fileExists(pi.package_name)
        println "${pi.package_path}/${pi.package_name} is ${result}"
    } catch (Exception err) {
        println "The package [${pi.package_name}] not exsits, the pipeline will make it next."
        result = false
        // println err.getMessage()
    }

    println "checkCacheExist result: ${result}"
    return result
}

// 上传制品包到Aws S3存储
def uploadAwsS3(region, credentials, bucket, path, ga_name) {
    println("uploadAwsS3 -> path: ${path}, ga_name: ${ga_name}, retry 3 times")
    timestamps {
        withAWS(region: region, credentials: credentials) {
            retry(3) {
                // s3Upload(bucket: bucket, path: path, file: ga_name)
                sh """
                    ls -alt /jenkins-common/jobs/${env.JOB_NAME}/
                    aws s3 cp /jenkins-common/jobs/${env.JOB_NAME}/${ga_name} s3://$bucket/${path}/ --acl public-read
                """
            }
        }
    }
}

def getReleaseVersion(version, deployType) {
    println "getReleaseVersion -> version[${version}],deployType[${deployType}]"
    def _result
    _result = version
    switch (deployType) {
        case 'DEV':
            _result = _result + '-DEV-SNAPSHOT'
            break
        case 'QA':
            _result = _result + '-SNAPSHOT'
            break
        case 'GA':
            _result = version
            break
    }
    return _result.trim()
}

// git获取spark 代码（预先触发同步git mirror）
def gitSparkCodeKe(repo, branch) {
    script {
        if (repo == 'Kyligence') {
            pullCodeFromGitMirror 'spark', branch
        } else {
            githubCheckout 'spark', branch, 'https', 'github.com', '+refs/heads/*:refs/remotes/origin/*', 'kyligence-git', repo
        }
    }
}

def generateCloudPackage(cloudType,dependencyDir,version,deployType) {
    println "generateCloudPackage -> cloudType[${cloudType}],dependencyDir[${dependencyDir}],version[${version}],deployType[${deployType}]"
    //kc 使用的的log4j jar 与本地略有区别，这里需要特殊处理 参见 https://olapio.atlassian.net/browse/KE-34130
    //https://olapio.atlassian.net/browse/KE-34066 配置方式也与本地略有区别
    //https://olapio.atlassian.net/browse/KC-12372 delete slf4j-log4j12
    def pi = getPackageInfo(version,deployType,cloudType)
    if(!checkCacheExist(pi)) {
        sh script: """
            export MAVEN_OPTS="-Xmx4g -XX:ReservedCodeCacheSize=1g -Xss128m"
            dev/make-distribution.sh --name ${pi.releaseVersion} -Phadoop-3.2 -Phive-thriftserver -pl assembly
            cp ../depedencies/log4j/*.jar dist/jars/
            cp ../depedencies/cloud_log4j/*.jar dist/jars/
            rm  dist/jars/log4j-1.2-api-*.jar
            rm  dist/jars/slf4j-log4j12*.jar
            cp -r ../hive_1_2_2  dist/
            cp ../depedencies/${dependencyDir}/* dist/jars/
            cp ../depedencies/log4j/spark-executor-log4j.xml dist/conf/spark-executor-log4j.xml
            #https://olapio.atlassian.net/browse/KC-13052,special handle for azure
            if [ 'cloud-azure' = '${cloudType}' ]; then
                cp dist/jars/azure-identity-extensions*.jar dist/hive_1_2_2/ || :
                cp dist/jars/mysql-connector*.jar dist/hive_1_2_2/ || :
                cp dist/jars/postgresql*.jar dist/hive_1_2_2/ || :
            fi
            mv dist ${pi.file_name}
            tar czf ${pi.package_name} ${pi.file_name}
        """

        sh script: """
            mkdir -p ${pi.package_path}
            cp ${pi.package_name} ${pi.package_path}
        """
    } else {
        echo "${pi.package_name} is Existed"
        sh "cp ${pi.package_path}/${pi.package_name} ."
    }
}

def uploadCloudPackage(version,deployType,packageType,uploadOnly=false,uploadS3=true) {
    println "uploadCloudPackage -> version[${version}],deployType[${deployType}],packageType[${packageType}],uploadOnly[${uploadOnly}],uploadS3[${uploadS3}]"
    script {
        def _releaseVersion = getReleaseVersion(version,deployType)
        def _packageInfo =  getPackageInfo(version,deployType, packageType)
        def _hasNexusCache = false
        def _hasPackageCache = false
        
        dir(packageType) {
            if(uploadOnly) {
                try {
                    sh """
                        wget https://package.kyligence.com/newten-cicd/spark/${_packageInfo.releaseVersion}/${_packageInfo.package_name} --no-check-certificate
                    """
                    _hasPackageCache = true
                }
                catch (exception) {
                    println "not found in https://package.kyligence.com/newten-cicd/spark/"
                    _hasPackageCache = false
                }
                if(!_hasPackageCache) {
                    try {
                        sh """
                            wget https://repo-ofs.kyligence.com/repository/raw-tars-hosted/io.kyligence.spark/${_packageInfo.package_name} --no-check-certificate
                        """
                    }
                    catch (exception) {
                        println "not found in https://repo-ofs.kyligence.com/repository/raw-tars-hosted/io.kyligence.spark/"
                        _hasNexusCache = false
                    }
                }
            } 
        }

        if(!uploadOnly || _hasPackageCache) {
            try {
                retry(3) {
                    uploadHelper.uploadNexus(_packageInfo.package_name, 'io.kyligence.spark', 'raw-tars-hosted', packageType)
                }
            } catch (Exception err) {
                println "upload to nexus fail, ${err.getMessage}"
            }
        }

        if(uploadS3){
            // uploadAwsS3('us-west-2', 'aws_global_s3_cp', 'kyligencecloud-ci', "packages/spark-cloud/${_packageInfo.package_name}", _packageInfo.package_name)
            uploadHelper.uploadAwsS3(_packageInfo.package_name, "packages/spark-cloud/${_packageInfo.package_name}", 'kyligencecloud-ci', 'us-west-2', 'aws_global_s3_cp', packageType)
        }
    }
}

def deployJars(version,deployType,sparkVersion,envProfile) {
    println "deployJars -> version[${version}],deployType[${deployType}],sparkVersion[${sparkVersion}],publishToKC[${publishToKC}],envProfile[${envProfile}]"
    script {
        def _releaseVersion = getReleaseVersion(version, deployType)
        def kubernetesParm = '-Pkubernetes'
        if (sparkVersion == 'spark2.2') {
            kubernetesParm = ''
        }
        retry(3) {
            sh script: """
                export MAVEN_OPTS="-Xmx4g -XX:ReservedCodeCacheSize=1g -Xss128m"
                mvn versions:set -DnewVersion=${_releaseVersion}
                mvn deploy -P${envProfile} -Phadoop-provided -Phive-provided -Phive-thriftserver -Pyarn ${kubernetesParm} -DskipTests=true
            """
        }
    }
}

def buildPackage(version,deployType,sparkVersion,envProfile) {
    println "buildPackage -> version[${version}],deployType[${deployType}],sparkVersion[${sparkVersion}],publishToKC[${publishToKC}],envProfile[${envProfile}]"
    script {
        def _releaseVersion = getReleaseVersion(version, deployType)
        def kubernetesParm = '-Pkubernetes'
        if (sparkVersion == 'spark2.2') {
            kubernetesParm = ''
        }
        retry(3) {
            sh script: """
                export MAVEN_OPTS="-Xmx8g -XX:ReservedCodeCacheSize=2g -Xss1g"
                mvn versions:set -DnewVersion=${_releaseVersion}
                mvn -T 2C package -U -P${envProfile} -Phadoop-provided -Phive-provided -Phive-thriftserver -Pyarn ${kubernetesParm} -DskipTests=true
            """
        }
    }
}

pipeline {
    options {
        timeout(time: 12, unit: 'HOURS')
        ansiColor('xterm')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/yaml/jenkins-spark-agent.yaml'
        }
    }

    parameters {
        string(name: 'repo', defaultValue: 'Kyligence', description: 'spark repo  https://github.com/Kyligence/spark.git--> Kyligence\nhttps://github.com/apache/spark.git--> apache')
        string(name: 'branch', defaultValue: 'kyspark-3.2.x-4.x', description: 'spark branch  \n kyspark-2.4.1.x-4.x \n kyspark-3.2.x-4.x \n kyspark-2.2.1.x-3.x ')
        string(name: 'release_version', defaultValue: '', description: 'spark release version for example: 3.2.0-kylin-4.5.16.0')
        choice(name: 'deployType', choices: 'DEV\nQA\nGA', description: '研发自测用自己分支打包，选择DEV，会在version后面加上 -DEV-SNAPSHOT，并且不会发包给kc，\n' +
                '进代码后基于dev分支发布，选择QA，会在version后面加上 -SNAPSHOT\n GA后基于稳定分支发包，选择GA，version 不做处理')
        choice(name: 'sparkVersion', choices: 'spark3\nspark2.4\nspark2.2', description: 'spark 大版本，spark2.4/2.2 发包不会推到云上')
        string(name: 'cloud_dependency_path', defaultValue: 'cloud-dependency/current', description: 'cloud denpendency directory in repo-ofs,\n 这个路径是制品库spark 目录下的子目录,该目录下必须有depedencies.tar.gz 文件，可以选择旧包的目录打旧版本的spark 包，eg:cloud-dependency/4.6.4.0\n 4.5稳定版发版请用cloud-dependency/4.5.x-current')
        booleanParam(name: 'override', defaultValue: false, description: '勾选时，不使用之前打过的版本缓存，重新覆盖打包')
        booleanParam(name: 'deploy_jars', defaultValue: true, description: '默认勾选，取消勾选时跳过本地repo-ofs deploy 以节省时间')
        booleanParam(name: 'deploy_to_kylin', defaultValue: false, description: '勾选时，将会将spark 推送到public repo，供kylin用户使用,重试的时候可以跳过这一步节省时间')
        booleanParam(name: 'deploy_to_aws', defaultValue: false, description: '勾选时，将会将spark 推送到aws repo，供CI使用,重试的时候可以跳过这一步节省时间')
        booleanParam(name: 'publishToKC', defaultValue: false, description: '勾选时，会打云上的包给KC用, 如果只打on promise 包可以取消勾选')
        booleanParam(name: 'upload_only', defaultValue: false, description: '勾选时，将会跳过 deploy jar 包到制品库，并获取repo-ofs raw 中对应版本 tar 包上传到 S3')
    }

    stages {
        stage('approve deploy DI OR Manager') {
            when {
                expression {
                    return params.deployType == 'GA'
                }
            }
            steps {
                container('build') {
                    script {
                        releaseVersion = getReleaseVersion(params.release_version, params.deployType)
                        def checkMsg = "DI部门，确定发布该版本吗？发布repo：${params.repo}, 发布分支：${params.branch}，发布版本号：${releaseVersion}"
                        println checkMsg
                        paramsGA = input(
                                message: checkMsg,
                                ok: '确认！',
                                submitter: 'jiawei.li2,chenliang.lu,biaobiao.sun,luoping.zhang,lu.cao,meixiu.chen,liming.meng',
                                submitterParameter: 'APPROVER'
                        )
                    }
                }
            }
        }
        stage('Checkout Source Code') {
            when {
                expression {
                    return !params.upload_only
                }
            }
            steps {
                container('build') {
                    dir('sourcecode') {
                        gitSparkCodeKe(params.repo, params.branch)
                    }

                    script {
                        releaseVersion = getReleaseVersion(params.release_version, params.deployType)
                        releaseName = releaseVersion.replace('-kylin', '')
                        if (params.sparkVersion == 'spark3' && params.publishToKC) {
                            publishToKC = true
                        }
                        if(params.deploy_to_kylin){
                            sh script: """
                                cp -r sourcecode ./sourcecode2
                                ls -alt sourcecode2
                            """
                        }
                        sh "cp -r sourcecode ./sourcecode3"
                    }
                    sh script: """
                        wget https://repo-ofs.kyligence.com/repository/raw-public/io.kyligence.spark/${params.cloud_dependency_path}/depedencies.tar.gz
                        tar zxf depedencies.tar.gz
                        wget https://s3.cn-north-1.amazonaws.com.cn/download-resource/kyspark/hive_1_2_2.tar.gz
                        tar zxf hive_1_2_2.tar.gz
                    """
                }
            }
        }
        stage('Build') {
            steps {
                container('build') {
                    dir('sourcecode') {
                        script {
                            def piHadoop = getPackageInfo(params.release_version, params.deployType, 'on-perm-hadoop2')
                            if(!checkCacheExist(piHadoop) || publishToKC || params.override) {
                                buildPackage(params.release_version, params.deployType, params.sparkVersion, 'dev')
                            }
                        }
                    }

                    script {
                        sh script: '''
                            cp -r sourcecode ./on-perm-hadoop2
                        '''
                        if(publishToKC) {
                            sh script: '''
                                cp -r sourcecode ./on-perm-nohadoop
                                cp -r sourcecode ./cloud-azure
                                cp -r sourcecode ./cloud-aws
                                cp -r sourcecode ./cloud-gcp
                                cp -r sourcecode ./cloud-huawei
                                ls -alh
                            '''
                        }
                    }
                }
            }
        }
        stage('Deploy') {
            when {
                expression {
                    return !params.upload_only && params.deploy_jars
                }
            }
            parallel {
                stage('1.to Ofs') {
                    steps {
                        container('build') {
                            dir('sourcecode') {
                                deployJars(params.release_version, params.deployType, params.sparkVersion, 'dev')
                            }
                        }
                    }
                }
                stage('2.to AWS CI') {
                    when {
                        expression {
                            return params.deploy_to_aws
                        }
                    }
                    steps {
                        container('build3') {
                            dir('sourcecode3') {
                                deployJars(params.release_version, params.deployType, params.sparkVersion, 'aws')
                            }
                        }
                    }
                }
                stage('3.to Open Source') {
                    when {
                        expression {
                            return params.deploy_to_kylin
                        }
                    }
                    steps {
                        container('build2') {
                            dir('sourcecode2') {
                                deployJars(params.release_version, params.deployType, params.sparkVersion, 'pro')
                            }
                        }
                    }
                }
            }
        }
        stage('Package') {
            when {
                expression {
                    return !params.upload_only
                }
            }
            parallel {
                stage('1.on-perm-hadoop2') {
                    steps {
                        container('build') {
                            dir('on-perm-hadoop2') {
                                script {
                                    def pi = getPackageInfo(params.release_version, params.deployType, 'on-perm-hadoop2')
                                    if(!checkCacheExist(pi)) {
                                        def hadoopVersion = 'hadoop-2.7'
                                        if (params.sparkVersion == 'spark2.4') {
                                            hadoopVersion = 'hadoop-2.6'
                                        }
                                        if (params.sparkVersion == 'spark2.2') {
                                            hadoopVersion = 'hadoop-2.6'
                                        }
                                        sh script: """
                                            ls -alh .
                                            export MAVEN_OPTS="-Xmx4g -XX:ReservedCodeCacheSize=1g -Xss128m"
                                            dev/make-distribution.sh --name ${pi.releaseVersion} -P${hadoopVersion} -Phive -Phive-thriftserver -Pyarn 
                                            if [ 'spark3' = '${params.sparkVersion}' ]; then
                                                cp ../depedencies/log4j/*.jar dist/jars/
                                            fi
                                            mv dist ${pi.file_name}
                                            tar czf ${pi.package_name} ${pi.file_name}
                                            md5sum ${pi.package_name}
                                        """

                                        sh script: """
                                            mkdir -p ${pi.package_path}
                                            cp ${pi.package_name} ${pi.package_path}
                                        """
                                    } else {
                                        echo "${pi.package_name} is Existed"
                                        sh """
                                            cp ${pi.package_path}/${pi.package_name} .
                                            ls -alh .
                                        """
                                    }
                                }
                            }
                        }
                    }
                }
                stage('2.on-perm-nohadoop') {
                    when {
                        expression {
                            return publishToKC
                        }
                    }
                    steps {
                        container('build') {
                            dir('on-perm-nohadoop') {
                                script {
                                    def pi = getPackageInfo(params.release_version,params.deployType,'on-perm-nohadoop')
                                    if(!checkCacheExist(pi)) {
                                        sh script: """
                                            dev/make-distribution.sh --name ${pi.releaseVersion} -Phadoop-provided -Phive-provided -Phive-thriftserver -Pyarn  -pl assembly
                                            mv dist ${pi.file_name}
                                            tar czf ${pi.package_name} ${pi.file_name}
                                        """

                                        sh script: """
                                            mkdir -p ${pi.package_path}
                                            cp ${pi.package_name} ${pi.package_path}
                                        """ 
                                    } else {
                                        echo "${pi.package_name} Is Existed"
                                        sh "cp ${pi.package_path}/${pi.package_name} ."
                                    }
                                }
                            }
                        }
                    }
                }
                stage('3.cloud-aws') {
                    when {
                        expression {
                            return publishToKC
                        }
                    }
                    steps {
                        container('build') {
                            dir('cloud-aws') {
                                script {
                                    generateCloudPackage('cloud-aws', 'aws', params.release_version, params.deployType)
                                }
                            }
                        }
                    }
                }
                stage('4.cloud-azure') {
                    when {
                        expression {
                            return publishToKC
                        }
                    }
                    steps {
                        container('build') {
                            dir('cloud-azure') {
                                script {
                                    generateCloudPackage('cloud-azure', 'azure', params.release_version, params.deployType)
                                }
                            }
                        }
                    }
                }            
                stage('5.cloud-gcp') {
                    when {
                        expression {
                            return publishToKC
                        }
                    }
                    steps {
                        container('build') {
                            dir('cloud-gcp') {
                                script {
                                    generateCloudPackage('cloud-gcp', 'gcp', params.release_version, params.deployType)
                                }
                            }
                        }
                    }
                }
                stage('6.cloud-huawei') {
                    when {
                        expression {
                            return publishToKC
                        }
                    }
                    steps {
                        container('build') {
                            dir('cloud-huawei') {
                                script {
                                    generateCloudPackage('cloud-huawei', 'huawei', params.release_version, params.deployType)
                                }
                            }
                        }
                    }
                }
            }
        }
        stage('Upload') {
            parallel {
                stage('1.on-perm-hadoop2') {
                    steps {
                        container('build') {
                            uploadCloudPackage(params.release_version, params.deployType,'on-perm-hadoop2', params.upload_only, false)
                        }
                    }
                }
                stage('2.on-perm-nohadoop') {
                    when {
                        expression {
                            return publishToKC || params.upload_only
                        }
                    }
                    steps {
                        container('build') {
                            uploadCloudPackage(params.release_version, params.deployType,'on-perm-nohadoop', params.upload_only)
                        }
                    }
                }
                stage('3.cloud-aws') {
                    when {
                        expression {
                            return publishToKC || params.upload_only
                        }
                    }
                    steps {
                        container('build') {
                            uploadCloudPackage(params.release_version, params.deployType,'cloud-aws', params.upload_only)
                        }
                    }
                }
                stage('4.cloud-azure') {
                    when {
                        expression {
                            return publishToKC || params.upload_only
                        }
                    }
                    steps {
                        container('build') {
                            uploadCloudPackage(params.release_version, params.deployType,'cloud-azure', params.upload_only)
                        }
                    }
                }            
                stage('5.cloud-gcp') {
                    when {
                        expression {
                            return publishToKC || params.upload_only
                        }
                    }
                    steps {
                        container('build') {
                            uploadCloudPackage(params.release_version, params.deployType, 'cloud-gcp', params.upload_only)
                        }
                    }
                }
                stage('6.cloud-huawei') {
                    when {
                        expression {
                            return publishToKC || params.upload_only
                        }
                    }
                    steps {
                        container('build') {
                            uploadCloudPackage(params.release_version, params.deployType, 'cloud-huawei', params.upload_only)
                        }
                    }
                }
            }
        }
        stage('Tag') {
            when {
                expression {
                    return params.deployType == 'GA'
                }
            }
            steps {
                container('build') {
                    dir('sourcecode') {
                        githubHelper 'TAG', params.branch, 'spark', releaseVersion
                    }
                }
            }
        }
    }


    post {
        failure {
            container('build') {
                script {
                    if (!IS_DEBUG) {
                        feishu('KE-All-CD-2.1打包失败！！')
                    }
                }
            }
        }
    }
}

