kind: ConfigMap
apiVersion: v1
metadata:
  name: kylin.properties.yaml
data:
  kylin.properties: |
    kyligence.kyiam.sdk.security.gateway-path-filter.forbid-url=/kylin/api/jobs/feign/**,/kylin/api/models/feign/**,/kylin/api/tables/feign/**,/kylin/api/job_delegate/feign/**
    kyligence.kyiam.sdk.security.gateway-path-filter.ignore-url=/kylin/api/epoch/maintenance_mode,/kylin/api/prometheus,/kylin/api/user/update_user,/kylin/api/metastore/cleanup,/api/metastore/cleanup_storage,/kylin/api/epoch,/kylin/api/config/is_cloud,/api/system/license/file,/kylin/api/system/license/content,/kylin/api/system/license/trial,/api/system/license,/kylin/api/system/diag/progress,/kylin/api/system/roll_event_log,/api/user/authentication*/**,/kylin/api/system/backup,/kylin/api/cubes/src/tables,/kylin/api/admin/public_config,/api/admin/instance_info,/kylin/api/projects,/kylin/api/system/license/info,/kylin/api/health,/kylin/api/health/**,/api/prometheus,/kylin/api/broadcast/**,/kylin/api/models/model_info,/kylin/api/**/metrics,/kylin/api/cache*/**,/kylin/api/monitor/spark/prometheus,/kylin/api/query/history_queries/table_names,/kylin/api/health,/kylin/api/health/**,/api/prometheus,/kylin/api/broadcast/**,/kylin/api/models/model_info,/kylin/api/**/metrics,/kylin/api/cache*/**,/kylin/api/streaming_jobs/spark,/kylin/api/streaming_jobs/stats,/api/streaming_jobs/dataflow/**,/kylin/api/jobs/spark,/kylin/api/jobs/stage/status,/kylin/api/jobs/error,/api/jobs/wait_and_run_time,/kylin/api/health,/kylin/api/health/**,/api/prometheus,/kylin/api/broadcast/**,/kylin/api/models/model_info,/kylin/api/**/metrics,/kylin/api/cache*/**
    kyligence.kyiam.sdk.tenant-id=${TENANT_ID}
    kylin.circuit-breaker.threshold.project=1000
    kylin.engine.extra-jars-path=${KYLIN_HOME}/server/jars/mysql-connector-java-8.0.28.jar
    kylin.engine.spark-conf.spark.driver.host=${SPARK_DRIVER_BIND_ADDRESS}
    kylin.engine.spark-conf.spark.executor.cores=1
    kylin.engine.spark-conf.spark.executor.instances=1
    kylin.engine.spark-conf.spark.executor.memory=1024m
    kylin.engine.spark-conf.spark.executor.memoryOverhead=512m
    kylin.engine.spark-conf.spark.hadoop.fs.s3a.access.key=WAXC3I4MY90TH6OR7NFL
    kylin.engine.spark-conf.spark.hadoop.fs.s3a.fast.upload=true
    kylin.engine.spark-conf.spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
    kylin.engine.spark-conf.spark.hadoop.fs.s3a.secret.key=VJ0CBjdMCqVu2kXVxx0m5ioqOJ04yGtgqZBumakq
    kylin.engine.spark-conf.spark.kubernetes.authenticate.driver.serviceAccountName=spark
    kylin.engine.spark-conf.spark.kubernetes.authenticate.executor.serviceAccountName=spark
    kylin.engine.spark-conf.spark.kubernetes.container.image.pullPolicy=Always
    kylin.engine.spark-conf.spark.kubernetes.container.image=repo-ofs.kyligence.com/spark:3.3.0-kylin-4.5.17.0-SNAPSHOT
    kylin.engine.spark-conf.spark.kubernetes.driver.limit.cores=1
    kylin.engine.spark-conf.spark.kubernetes.executor.limit.cores=1
    kylin.engine.spark-conf.spark.kubernetes.executor.podNamePrefix=data-loading
    kylin.engine.spark-conf.spark.kubernetes.file.upload.path=s3a://yinglong-dep
    kylin.engine.spark-conf.spark.kubernetes.namespace=${K8S_NAMESPACE}
    kylin.engine.spark-conf.spark.master=k8s://https://kubernetes.default:443
    kylin.engine.spark-conf.spark.sql.hive.metastore.jars.path=s3a://yinglong/kylin/hive_1_2_2/*
    kylin.engine.spark-conf.spark.sql.hive.metastore.jars=path
    kylin.engine.spark-conf.spark.submit.deployMode=cluster
    kylin.engine.spark.cluster-manager-class-name=org.apache.kylin.cluster.K8sClusterManager
    kylin.job.check-quota-storage-enabled=false
    kylin.job.max-concurrent-jobs=6
    kylin.metadata.compress.enabled=false
    kylin.metadata.distributed-lock-impl=org.apache.kylin.common.lock.jdbc.JdbcDistributedLockFactory
    kylin.metadata.distributed-lock.jdbc.url=${KYLIN_METADATA_URL}
    kylin.metadata.url=${KYLIN_METADATA_URL}
    kylin.query.async-query.spark-conf.spark.executor.cores=1
    kylin.query.async-query.spark-conf.spark.executor.instances=1
    kylin.query.queryhistory.url=${KYLIN_METADATA_URL}
    kylin.query.realization.chooser.thread-core-num=1
    kylin.security.custom.authentication-provider-class-name=io.kyligence.saas.iam.sdk.ke.IAMAuthenticationProvider
    kylin.security.custom.user-group-service-class-name=io.kyligence.saas.iam.sdk.ke.IAMUserGroupService
    kylin.security.custom.user-service-class-name=io.kyligence.saas.iam.sdk.ke.IAMUserService
    kylin.security.profile=custom
    kylin.storage.columnar.spark-conf.spark.default.parallelism=32
    kylin.storage.columnar.spark-conf.spark.driver.cores=1
    kylin.storage.columnar.spark-conf.spark.driver.extraJavaOptions=-Djava.library.path=$SPARK_HOME/lib/native=-XX:MaxDirectMemorySize=1G
    kylin.storage.columnar.spark-conf.spark.driver.memory=1024m
    kylin.storage.columnar.spark-conf.spark.executor.cores=1
    kylin.storage.columnar.spark-conf.spark.executor.instances=1
    kylin.storage.columnar.spark-conf.spark.executor.memory=1024m
    kylin.storage.columnar.spark-conf.spark.executor.memoryOverhead=1024m
    kylin.storage.columnar.spark-conf.spark.hadoop.fs.s3a.access.key=WAXC3I4MY90TH6OR7NFL
    kylin.storage.columnar.spark-conf.spark.hadoop.fs.s3a.fast.upload=true
    kylin.storage.columnar.spark-conf.spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
    kylin.storage.columnar.spark-conf.spark.hadoop.fs.s3a.secret.key=VJ0CBjdMCqVu2kXVxx0m5ioqOJ04yGtgqZBumakq
    kylin.storage.columnar.spark-conf.spark.kubernetes.authenticate.driver.serviceAccountName=spark
    kylin.storage.columnar.spark-conf.spark.kubernetes.authenticate.executor.serviceAccountName=spark
    kylin.storage.columnar.spark-conf.spark.kubernetes.container.image.pullPolicy=Always
    kylin.storage.columnar.spark-conf.spark.kubernetes.container.image=repo-ofs.kyligence.com/spark:3.3.0-kylin-4.5.17.0-SNAPSHOT
    kylin.storage.columnar.spark-conf.spark.kubernetes.driver.limit.cores=1
    kylin.storage.columnar.spark-conf.spark.kubernetes.executor.limit.cores=1
    kylin.storage.columnar.spark-conf.spark.kubernetes.executor.podNamePrefix=sparder
    kylin.storage.columnar.spark-conf.spark.kubernetes.file.upload.path=s3a://yinglong-dep
    kylin.storage.columnar.spark-conf.spark.kubernetes.namespace=${K8S_NAMESPACE}
    kylin.storage.columnar.spark-conf.spark.master=k8s://https://kubernetes.default:443
    kylin.storage.columnar.spark-conf.spark.serializer=org.apache.spark.serializer.KryoSerializer
    kylin.storage.columnar.spark-conf.spark.sql.shuffle.partitions=32
    spring.cloud.nacos.discovery.group=${TENANT_ID}
    spring.cloud.nacos.config.server-addr=${NACOS_CONFIG_SERVER_ADDR_NO_HTTP}
    spring.cloud.nacos.discovery.server-addr=${NACOS_DISCOVERY_SERVER_ADDR}
    spring.cloud.nacos.discovery.service=${APP_NAME}
    spring.cloud.nacos.server-addr=${NACOS_DISCOVERY_SERVER_ADDR}
    spring.session.store-type=none
    spring.profiles.active=custom
