apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.sparkRoleBinding }}
  namespace: {{ .Values.sparkResourceNamespace }}
subjects:
  - kind: ServiceAccount
    name: spark
roleRef:
  kind: ClusterRole
  name: {{ .Values.sparkRole }}
  apiGroup: rbac.authorization.k8s.io