#!groovy

def testInParallel() {
    def testStages = [
            'Test-Stage-1': testForModules('Test-Stage-1', "src/core-common", "src/core-job", "src/core-storage", "src/core-metadata", "src/server-base", "src/server"),
            'Test-Stage-2': testForModules('Test-Stage-2', "src/query", "src/smart", "src/source-hive", "src/streaming"),
            'Test-Stage-3': testForModules('Test-Stage-3', "src/udf", "src/spark-project", "src/assembly", "src/tool", "src/datasource-sdk", "src/external", "src/external-catalog"),
            'Test-Stage-4': testForModules('Test-Stage-4', "src/kap-it")
    ]

    parallel testStages
}

def testForModules(String stage, String... modules) {
    return {
        // 'container': use the same container to execute in parallel in the current pod
        // 'node(POD_LABEL)': multiple pod in parallel, and this situation needs to rely on external shared storage
        container("maven") {
            def willTestModules = modules.join(",")
            sh script: """
                mkdir ${stage} && cp -arf ./sourcecode/* ./${stage}/ && cd ./${stage}
                mvn test --fail-at-end \
                -pl ${willTestModules} \
                -Dtest='!io.kyligence.kap.secondstorage.*,!io.kyligence.**.clickhouse.*' \
                -DfailIfNoTests=false \
                -Duser.timezone=GMT+8
            """
        }
    }
}

pipeline {
    options {
        timeout(time: 6, unit: 'HOURS')
    }

    agent {
        kubernetes {
            yaml """
                kind: Pod
                name: jenkins-agent
                spec:
                  containers:
                    - name: maven
                      image: maven:3.8.3-openjdk-8
                      command:
                        - cat
                      tty: true
                      volumeMounts:
                        - name: jenkins-common
                          mountPath: /root/.m2
                          subPath: maven3
                        - name: jenkins-common
                          mountPath: /var/troubleshooting
                          subPath: troubleshooting
                    - name: git
                      image: bitnami/git:latest
                      command:
                        - cat
                      tty: true
                      volumeMounts:
                        - name: jenkins-common
                          mountPath: /var/jenkins_common
                  volumes:
                    - name: jenkins-common
                      persistentVolumeClaim:
                        claimName: jenkins-common
            """
        }
    }

    parameters {
        string(name: 'kap_repo', defaultValue: 'Kyligence', description: 'Kap repo?')
        string(name: 'kap_branch', defaultValue: 'newten-dev', description: 'Kap branch')
        credentials(name: 'certificate', credentialType: 'com.cloudbees.plugins.credentials.common.StandardCredentials', defaultValue: '', required: true)
    }
    stages {
/*        stage("Cleanup") {
            steps {
            }

        }*/
        stage("Checkout Source Code") {
            steps {
                container("git") {
                    dir("sourcecode") {
                        retry(3) {
                            checkout([$class           : 'GitSCM', branches: [[name: "${params.kap_branch}"]],
                                      userRemoteConfigs: [[credentialsId: "${params.certificate}", url: "git://10.1.2.192/${params.kap_repo}/KAP.git"]],
                                      browser          : [$class: 'GithubWeb', repoUrl: "https://github.com/${params.kap_repo}/KAP"],
                                      extensions       : [
                                              [$class: 'CleanBeforeCheckout'],
                                              [$class: 'CloneOption', depth: 0, noTags: false, shallow: false, timeout: 60]
                                      ]
                            ])
                        }
                    }
/*                    // TODO
                    script {
                        def patchFile = "/shard/jenkins/license/newten.patch.${ghprbActualCommitAuthor}"
                        if (fileExists(patchFile)) {
                            sh script: """
                             git apply "${patchFile}"
                         """
                        } else {
                            sh script: """
                             git apply /shard/jenkins/license/newten.patch
                         """
                        }

                        sh "git checkout -- ."
                    }*/
                }
            }
        }
        stage('Maven Install') {
            steps {
                container("maven") {
                    dir("sourcecode") {
                        sh script: """
                            mvn -U clean install -T 1C -Dmaven.compile.fork=true -DskipTests
                        """
                    }
                }
            }
        }
        stage('Testing') {
            steps {
                script {
                    testInParallel()
                }
            }

        }
    }
    post {
        failure {
            container('maven') {
                timestamps {
                    sh "mkdir -p /var/troubleshooting/${JOB_NAME}/${BUILD_NUMBER} && \
                        cp ./* -rf /var/troubleshooting/${JOB_NAME}/${BUILD_NUMBER}"
                }
            }
        }
    }

}