apiVersion: v1
data:
  # ceph auth get-key client.admin | base64
  key: QVFBTjB6cGlQRkMxRXhBQWhRRVFnemFHM0tTREE3S0JhQUpsNVE9PQ==
kind: Secret
metadata:
  name: ceph-admin-secret
  namespace: kube-system
type: kubernetes.io/rbd
---
apiVersion: v1
data:
  # ceph auth add client.k8s-rbd mon 'allow r' osd 'allow rwx pool=k8s-rbd'
  # ceph auth get-key client.k8s-rbd | base64
  key: QVFCdXJVMWkvZllSS2hBQVlvSStSRHhMaEU5dUE3KzAxUnVzNFE9PQ==
kind: Secret
metadata:
  name: ceph-user-secret
  namespace: default
type: kubernetes.io/rbd
