apiVersion: v1
data:
  # ceph auth get-key client.admin | base64
  key: QVFCVzJxNWh6c001TUJBQW9CRk5YTzVROEFXVnVEYmowY2hsVnc9PQ==
kind: Secret
metadata:
  name: ceph-admin-secret
  namespace: kube-system
type: kubernetes.io/rbd
---
apiVersion: v1
data:
  # ceph auth add client.k8s mon 'allow r' osd 'allow rwx pool=k8s'
  # ceph auth get-key client.k8s | base64
  key: QVFERExyUmh0ZnVVQ0JBQWtOVnFCaURFU20rQUlLbUNaVmdUeFE9PQ==
kind: Secret
metadata:
  name: ceph-user-secret
  namespace: default
type: kubernetes.io/rbd
