apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "yinglong-frontend.fullname" . }}-default-conf
data:
  default.conf: |-
    server {
      listen       80;
      listen  [::]:80;
      server_name  localhost;

      # Gateway
        location ~^/(kylin/api|kylin/sparder|kylin/history_server)/ {
        proxy_pass http://{{ .Values.gateway.serverAddr }};
      }

        location /kylin {
        rewrite ^/kylin(.*)$ $1 break;
        root  /usr/share/nginx/html;
        index  index.html;
        try_files $uri /index.html;
      }
    
      location /browser {
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS';
        add_header Access-Control-Allow-Headers 'Referer,Accept,Origin,DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';
    
        if ($request_method = 'OPTIONS') {
          return 204;
        }
        
        proxy_pass {{ .Values.skywalking.oap.rest }};
      }

        location / {
        root  /usr/share/nginx/html;
        index  index.html;
        try_files $uri /index.html;
      }
    }