apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "yinglong-frontend.fullname" . }}
  labels:
    {{- include "yinglong-frontend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "yinglong-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "yinglong-frontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: spark
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: default-conf
          configMap:
            name: {{ include "yinglong-frontend.fullname" . }}-default-conf
            defaultMode: 420
        - name: sitemap-json
          configMap:
            name: {{ include "yinglong-frontend.fullname" . }}-sitemap-cm
            defaultMode: 420
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh
            - "-c"
            - |
              sed -i 's/SW_AGENT_NAME/yinglong-frontend-{{ .Release.Namespace }}/g' /usr/share/nginx/html/static/js/app*
              sed -i 's/SW_AGENT_COLLECTOR_BACKEND_SERVICES/{{ .Values.skywalking.oap.rest | replace "/" "\\/" }}/g' /usr/share/nginx/html/static/js/app*
              nginx -g "daemon off;"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: default-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: sitemap-json
              mountPath: {{ .Values.nginx.shareDir }}/sitemap.json
              subPath: sitemap.json
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
