apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret-client-cephfs
  namespace: cephfs
type: kubernetes.io/rbd
data:
  # ceph fs authorize cephfs client.cephfs / r /data rw
  # ceph auth get-key client.cephfs | base64
  key: QVFBemNZVlo2c2JKTGhBQTdxQ0J5d00raVBSZ0FHOTdGdG9YSXc9PQ==