apiVersion: v1
kind: Secret
metadata:
  name: cephfs-admin-secret
  namespace: cephfs
type: kubernetes.io/rbd
data:
  key: QVFBM3ZmdGhtZmJuSUJBQVN6S2lCUkVuV3JrR0x2NDc5OVJrMFE9PQ==
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cephfs-dynamic
provisioner: ceph.com/cephfs
parameters:
  monitors: 10.1.9.21:6789,10.1.9.22:6789,10.1.9.23:6789
  adminId: admin
  adminSecretName: cephfs-admin-secret
  adminSecretNamespace: cephfs
  pool: cephfs_pool
  claimRoot: /data

