apiVersion: v1
data:
  # ceph auth get-key client.admin
  # AQBx/Z5hnu3nBhAAmRkm0fhNtf9km8LHu8+qsw==
  key: QVFCeC9aNWhudTNuQmhBQW1Sa20wZmhOdGY5a204TEh1OCtxc3c9PQ==
kind: Secret
metadata:
  name: cephfs-admin-secret
  namespace: kube-system
  selfLink: /api/v1/namespaces/kube-system/secrets/cephfs-admin-secret
type: kubernetes.io/rbd
---
# apiVersion: v1
# data:
#   # ceph auth add client.k8s mon 'allow r' osd 'allow rwx pool=k8s'
#   # ceph auth get-key client.k8s | base64
#   key: QVFCbVJLdGhod3lCRWhBQW0xNXM3c0k4WjJlcFp4OTFBTjl4aUE9PQ==
# kind: Secret
# metadata:
#   name: cephfs-user-secret
#   namespace: cephfs
# type: kubernetes.io/rbd


# kubectl create secret generic cephfs-secret --type="kubernetes.io/rbd" \
# --from-literal=key=AQBx/Z5hnu3nBhAAmRkm0fhNtf9km8LHu8+qsw== \
# --namespace=kube-system