#!groovy

@Library('devopslib@tigger') _

//变量名，用于存储input步骤的返回值
def approvalMap
// K8S启动用包名
def package_file
// 文件路径
def package_path
// 文件名
def file_name
// 上传到nexus文件
def packageFilename

pipeline {
    options {
        timeout(time: 1, unit: 'HOURS')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/yaml/jenkins-package-agent.yaml'
        }
    }

    parameters {
        string(name: 'commitId_back', defaultValue: 'newten-qa', description: '后端Repo(KAP)的branch或者commitid（必填）')
        string(name: 'commitId_front', defaultValue: '', description: '前端repo(KAP_Frontend)的branch或者commitid（不填不拉取和替换KAP中前端repo的代码）')
        string(name: 'version', defaultValue: '4.5.10', description: '填写版本号，格式：4.5.10，4.3.11，前两位版本号必须规范')
        choice(name:'envStage', choices:'DEV\nRC\nGA', description:'打包阶段' )
    }

    stages {
        stage('1.Pull Code') {
            steps {
                container('build') {
                    dir('sourcecode') {
                        script {

                            if(!commitId_back){
                                error 'commitId_back 不能为空'
                            }

                            echo '1 - GIT_COMMIT: ${GIT_COMMIT}, GIT_BRANCH: ${GIT_BRANCH}, BRANCH_NAME: ${BRANCH_NAME}'
                            echo 'Sync the git mirror'
                            sshCmdWithCredentials(
                                'bash -c /var/lib/git/pull.sh',
                                'private_git',
                                ['name':'localhost', 'host':'10.1.2.192', 'allowAnyHosts': true]
                            )

                            echo 'checkout KAP'
                            retry(3) {
                                githubCheckout 'KAP', params.commitId_back
                            }

                            echo '2 - GIT_COMMIT: ${GIT_COMMIT}, GIT_BRANCH: ${GIT_BRANCH}, BRANCH_NAME: ${BRANCH_NAME}'

                            if (!params.commitId_front) {
                                echo 'not checkout KAP_Frontend'
                            }else {
                                echo 'checkout KAP_Frontend to kystudio'
                                sh 'rm -rf ./kystudio'
                                dir('kystudio') {
                                    retry(3) {
                                        githubCheckout 'KAP_Frontend', params.commitId_front
                                    }
                                }
                            }

                            echo '3 - GIT_COMMIT: ${GIT_COMMIT}, GIT_BRANCH: ${GIT_BRANCH}, BRANCH_NAME: ${BRANCH_NAME}'
                        }
                    }
                }
            }
        }
        stage('2.Building Package') {
            steps {
                container('build') {
                    dir('sourcecode') {
                        script {
                            dir('kystudio') {
                                sh """
                                    rm -f .npmrc
                                    echo "registry = 'http://mvn.ops.kylincorp.com/repository/npm-public/'" > .npmrc
                                    cat .npmrc
                                """
                            }

                            if (!version) {
                                error 'version 版本号不能为空'
                            }

                            buildNewten(params.version, false, false)
                            archiveArtifacts artifacts: 'dist/*.tar.gz', fingerprint: true, followSymlinks: false, onlyIfSuccessful: true

                            if (version.startsWith('4.5.') || GIT_BRN) {
                                package_path = "artifacts/4.5.x/${params.envStage}"
                            }else if (version.startsWith('4.3.')) {
                                package_path = "artifacts/4.3.x/${params.envStage}"
                            }else {
                            // nothing to do
                            }
                            println "package_path: ${package_path}"

                            def commitid = sh(returnStdout:true, script: "git rev-parse --short HEAD | sed -e 's/\r//g'").trim()
                            println "commitid: ${commitid}"

                            file_name = "KE-${version}-${params.envStage}-${BUILD_NUMBER}-${commitid}.tar.gz"
                            println "file_name: ${file_name}"

                            packageFilename=sh(script: """
                                mkdir -p package
                                cp dist/*.tar.gz package/${file_name}
                                echo "package/${file_name}"
                            """, returnStdout:true).trim()
                            println "packageFilename: ${packageFilename}"

                            package_file=sh(script: """
                                mkdir -p /var/cicd/${package_path}
                                mv dist/*.tar.gz dist/${file_name}
                                cp dist/*.tar.gz /var/cicd/${package_path}
                                echo "newten-cicd/${package_path}/${file_name}"
                            """, returnStdout:true).trim()
                            println package_file
                        }
                    }
                }
            }
        }
        stage('3.Tars to nexus') {
            steps {
                container('build') {
                    dir('sourcecode') {
                        script {
                            println package_file
                            withCredentials([usernamePassword(credentialsId: 'nexus-raw', passwordVariable: 'passwd', usernameVariable: 'user')]) {
                                pushRawArtifactsByApi('raw-tars-hosted', package_path, packageFilename, file_name, user, passwd)
                            }
                        }
                    }
                }
            }
        }
    }
}
