#!groovy

@Library('devopslib') _

pipeline {
    options {
        timeout(time: 2, unit: 'HOURS')
    }

    agent {
        kubernetes {
            yamlFile 'pipelines/yaml/jenkins-package-agent.yaml'
        }
    }

    parameters {
        choice(name: 'module', choices: ['all', 'chongqingchangan', 'yinlianshangwu', 'yum', 'zhaoshangjinke'], description: '指定运行的模块名称')
        string(name: 'keVersion', defaultValue: '', description: 'ke version\n for example: 4.5.17.0')
        choice(name: 'option', choices: ['isDeploy', 'isIT'], description: 'deploy or integration test')
    }

    environment {
        ENVIRONMENT_TEST_FLAG = 'NO'
    }

    stages {
        stage("Checkout Source Code") {
            steps {
                container("build") {
                    dir("custom-user-manager-4x") {
                        script {
                            retry(3) {
                                githubCheckout 'custom-user-manager-4x', 'main', 'https', 'github.com', '+refs/pull/*:refs/remotes/origin/pr/* +refs/heads/*:refs/remotes/origin/*', 'kyligence-git', 'Kyligence'
                            }
                        }
                    }
                }
            }
        }

        stage('Maven Install') {
            steps {
                container("build") {
                    sh "cat /root/.m2/settings.xml"
                    dir("custom-user-manager-4x") {
                        script {
                            sh script: """
                                    git branch
                                    mvn -Dkap.version=5.0.0-ke-${params.keVersion} clean install -DskipTests
                                """
                        }
                    }
                }
            }
        }

        stage('copy_file_to_remote') {
            steps {
                container('build') {
                    dir("custom-user-manager-4x") {
                        timestamps {
                            script {
                                cmd = "rm -rf /opt/custom-user-manager-4x"
                                echo "cmd: ${cmd}"
                                sshCmdWithCredentials(
                                        cmd,
                                        'shuiaileiroot',
                                        ['name': 'localhost', 'host': '10.1.2.181', 'allowAnyHosts': true]
                                )
                            }
                            script {
                                def remote = [:]
                                def file_name = "./../custom-user-manager-4x"
                                def remote_path = "/opt"
                                def remote_ip = "10.1.2.181"
                                remote.name = 'server_test_env'
                                def credentials = "shuiaileiroot"
                                withCredentials([usernamePassword(credentialsId: credentials,
                                        usernameVariable: 'REMOTE_USERNAME',
                                        passwordVariable: 'REMOTE_PASSWORD')]) {
                                    remote.user = REMOTE_USERNAME
                                    remote.password = REMOTE_PASSWORD
                                }
                                remote.host = remote_ip
                                remote.allowAnyHosts = true
                                sshPut remote: remote, from: file_name, into: remote_path
                                sshCommand remote: remote, command: """
                    ls -lh ${remote_path}
                """
                            }
                        }
                    }
                }
            }
        }
        stage('test_prepare') {
            when {
                expression {
                    return params.module != 'zhaoshangjinke'
                }
            }
            steps {
                container("build") {
                    dir("custom-user-manager-4x") {
                        script {
                            def installDir = "/opt"
                            def keVersion = "${params.keVersion}"
                            def module= "${params.module}" == 'all' ? "chongqingchangan" : "${params.module}"
                            def host = "10.1.2.181"
                            def moduleVersion = sh(script: " mvn help:evaluate -Dexpression=sub.version -pl ${module} | grep -v \"INFO\" | grep -v \"WARNING\" | tail -n 1 ", returnStdout:true).trim()
                            cmd = "sh " + installDir + "/custom-user-manager-4x/benchmark/src/main/resources/script/prepareKEEnvironment.sh  " + keVersion + " " + moduleVersion + " " + module
                            echo "cmd: ${cmd}"
                            sshCmdWithCredentials(
                                    cmd,
                                    'shuiaileiroot',
                                    ['name': 'localhost', 'host': host, 'allowAnyHosts': true]
                            )
                            echo "ssh cmd send success"
                            echo "Listen for the KE running status"
                            def url = "http://10.1.2.181:7080/kylin/api/system/license"
                            def i = 0
                            retry(10) {
                                echo "Get KE Status ${++i} "
                                try {
                                    def response = httpRequest     \
                                                httpMode: 'GET',
                                            contentType: 'APPLICATION_JSON',
                                            url: url
                                    def status = response.status
                                    echo "status: ${status}"
                                } catch (e) {
                                    sleep(time: 30, unit: "SECONDS")
                                    echo "check KE status exception: ${e}"
                                    sh 'exit 1'
                                }
                            }
                        }
                    }
                }
            }
        }
        stage('testCI') {
            when {
                expression {
                    return params.module != 'zhaoshangjinke'
                }
            }
            steps {
                container("build") {
                    dir("custom-user-manager-4x") {
                        sh script: """
                            mvn test -Dtest=io.kyligence.kap.TestCI#testCI -pl benchmark
                        """
                    }
                }
            }
        }

        stage('Deploy') {
            when {
                expression {
                    return params.option == 'isDeploy'
                }
            }
            steps {
                container("build") {
                    dir("custom-user-manager-4x") {
                        script {
                            sh script: """
                                   sh benchmark/src/main/resources/script/deployRelease.sh ${params.keVersion}
                                """
                        }
                    }
                }
            }
        }

        stage("doTag") {
            when {
                expression {
                    return params.option == 'isDeploy'
                }
            }
            steps {
                container("build") {
                    dir("custom-user-manager-4x") {
                        script {
                            def sdkVersion = ''
                            if (params.module == 'all') {
                                sdkVersion = sh(script: " mvn help:evaluate -Dexpression=revision | grep -v \"INFO\" | grep -v \"WARNING\" | tail -n 1 ", returnStdout:true).trim()
                            } else {
                                sdkVersion = sh(script: " mvn help:evaluate -Dexpression=sub.version -pl ${params.module} | grep -v \"INFO\" | grep -v \"WARNING\" | tail -n 1 ", returnStdout:true).trim()
                            }
                            echo "sdkVersion: ${sdkVersion}"
                            if (!sdkVersion.contains("-SNAPSHOT")) {
                                def _tag = "v-" + params.module + "-" + sdkVersion
                                githubHelper 'TAG', "main", 'custom-user-manager-4x', _tag
                            }
                        }
                    }
                }
            }
        }
    }
}
