@Library('devopslib') _
pipeline { 
    agent any 
    
    stages {
        stage('Example'){
            steps {
            echo 'Hello world'
            }
        }
    }
    //
    post {
        success {
            emailext (
                subject: "SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
                to: "fuzhou.sun@kyligence.io",
                from: "internal.notice@kyligence.io",
                //定义html 模版
                body: """<p>FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
                    <p>Check console output at "<a href="${env.BUILD_URL}">${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>"</p>"""
            )
        }
    }
    //
}
